### ISSUE TITLE
QUEST "Hidden Enemies" not working

### ISSUE THREAD

**Issue by Thrombor2017** [LightsHope/issues#10]
http://vanillawowdb.com/?quest=5727

The part where we have to "Gauge Neeru Fireblade's reaction to you being a member of the Burning Blade" doesn't work, when clicking on the NPC, we have the option "you may speak frankly Neeru"(or something like this) but then the next dialog doesn't bring us to the next one, we are stuck here and so the quest objective can not be completed.

Lot of people gave evidence of this bug on the forum : https://forum.lightshope.org/viewtopic.php?f=9&t=10731

**Comment by brotalnia** [comment]
Unable to reproduce. Quest works as intended on development branch.

https://streamable.com/jad9k
