### ISSUE TITLE
[QUESTION] Gothik The Harvester - Undead Spectral mob spawns - immune to all magic including Holy?

### ISSUE THREAD

**Issue by theloras** [LightsHope/issues#100]
Spectral Horse - http://classicdb.ch/?npc=16149
Spectral Rider - http://classicdb.ch/?npc=16150
Spectral Trainee - http://classicdb.ch/?npc=16127
Spectral Death Knight - http://classicdb.ch/?npc=16148

Are these mobs supposed to function like Blackwing Spellbinders in BWL - http://classicdb.ch/?npc=12457 and be immune to ALL 6 magic schools or should they function like Emperor Vek'nilash in AQ40 - http://classicdb.ch/?npc=15275#drop and be immune to 5 out of the 6 excluding Holy?

Even the wiki description seems to suggest the latter and the mobs being immune to most but not all magic:

_All of the NPCs on the dead side are immune to most magical abilities so the dead side in comprised mainly of Rogues, Warriors, Druids and Paladin/Shaman._
http://wowwiki.wikia.com/wiki/Gothik_the_Harvester_(original)

**Comment by GuybrushGit** [comment]
They are currently not immune to holy.

**Comment by theloras** [comment]
sorry my bad - Retfavre had said that they were immune to Holy the other but later said that he was thinking of the Blackwing Spellbinders - I had missed the latter part of his conversation.
