### ISSUE TITLE
Head of Nefarian disappeared.

### ISSUE THREAD

**Issue by Dwamz** [LightsHope/issues#103]
So myself and other people in my guild, Sator and myself Dwamz have had our Head of Nefarian removed from our bags, the quest is gone as well. The one thing I can add to it is I did have the quest of it accepted, ready to turn in. But yes the Head is completely gone out of our bags. I believe there have been several issues with Heads and Hearts recently with people being able to see them on the corpses of the bosses even though they've previously completed the quest. So if I could get myself a new Head of Nefarian before our Sunday raid that would be much appreciated!

Thank you, Dwamz.

**Comment by GuybrushGit** [comment]
See https://forum.lightshope.org/viewtopic.php?f=8&t=486 for item recovery.

**Comment by Dwamz** [comment]
I don't have a video of the entire run, and it is in a sense an epic item. But since it's more of a quest item can I get it restored by providing the item ID and quest reward ID?

**Comment by thepparker** [comment]
Contact a Game Master through an in-game ticket and see if they are able to do anything for you. Items don't disappear unless you were rolled back after a crash.
