### ISSUE TITLE
Stonescale swarm spawns

### ISSUE THREAD

**Issue by curacaoblue** [LightsHope/issues#105]
Just like stated in bugreport #98 for Darrowshire there are no Stonescale eel pools spawning in Feralas on Light's hope too. According to the database there should be ones spawning in Feralas, Tanaris, Azshara and Stv. While i didn't check on Azshara i couldn't find a single pool in Stv and Feralas. The only spawns i found are 68.6/23.0 and 67.8/23.2 in Tanaris which spawn at a rate of 1/3min each. This seems way too high to me. Feels like all of Azeroths stonescale eel swarm spawns are limited to these two spawns right now.

**Comment by Byste** [comment]
By light's hope, do you mean lightbringer? Darrowshire is a light's hope server.
