### ISSUE TITLE
Can't swap trinket.

### ISSUE THREAD

**Issue by medremo** [LightsHope/issues#1066]
Hello, on the server Lightbringer after the last maintenance work(31.10.2018), there was a problem with the Swap Trinkets, neither hunt through the FD(fake death), Neither  Rogue through the Vanish could not swap the trinkets on the boss fight, is this how the mechanic should work? or is it a bug or something similar?

**Comment by someotherplayer** [comment]
Can confirm.
All our Rogues and Hunters have the same problem. Trinket swapping during boss fights with vanish/FD is not working anymore and I am pretty sure this used to work in vanilla.

**Comment by Holyfrogg** [comment]
Possibly unrelated, but I have noticed that queueing up a trinket during combat using TrinketMenu in areas where you drop and enter combat frequently like the BRD lyceum sometimes dont swap the trinket properly.

I had never had an issue in 200+ BRD runs until recently.

**Comment by PugzM** [comment]
Yes this is definitely an issue. Rogues in my guild can no longer use vanish to swap trinkets mid fight in almost any fight in BWL / AQ40 / or Naxx. This also affects hunters in the same way but also prevents them from dropping new traps mid fight. It's definitely not blizz-like behaviour either so this needs a fix.

**Comment by RizlaDNB** [comment]
Confirmed. Trinket swaping not working using Trinketmenu, Itemrack and Outfitter.

**Comment by PugzM** [comment]
Just to add a bit of extra detail to this. It seems to be to do with global combat. The speed at which global combat re-engages following a vanish or feign death is so fast that addons (trinket menu, outfitter, itemrack) / macros / quick fingers are now unable to swap out gear in time before you're back in combat. This is irrespective of whether or not there is low ping. Sometimes global combat is not dropping at all following a vanish or feign death also so this actually breaks many normal game mechanics for hunters and rogues.
