### ISSUE TITLE
Shaman Water totem Bug, Part (6) Elementals

### ISSUE THREAD

**Issue by brunnomoreno** [LightsHope/issues#1081]
Arriving at the place of the elementals, they were visible and immobile and you can not attack them and pick up the quest items.

**Comment by Gyronell** [comment]
Someone probably killed it before you, I was confused too when I did this. He spawned later though.

**Comment by brunnomoreno** [comment]
still with problem, I'll have to wait for the server to restart =(

**Comment by brunnomoreno** [comment]
now ok =D
