### ISSUE TITLE
Goldseller !

### ISSUE THREAD

**Issue by LordGvin** [LightsHope/issues#1084]
Goldseller wrote me i
![wowscrnshot_111218_034403](https://user-images.githubusercontent.com/37159435/48320882-2ac1de80-e62f-11e8-97fb-da27b1c8881e.png)
n PM and since then it is forbidden to sell gold please punish him properly !

**Comment by Godmatik** [comment]
GMs aren't on this github, it's only for reporting bugs.

Open a ticket in-game to report this to a GM.
