### ISSUE TITLE
Hello, please help me to see why my character, the crit attribute is 0%

### ISSUE THREAD

**Issue by xiaohua7777** [LightsHope/issues#1086]
Hello, please help me to see why my character, the crit attribute is 0%，My account is xiaohua7777，user is “Cicicicici”
https://i.redd.it/tk3om5jjawx11.png 

Please look at this picture.

**Comment by Gamemechanicwow** [comment]
Most likely its just an UI error, caused by a buggy addon. Can you crit when you attack?

Try to disable your addons.

**Comment by Godmatik** [comment]
Probably because the weapon skill of what you are using is at 1 or extremely low.
