### ISSUE TITLE
Ooze Covered Mithil Vein have no loot

### ISSUE THREAD

**Issue by elcasai** [LightsHope/issues#111]
hi i cant loot ooze covered mithril veins but every other mining nodes i deleted my wdb and wtf and it still doesnt work i had this bug on other charackters before and gms fixed it i know you can i get skillpoint but not a single loot https://www.youtube.com/watch?v=MdC2UMgG0jA&feature=youtu.be

**Comment by GuybrushGit** [comment]
Old issue but don't know what causes it, never happens on dev.

**Comment by elcasai** [comment]
d i need to unlearn mining now and skill again or what is to do ?

**Comment by GuybrushGit** [comment]
No don't unlearn. Find other places to mine.

**Comment by elcasai** [comment]
but i want mine there its perfekt for leveling and mining :( i know gm can fix it got the same problem on old elysium on my other account / main  GM smoke did fix it i dont know how but he did it. is he in your team or on elysium team ? . it would be nice if you can fix it too . sry for my bad english i dont understand all but i try

**Comment by GuybrushGit** [comment]
Happens to characters under level 35.

**Comment by elcasai** [comment]
ok ty

**Comment by GuybrushGit** [comment]
Dont close its not fixed yet.
