### ISSUE TITLE
Invite/Whisper - <error>

### ISSUE THREAD

**Issue by sxe-dante** [LightsHope/issues#1110]
Cant invite people in party and whisper , its says <error> - http://prntscr.com/ll5wcz
I seen other people that has same problem after maintenance 21.11.2018
Server: Northdale
Character: Fenixon

I Already tryed to OFF all addons and clean wdb folder

**Comment by karlzila1** [comment]
Same, I wonder if it's to do with character level. 
Character: "Middgee"

**Comment by Totier** [comment]
You are too low level.

These restrictions are in place until level 15, in order to prevent spam.

 - Senior GM Totier

**Comment by karlzila1** [comment]
Thanks. Ending up working that out through leveling anyways, thanks though
XD
