### ISSUE TITLE
Invite/Whisper - <error>

### ISSUE THREAD

**Issue by Warnexx** [LightsHope/issues#1113]
Cant invite people in party and whisper
I seen other people that has same problem after maintenance 21.11.2018
Server: Northdale
Character:Magnexx

**Comment by jjadin** [comment]
I have the same problem, everything is correct but invite other player tips <error> on screen.
Server: Northdale
Character: Saluka

**Comment by 18ivan18** [comment]
Same problem here
Server: Northdale
Character: Tinyflame

**Comment by sanmor1690** [comment]
Same problem here
Server: Northdale
Character: Sancaza

**Comment by W1sefox** [comment]
Same problem here
Server: Northdale
Character: Wisefox

**Comment by kovsey** [comment]
Same issue 
Server: Northdale
Character: Unihorn

**Comment by ghost** [comment]
Same issue, cant chat in say,general,world and whisper! Please fix is ASAP its unplayable, its like playing alone in server, totally insulation if you are not in guild...
Server: Northdale
Character: Lightss
