### ISSUE TITLE
Ret pally issue #1 Lifestealing

### ISSUE THREAD

**Issue by Dualityz** [LightsHope/issues#1115]
The Lifestealing enchantement does not scale with spell power as it is supposed to. That is a very, very big issue for retribution paladins.

**Comment by Hanzemon** [comment]
Absolutely agree, in early patches Lifestealing scaled with both Spell damage and healing giving it 200% the efficency intended.

It was changed in patch 1.7 to only be affected by +spell damage:

All item based self heals will no longer be effected by equipment that provides bonuses to healing. This change affects both the Arcanite Champion and the Crusader Enchantment.

**Comment by Dualityz** [comment]
Adding to this, it is also unaffected by shadow power elixirs, which is an even bigger problem...

**Comment by Dualityz** [comment]
Following up on paladin bug reports, some mobs seem to have holy resistance.
 This has been discussed past on Elysium and Nost : no mobs should ever have holy resistance. 
The only time holy spells should be resisted should be with regards to the level on the mob compared to the level of the paladin, and they should either be fully resisted or not at all. 
![wowscrnshot_112818_141724](https://user-images.githubusercontent.com/45302442/49155867-43631180-f31c-11e8-8f22-4d05712cbb44.jpeg)

**Comment by Holyfrogg** [comment]
Agree. The fact that lupos does shadow damage proves that the developers consider the scope of progressive itemization to go beyond just stats. This should be changed to accurately reflect how Vanilla used to work.
