### ISSUE TITLE
Texting problem(Say,whisper,general,World)

### ISSUE THREAD

**Issue by ghost** [LightsHope/issues#1118]
Hello, I have a problem. Nobody can see what I text in Say,General,World,Whisper and maybe party channel  I am not sure. I can see incoming whispers or any other text by players! I can text just in Raid chat it works good. Character Lightss. Thanks!

**Comment by dinsfireyo** [comment]
Delete your chat cache

Go to WOW folder > WTF > Account > Server > Character >  delete chat-cache file

**Comment by ghost** [comment]
Man, thanks for advice but i tried it. I deleted even all wow...nothing.
