### ISSUE TITLE
Mobs having Holy Resistance

### ISSUE THREAD

**Issue by Dualityz** [LightsHope/issues#1122]
Following up on paladin bug reports, some mobs seem to have holy resistance.
This has been discussed in the past on Elysium and Nost : no mobs should ever have holy resistance.
The only time holy spells should be resisted should be with regards to the level on the mob compared to the level of the paladin, and they should either be fully resisted or not at all.
![49155867-43631180-f31c-11e8-8f22-4d05712cbb44](https://user-images.githubusercontent.com/45302442/49188789-4980de80-f36c-11e8-938e-a2fa9dcf58b5.jpeg)

**Comment by Dualityz** [comment]
Reopened as It just happened again in AV.

**Comment by Gamemechanicwow** [comment]
Seal of Command partial resists against higher level targets are indeed Blizzlike and are the result of level based resistance not actual Holy Resistance.

Video from vanilla retail 2006 where you can see same mechanic:
https://www.youtube.com/watch?v=ovhRqAxnXqg

**Comment by dinsfireyo** [comment]
Sounds like  level based  resist

**Comment by Dualityz** [comment]
I didnt know that could happend, thank you !
