### ISSUE TITLE
2/9 Warlock T3 set bonus Bug

### ISSUE THREAD

**Issue by CMCalamitas** [LightsHope/issues#113]
**The server or game patch that the issue pertains to:** Darrowshire, 1.11

**A clear, concise description of the current behavior:** Shadowbolts are not healing the caster while having 2/9 T3 equipped.

**A description of the expected behavior:** After a Shadowbolt lands, there should be a 10-15% chance (only unreliable sources -> player comments on archived thottbot) to heal the caster for 270-330 HP.

**Where applicable, provide relevant sources that show or describe the correct behavior**:
https://web.archive.org/web/20071227181543/http://thottbot.com:80/?set=529
https://web.archive.org/web/20090405043053/http://thottbot.com:80/s28831

**Comment by GuybrushGit** [comment]
Works in dev.

**Comment by yeahmate** [comment]
Can somone else try and test this on Darrowshire. It isnt working in my opinion. We have seen incorrect set bonuses many times on Darrowshire. I would not be surprised if this is the case again.

**Comment by yeahmate** [comment]
Ok since the recent maintainace can confirm that the proc is working.
