### ISSUE TITLE
Mount sound effect

### ISSUE THREAD

**Issue by Rockanhe** [LightsHope/issues#114]
Hello good people of LH
For some reason i can't hear any noise from my mounts when pressing spacebar, i tried it with different mounts and characters. But i can hear other people mounts when they press spacebar, and other people told me they have the same problem.
Thank you for your time and keep up the good work.

**Comment by Rockanhe** [comment]
hello?

**Comment by GuybrushGit** [comment]
Client issue, some mounts dont have the sound working for some reason.
