### ISSUE TITLE
 character disappeared

### ISSUE THREAD

**Issue by mylichao84** [LightsHope/issues#1140]
Role information: 
Server Name：Lightbringer           
Camps: Alliance            
Race: Human            
Gender: Female            
Occupation: Rogue            
Exception Description:            
On Dec 5, 2018, after the server was updated, the login account found that the Rogue character disappeared. There was no response to the new character appeal.            Please help solve.            
Account information:            
Account number: sxxjackson
ID：Luguaner      
TYWM!!

**Comment by Kittnz** [comment]
Please write this in a gm ticket, no support here.
