### ISSUE TITLE
Not possible to use things together, at the same time, at once, simultaneously GLEICHZEITIG

### ISSUE THREAD

**Issue by bugbringer** [LightsHope/issues#1143]
I remember many players were reporting a bug with the usage of trinkets combined with other spells like frostbolt, didn't really work out smoothly. The error-message "Another action is in progress" appeared. This bug was fixed i think in early 2018.

But the issue is still there with other items and spells that aren't on global cooldown, like Iron Grenade and Counterspell. 

It's not possible to use counterspell and fire blast at the same time. It should be possible for sure. No, it's not the server being delayed or something, because both are instants.

I'd like to play real vanilla wow properly before classic wow gets released and kills all blizzlike vanilla servers.

**Comment by Gamemechanicwow** [comment]
are you using spellstopcasting ?

**Comment by bugbringer** [comment]
Yes, I am. But that doesn't matter. You get same result without spellstopcasting. How can you stop casting an instant spell, haha.

**Comment by bugbringer** [comment]
Here an example how it should be: https://youtu.be/RfY8Egsd6C8?t=618

Or watch this: https://youtu.be/CStaLR0ipxY?t=181

No fucking "Another action is in progress"....
