### ISSUE TITLE
Buff not working, Rallying cry of the Dragonslayer

### ISSUE THREAD

**Issue by uanz** [LightsHope/issues#115]
on the Buff it says " Increases critical chance of spells by 10%, melee and range by 5% and grants 140 attack power. 120 minute duration" 

this buff only applys to the melee attack power for hunters , if it where only for melee attack power the buff should state this, as it stands it should apply both to melee and range but issent. this gives Hunters a dissadvantage in raids and the use of this world buff, hunters fall behind on the dps and cant realy compete dps wise, this also results that hunters are unwanted sometimes due to high dps beeing needed to achive progress at high end raid bosses .

**Comment by marchelzo** [comment]
That's blizzlike. In fact, if the server were really blizzlike, Juju Might and Fengus' Ferocity would also only give melee AP. Consider yourself lucky.
