### ISSUE TITLE
The blood craze issue

### ISSUE THREAD

**Issue by babymikkel** [LightsHope/issues#1156]
Darkknightz-Northdale Patch unknown.
Date: 17-12-2018

There is an issue with the blood craze talent for fury warriors were, even tho you have 3 points in it which should give me 3 % health back, but only gives me 1 %

**Comment by magp3** [comment]
Blood craze does not procc for my warrior at all currently.

**Comment by babymikkel** [comment]
Of you try to relog you might get some use back, No garanti :/

**Comment by magp3** [comment]
@babymikkel Yea for some reason it started working lately.. Strange

**Comment by bladezLH** [comment]
Blood Craze works in a silly way:
T1: 1 tick after 6 seconds
T2: 2 ticks in 6 seconds (every 3 sec)
T3: 3 ticks in 6 seconds (every 2 sec).

It is working correctly.
