### ISSUE TITLE
Anticheat is Not 100% accurate

### ISSUE THREAD

**Issue by lebelsao** [LightsHope/issues#1162]
my accounts was banned，and I had submitted my ban appeal a few days，but I just received it by GM (I have reviewed your ban and found our Anticheat to be working properly. Your account will remain banned.).the Anticheat working properly is not be convinced,At least tell me if  I used an accelerator or something else. I swear I haven't used any cheating software. So here comes the question... Why is my account banned？ 
a weeks ago,the same thing happened in my accounts,My main network disconnection,As a result of raids,so i use my mobile phone HOT POINT function，the network has change to 4Gs, A few minutes later I was banned. this thing happened twice，I think Anticheat is bug. My WiFi is off, but the routing is not off, and the server defaults that you are not off, so go on for a while before it disappears. So it was identified as flash move,Or because the delay is too high, let other players report as flash move.
Northdale,I've been playing for seven months and cherish my account very much. Do not use cheating procedures for an unreasonable reason. If as I said, there is something wrong with Anticheat, please approved my account number,my account is (marshalcao). My English is not good, I hope you can understand.

**Comment by babymikkel** [comment]
Well if a GM returned to you and said that the anticheat system is working properly, then you have been cheating. ''He'' might have checked out your account and seen what you have been banned for and determined that you indeed cheated. 
Don't think that a wifi switch, can set of the anticheat software. Correct me if i'm wrong.
