### ISSUE TITLE
hello! i can't send any whispers to anyone!

### ISSUE THREAD

**Issue by anticitizen81** [LightsHope/issues#1163]
hello! i can't send any whispers to anyone
Char : Killrath lvl60 warrior in Northdale server

**Comment by anticitizen81** [comment]
can some one help me ! i am not gold seller dammit!

**Comment by yoyosan** [comment]
Read https://www.lightshope.org/faqs/faq-mutes

**Comment by Kittnz** [comment]
Please write this in a gm ticket, no support here.
