### ISSUE TITLE
can GM help me?

### ISSUE THREAD

**Issue by sun1115446061** [LightsHope/issues#1177]
Please check my account information. ID:Truman.The reason for the ban is to use the bug. but im played with my friend. why he is safety.can GM help me ?I have been complaining on the official website for three days. but no one back to me.

**Comment by Gamemechanicwow** [comment]
> Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development.

**Comment by sun1115446061** [comment]
no one answer me

**Comment by Kittnz** [comment]
Please write this in a gm ticket, no support here.
