### ISSUE TITLE
Hunters should NOT recieve loot and exp if pet solo mobs

### ISSUE THREAD

**Issue by placoto99** [LightsHope/issues#118]
It is possible to have the pet fight one mob while the Hunter attacks another. Note: the Hunter will not gain loot or experience from a mob that the pet kills solo. This is a deliberate decision by Blizzard, not a bug. If you intend on pulling multiple mobs and having your pet kill one or more of them while you focus on others, it would be best to try to get at least one shot or hit on each of the mobs and then allow your pet to do its work on them.

http://wowwiki.wikia.com/wiki/Hunter_pets

I started playing wow before 2.2.0 and this was true (avoid player afk farming)

I checked all patch released between 1.1 and 2.2.0 nowhere it said that pets can no longer get experience and loot from pet so that mean's that it was always been part of wow release in 2004.

**Comment by crackyoo** [comment]
This is true. You didn't get any xp or loot if your hunter or warlock pet soloed a mob, you needed to deal at least 1 damage yourself. 
Blizzard did this to prevent people from farming lower level mobs while tabbed and looting every 5mins, for example.
