### ISSUE TITLE
Redemption quest

### ISSUE THREAD

**Issue by yoyosan** [LightsHope/issues#1199]
Hello.

The [Redemption quest](http://classicdb.ch/?quest=5742) from Tirion Fordring in Eastern Plaguelands is bugged. Nothing happens after I accept the quest and try to talk with him.

**Comment by dinsfireyo** [comment]
if you pull a spider from the nearby cave near him he will kill it and he will "reset". Atleast that worked for me but that was a few months ago gl

**Comment by dinsfireyo** [comment]
you know when tirion tells you to sit and listen


He wants you to actually /sit and listen to him learn to read

**Comment by yoyosan** [comment]
You're right. Thank you.
