### ISSUE TITLE
Joining the dev team?

### ISSUE THREAD

**Issue by mheine94** [LightsHope/issues#1201]
Hello LightsHope Team!

I enjoy the server you and your colleagues run very much. 
I am from Germany and I currently study for my masters degree in computer science. 
At the moment I am working as a backend developer for the medical computer science department of the university.

If your team could use another developer i would be very interested in joining you as i am a huge fan of the game since late vanilla and bc.
Through my studies and work I have experience  in programming in c++, c, assembler, java, python, javascript and some exotic scientific languages.

I would be happy to hear from you.

Greetings from Germany

**Comment by bladezLH** [comment]
https://github.com/lh-server/core if you wish to contribute. Pick an issue of your choosing and work through it.
