### ISSUE TITLE
Mouse cursor size is bugged

### ISSUE THREAD

**Issue by DunnersND** [LightsHope/issues#1209]
Yo so when I logged in today, I immediately noticed a difference in the text size on the login screen.  It was bigger and a little blurry.  When I logged in, my mouse cursor was TINY.  Like 1/10th the size of what it normally is.  Whenever I drag items from bag space/action bar, the item icon shrinks down to about 1/10th to the size of what it should be.  I've tried restarting my PC, deleting my WDB, and copying over WTF interface files from other accounts.  Nothing has worked... any suggestions?
![img_3188](https://user-images.githubusercontent.com/47170184/51962836-b83af080-241e-11e9-8a3c-0de4a25ce0eb.JPG)
![img_3186 1](https://user-images.githubusercontent.com/47170184/51962837-b83af080-241e-11e9-9841-e2ba894d5a63.JPG)
![img_3187](https://user-images.githubusercontent.com/47170184/51962838-b8d38700-241e-11e9-8b01-88c00d39d7ba.JPG)

**Comment by Nimbix-wow** [comment]
try to disable all addons and see if that fixes it.
