### ISSUE TITLE
Warlock talents not working properly

### ISSUE THREAD

**Issue by warlockdudes** [LightsHope/issues#123]
Several Warlock talents do not work.
Improved Drain Life is suppose to give extra % to the spell. I've specced 3 points into it but it still only drains 10 hp when used. No improvement,

Also Demonic Embrace which should give 3% stamina and decrease 1% spirit does not increase any hp when specced into. I've watched my hp stay the same when speccing.

Please look into this!

**Comment by placoto99** [comment]
Sorry to tell you that I'm not a dev and its working for me and for everyone else... Your issue with be mark invalid in a few mins.
