### ISSUE TITLE
Buff of improved battle shot not showing correct attack power

### ISSUE THREAD

**Issue by Mynnaa** [LightsHope/issues#1230]
Hi,

After having contacted a GM, he suggested me to post this bug here.
It's quite simple. I have the the talent "improved battle shot" on my warrior wich make the battle shot buff from 193 to 231. (something liek this)
When pass the mouse on the buff icone, it's says "attack power increased by 193".
The talent works because when i check on my character infos, i see that my attack power is increased by 231 (more or less)

**Comment by Holyfrogg** [comment]
This is blizzlike. Bonuses from talents never showed on buff tooltips in vanilla.

**Comment by Mynnaa** [comment]
ok thx, sorry to bother you

Le mar. 26 févr. 2019 à 16:58, Holyfrogg <notifications@github.com> a
écrit :
