### ISSUE TITLE
Can't Log into Northdale Realm

### ISSUE THREAD

**Issue by ghost** [LightsHope/issues#1240]
First of all, thank you for taking the time to report this issue.

Hello, 

i'm playing light hope for some months. I had to format my win10 and re-install the wow 1.12. I did nothing different from the last time i installed it. Well, i logged in normaly, played for a couple of minutes and went AFK for less than 5min. When i got back to the computer i was DC. So, I tried to log in again and i couldn't connect to Northdale Realm, it does not upload my characters and get back to the realm list. I tried lightbringer and it worked fine. I already re-installed it, restart PC, flushdns and, as crazy as it appears to be, sometimes i could log in and sometimes not. I've made a quick video to show you. 

*SORRY for the loud music, i was dumb enough to not turn it off while recording*
https://www.youtube.com/watch?v=1mOv3Km8k9g&feature=youtu.be

Thank you for your time.

**Comment by Nimbix-wow** [comment]
https://imgur.com/a/tiJugXM

A russian shitkid has held the server hostage in the last 36hours and demanding 500$.

Link above is communication from said shitkid.

Admin message about incident: https://status.lightshope.org/

**Comment by ghost** [comment]
I saw the server online and thought it would be a local problem. Thank you man.
