### ISSUE TITLE
WSG - past victories/past efforts in Warsong Gulch - item not found

### ISSUE THREAD

**Issue by khthnoios** [LightsHope/issues#1241]
HI,

Having issues trying to turn in the quest for Past Victories/Past Efforts in Warsong Gultch in SW
Each time I try to turn them in, the error msg appears saying item not found. Its clearly in my bag but i am unable to turn them in. 

I have deleted my WDB file and restarted my game, however it doesnt seem to work.

Please advise.

Thank you

**Comment by bladezLH** [comment]
There are multiple quests. You need to complete the one relevant for the current marks of honour.
