### ISSUE TITLE
Letherworking Bug 

### ISSUE THREAD

**Issue by huntmenow** [LightsHope/issues#1242]
found this  and i got the sameproblem Right now, 

Unlearned-Relearning Leatherworking Profession Bug #370
 Closed	AirJoker opened this issue on 28 May 2018 · 3 comments

**Comment by Gamemechanicwow** [comment]
But that guy was talking to the wrong trainer? There is different trainers for apprentice and journeyman skills.

Journeyman trainers:
https://vanillawowdb.com/?spell=2154

Apprentice trainers:
https://vanillawowdb.com/?spell=2155
