### ISSUE TITLE
Rogue q bug

### ISSUE THREAD

**Issue by enlil1234** [LightsHope/issues#1260]
I doing rogue poison q , and i done everything , excecp pick pocket key from q's mob , i kill them without PP , then open box and got poisoned for 7 days without key , so i cant finish q without key , and cant cure from poison coz cant finish q , i abbandon q , posion stays , but q g disaperety trainer cant give me new q's...cant take q again...pls help me :D thanks

**Comment by Gamemechanicwow** [comment]
You already did the first part, thats why the trainer won't give you the quest again.

You need to pickup the followup quest, which is given by Agent Kearnen.

**Comment by enlil1234** [comment]
No i know i whistle alredy to tim and take his q's then fail then drop whistle and flare, and he start to be unfriendly , but i solve that , was w8 another rogue to come on this part of and he whistle, flare , anyway thanks
