### ISSUE TITLE
please give amnesty for my account

### ISSUE THREAD

**Issue by 13rutus** [LightsHope/issues#1264]
Have ban account "WOWFRESH" 8 months ago - "You bought about 60g from a gold seller. This is against the rules. Which you knew already, and thus this account is banned and appeal denied."
but is not true, nevertheless ... 8 months ago, please give me account back for game :)

**Comment by Gamemechanicwow** [comment]
Not related to server development.

**Comment by dimadze1337** [comment]
Haha lol idiot!
