### ISSUE TITLE
Anachronos quest bug

### ISSUE THREAD

**Issue by arthashan** [LightsHope/issues#1265]
Unable to submit "The Path of the Conqueror" quest to Anachronos in order to get my ring "Signet ring of the bronze dragonflight". I can still attack dragon after I reach reputation of "Friendly" with Brood of Nozdormu. Please help! Thank you

**Comment by Gamemechanicwow** [comment]
untick "at war" in your reputation pane..

**Comment by morfisia** [comment]
C = control panel character
Reputation
scroll on Brood of Nozdormu  and click up reputation, it open a little window on right
Untag at War
