### ISSUE TITLE
Black Dragon Mail set bonus

### ISSUE THREAD

**Issue by stephenmilea** [LightsHope/issues#1267]
I have crafted Black Dragonscale Shoulders and Black Dragonscale Breastplate, but do not receive a set bonus. I do not see any text below the item description relating to a set bonus in-game, but it seems to be present on this website:

https://vanillawowdb.com/?itemset=489

Additionally, the set bonus states that 2 pieces "improves your chance to hit by 1%," but I do not see any change to my attack rating when I equip them.

**Comment by blackdragonscalesetbonus** [comment]
I have crafted Black Dragonscale Shoulders and Black Dragonscale Breastplate, but do not receive a set bonus.  I do not see any text below the item description relating to a set bonus in-game, but it seems to be present on this website:

https://vanillawowdb.com/?itemset=489

Additionally, the set bonus states that 2 pieces "improves your chance to hit by 1%," but I do not see any change to my attack rating when I equip them.

**Comment by Gamemechanicwow** [comment]
Before patch 1.8 the set was not a set, but seperate items. If your client still have the old data cached, you need to delete your wdb folder. This is recommended to do after each server update or after playing on a different server.

Even if your client doesn't show the correct data, it will still give the benefits serverside.

+hit is not shown on your attack rating.

**Comment by stephenmilea** [comment]
Thank you for the quick reply.  I have deleted my WDB folder and the set bonus is now visible for me on each item.  

Thanks again!
