### ISSUE TITLE
Character keeps crashing WoW every time I try to log in.

### ISSUE THREAD

**Issue by RandomizerNOR** [LightsHope/issues#1281]
April 7, 2019
Patch 1.12.1 
Northdale

Hello, my newly made Tauren Druid named Norskku randomly got an error when I was done picking up quests in Bloodhoof village. 

Screenshot below
This instantly pops up every time I try to restart the game and log in to this specific character, and im forced to exit the game. I can log in to other characters perfectly fine, but there's something wrong with this character. 

![b97e65481477968c1b5856193940d6ca](https://user-images.githubusercontent.com/49366161/55683705-fc78ce80-5942-11e9-8b93-5685c68e7c76.jpg)

**Comment by Shivsproket** [comment]
You need to make a ticket in-game on another character to have a GM move you somewhere else, if you want to recover your character.

Are you perhaps playing on an Apple OS?
Else I'd try reinstalling or downloading a new version somewhere else and install that.

**Comment by bladezLH** [comment]
Mac-related issue, create a ticket on a new character.
