### ISSUE TITLE
Luck be with you

### ISSUE THREAD

**Issue by Xengard** [LightsHope/issues#1282]
Trying to do that quest, but you can't get frostmaul shards. GIants don't drop them, and you can't interact with the cristals.

**Comment by Gamemechanicwow** [comment]
If you haven't already found a solution to this, i would recommend closing wow and deleting your wdb folder. Crystals should be interactable.

**Comment by Xengard** [comment]
OK, my bad... Apparently you can't loot from the giants or the cristals when in a raid group... Sorry about that.
