### ISSUE TITLE
Can't complete Ashenvale quest Warsong Supplies from Locke Okarr

### ISSUE THREAD

**Issue by Da1337DoOD** [LightsHope/issues#1283]
I completed the Horde quest Warsong Supplies that starts and ends with the NPC Locke Okarr in Ashenvale, but the NPC has a grey question mark.

I have all 4 quest items in my bag but cant complete the quest! And if I try to abandon it will remove the quest items which were pretty time consuming to get.

Screenshots of the quest items, quest log and NPC log:

https://imgur.com/a/EwqR8T1

**Comment by Gamemechanicwow** [comment]
>  it will remove the quest items

Nope.

https://lightshope.org/faqs/faq-completed-quest-cant-turn-in
