### ISSUE TITLE
Suject closed

### ISSUE THREAD

**Issue by Dreamersclaw** [LightsHope/issues#1288]
Subject closed--ending with meme
![ofikg](https://user-images.githubusercontent.com/48614233/56170755-5b27f300-5fa8-11e9-9936-cb5504fee55b.jpg)

**Comment by Gamemechanicwow** [comment]
> Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development.

> I know theres a tab to reverse a banned decision and I'm not downloading that app because I don't trust it

Its basic software thats provided by several renowned publishers (ex. google), you can even download the opensource code and compile it yourself if you are that paranoid.

**Comment by Gamemechanicwow** [comment]
Btw... Why the fuck is your GF paying for you? Grow some balls.

**Comment by Dreamersclaw** [comment]
I give her the money to pay for me, easier than paying separate accounts, go fuck yourself sjw

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Dreamersclaw** [comment]
I also said it like that to see who the other cunt was giving people negative damage debuffs, w/e

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Gamemechanicwow** [comment]
Not relevant for the server development. Please close this "bugreport".

**Comment by Gamemechanicwow** [comment]
Just gonna repost the deleted content in this thread for reference :>

> Hi, My account has been banned because I made tickets about my characters being deleted and the one GM Theodris is the only one answering them. I log back into the game and I have a ticket already made about my characters being deleted. Now it is banned for "Character Restoration Abuse" and "insulting a GM".
> 
> Also I made tickets prior to my characters being deleted about a GM debuff on my character reducing my damage and items not working properly. I know theres a tab to reverse a banned decision and I'm not downloading that app because I don't trust it. Can anyone other GM help(NOT THEDRIS) because this is ridiculous. I've had a level 43 warlock Dreamersclaw on Lightshopes this happned to and my 48 hunter Dreamerclaw. Also a number of guilds were disbanded when I was logged off.
> I know its not a hacker because I log back in sometimes and my gold and gear are still there. When I asked to talk to another GM Theodris always ignored me. The damage reduction tickets were labeled in the report a ticket section under character and one of the ways a GM could help is stats not adding up.
> 
> My gf donates 30$ a months for us to help this server team out and idk what the F to do anymore.

> I give her the money to pay for me, easier than paying separate accounts, go fuck yourself sjw

> I also said it like that to see who the other cunt was giving people negative damage debuffs, w/e

**Comment by Dreamersclaw** [comment]
Please fucking tell me about the damage reduction GM debuffs you were using. Seriously, you don't think I looked at the data my comp was getting from your servers. The broken weapons and auto crits against my character in pvp. You lil buddy buddy brobeertacosONtuesdays need to get your SJW azzes off a game intended for military training and go lift something other than a Cuntster energy drink.

**Comment by Gamemechanicwow** [comment]
> Seriously, you don't think I looked at the data my comp was getting from your servers.

I dont think you have any clue about what data is transmitted. Honestly i dont think you have any clue about anything. Just fuck off :>
