### ISSUE TITLE
[Rogue] Talent improved eviscerate tooltip

### ISSUE THREAD

**Issue by Staint84** [LightsHope/issues#1289]
i putt 3 points in the above talent and the tooltip for the ability does not change, to represent the new dmg numbers. Is this talent actually working?

**Comment by Gamemechanicwow** [comment]
Its a limitation of the vanilla wow client. Tooltips are static.

**Comment by Staint84** [comment]
but the talent is working fine?

**Comment by bladezLH** [comment]
Tooltips are not dynamically updated in Vanilla.
