### ISSUE TITLE
Method of averaging 120 g/h per person

### ISSUE THREAD

**Issue by 19966bb** [LightsHope/issues#1290]
Now, hunters can easily get Gordok Tribute.
The whole process is within 12 minutes.
Will this always be allowed?
Should they not be restricted?
I need to know your work email. I'll send you a video to prove everything I say.

There is another problem.
Why King Gordok's transfer skills don't work for hunters'pets?

More Chinese are earning more gold coins in this way.
Average 120 G/h per person

**Comment by 19966bb** [comment]
King Gordok will pull the first target beside him.
But when his first goal was to hunt pets, he couldn't do that.

**Comment by bladezLH** [comment]
We'll not be making any changes to DMT.
