### ISSUE TITLE
Correct formula for spirit-based mana regen for druids casters

### ISSUE THREAD

**Issue by Gamelander** [LightsHope/issues#1291]
Mana regen formula for druids is wrong on this server!
As we know, correct spirit-based mana regen formula for druids-casters is: MP2=Spirit/4.5 + 15
Now we have feral formula worked for all druids: MP2=Spirit/5 + 15
Most druids on this realms is casters (healers), so /4.5  formula must work correct for them.
https://wowwiki.fandom.com/wiki/Talk:Spirit

**Comment by Gamemechanicwow** [comment]
Just tested this on my druid, with no talentpoints set. My mana regen ticks is exactly MP2=Spirit/4.5 + 15

I am not sure how you get a different value?

**Comment by Gamelander** [comment]
MP2=Spirit/5 + 15 is absolutly correct now
For example:
![image](https://user-images.githubusercontent.com/22045958/56425707-1e1c7300-62be-11e9-8153-88ecc8249756.png)
Excel:
![image](https://user-images.githubusercontent.com/22045958/56425805-80757380-62be-11e9-80bd-176440f519b9.png)
And with formula:
![image](https://user-images.githubusercontent.com/22045958/56425774-60de4b00-62be-11e9-82b8-3c469f12c337.png)

**Comment by Gamemechanicwow** [comment]
I guess thats the BetterCharacterStats addon? Since mana regen is not shown in client without addons.

I have taken the time, to look at the sourcecode for that addon. And it doesn't get the information from the server, since the GetManaRegen() wasn't available in the WOW API until way later.

The mana regen calculated and shown on your character tab is done clientside.

https://github.com/yutsuku/BetterCharacterStats/blob/master/helper.lua#L919

```
	if class == "DRUID" then
		addvalue = (Spirit / 5 + 15)
```

**Comment by Gamelander** [comment]
Addon Theorycraft show the same. It calculated same as BetterCharacterStats ?

**Comment by Gamelander** [comment]
Okay, i check it manually, twice! Take no mp5 gear, low my mana and take time untill it full.
Formula is still  MP2=Spirit/5 + 15, not /4.5

**Comment by bladezLH** [comment]
We don't know the 'correct' formula is `SPI/4.5 + 15` at all. Both TC and BCS are calculating it at `SPI/5+15`, and the wiki page you link has `SPI/5+15` in the history for Vanilla (https://wowwiki.fandom.com/wiki/Spirit?oldid=140471).

I have no idea where the table showing 4.5 is coming from. For reference, we calculate it using 5.
