### ISSUE TITLE
Winterspring problem

### ISSUE THREAD

**Issue by fixbugplease** [LightsHope/issues#1293]
Hello my in game name is Pepeo and i am farming frostsaber reputation and i noticed that quest item is not droping at all its shardtooth meat and chillwind meat from cimeras nad bears in Winterspring on north ..i chekd it says the drop rate of meat is 30% and its not droping at all.....like 2days..... no single meat and i psend like 8 h of farming and runuing so please send me in game message as GM and explain me or send me some kinda of message for answer i whis u best of luck and ull call me soon take care :)...

**Comment by Gamemechanicwow** [comment]
> Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster.

**Comment by fixbugplease** [comment]
Dude game master told me to contact you so I guess it's dead end here.....

**Comment by Gamemechanicwow** [comment]
![image](https://user-images.githubusercontent.com/2223066/56542550-18998400-656f-11e9-85ab-325cbdf338de.png)

**Comment by Gamemechanicwow** [comment]
Not a server issue. Make sure you aren't in a raid. Try deleting your wdb folder, abandoning and retake quest.

**Comment by fixbugplease** [comment]
Ok..thank you for your time
