### ISSUE TITLE
Ansekhwa from Thunder Bluff doesn't teach how to use maces

### ISSUE THREAD

**Issue by mirkwoodenstick** [LightsHope/issues#1315]
Other weapon masters say that you can learn this skill from Ansekhwa, but he only offers guns and staves training. 
![IMG_20190511_140418](https://user-images.githubusercontent.com/50524868/57572282-aeaf2480-7420-11e9-8fc9-cf56eb75eb30.jpg)

**Comment by Gamemechanicwow** [comment]
Hunters cant learn/use maces.

**Comment by dimadze1337** [comment]
LMAO dude are you really. Hunters can't use maces. Also your screenshot is the darwin winner.

**Comment by mirkwoodenstick** [comment]
thanks guys, didn't know that
was just confused by the amount of weapons hunters can use in vanilla

yup that's the only thing I can ever win
