### ISSUE TITLE
This servers script is fucking awful why do people play on this server

### ISSUE THREAD

**Issue by rasmus47** [LightsHope/issues#1345]
Hey boys why people play on this trash fucking server where rogues can frontstab u aggro the whole instance randomly and pets fucking runaway for no reason? if you consider playing this server you might aswell hang yourself

**Comment by QAkvastskaft** [comment]
![asdf](http://www.quickmeme.com/img/2d/2d41f72deede37abb978d0399f67fcc97b46c1217fb976a652f3f9233b9fdd68.jpg)
