### ISSUE TITLE
Can't /s, whisper or talk in general. 

### ISSUE THREAD

**Issue by victorsaad00** [LightsHope/issues#1372]
Hello i recently created a character in silver hand server. Even after lvl 15 i can't talk, whisper or talk in general saying i'm too low lvl. I can invite ppl to party and talk in party chat or guild chat. I've seen a lot of ppl with the same problem.

edit1: Deleted the issue msg.
edit2: I've tried to delete all logs and WTF, WTB files on WoW folder but nothing worked.

**Comment by dimadze1337** [comment]
lvlup

**Comment by victorsaad00** [comment]
"Even after lvl 15"

I already check and ... it's not this. https://lightshope.org/faqs/faq-mutes
