### ISSUE TITLE
Gothik the harvester glides across the room and through the doors instead of teleporting (anathema / darrowshire)

### ISSUE THREAD

**Issue by niknikk** [LightsHope/issues#148]
As the title says, during Gothik encounter in Naxxramas, on Anathema, boss himself is not behaving as he is supposed to.
What he does is slowly gliding from living area to the dead one, literally passing through the closed doors.

Here is the clip of his current behavior: https://clips.twitch.tv/FurtiveSquareArugulaLitFam
Sometimes you can even have him get stuck in the doors so both sides can dps him, or have him not even go through, having dead side literally standing afk until living side team kills him.

Blizzlike behavior is him actually teleporting to the other side (i am unsure if that should happen after some time period or when certain % of his health is lost however). 
here are clips from retail vanilla naxxramas gothik encounters. in every one of them Gothik teleports, and never glides through the wall like he does on Anathema:
https://www.youtube.com/watch?v=Pa-Q0I3mcn0
https://www.youtube.com/watch?v=FN2QtHx8_xw
https://www.youtube.com/watch?v=K4j-5dSv414
https://www.youtube.com/watch?v=n-dDNBpvL8w
https://www.youtube.com/watch?v=9gx49pIQ4Ao
https://www.youtube.com/watch?v=GDTO27x-f3U

Also, doors behave rather strange - sometimes he dies before they open, and sometimes they open sooner. Retail videos suggest they are supposed to stay closed for a while. Can someone explain how does that actually work?

**Comment by towneh** [comment]
Confirmed that this happened to us on our Gothik kill on Darrowshire last Sunday. He glided through the doors on the last teleport before the doors opened.

**Comment by thepparker** [comment]
He does 'teleport', however the animation sometimes doesn't display correctly.

**Comment by niknikk** [comment]
even when he does, it looks like it did tonight
clip: https://clips.twitch.tv/ArtsyAlertMonkeyBibleThump

**Comment by towneh** [comment]
Tonight he displayed a slightly different issue. He teleports, retains aggro from the previous room and then appears to bounce off the door. At which point he then targets the highest on threat within the room he's occupying as should be correct, this boss scripting definitely needs to be reviewed.

Clip from twitch of my above example:
https://clips.twitch.tv/SecretiveBlushingAlpacaEagleEye

**Comment by niknikk** [comment]
please fix, this is ridiculous

https://clips.twitch.tv/QuaintCovertCatPeoplesChamp
