### ISSUE TITLE
[Lightforge Legplates] Not dropping from Stratholme.

### ISSUE THREAD

**Issue by svepi123** [LightsHope/issues#154]
I've done 32 consecutive runs on my character Sveh on Lightbringer realm.
So far I haven't seen them drop a single time! According to Atlas recourse the drop is estimated to be 4.20%-5.17% depending on the version or source of loot table you use.

Simple math shows a 134.4%-165.44% chance to have seen atleast one pair drop. I haven't seen one pair drop. I've seen them on other paladins but they've optained them before patch 1.10.0. Would be nice if you check the loot table if the item is actualy existing, because this is starting to look ridicilous. If such bug is found or something of that sort I would love to get them as a reward for pointing this out and my frustration. 

Keep in mind that I've seen MULTIPLE drops from the other set pieces. From 2x-4/5x other set pieces drops.

**Comment by fgsfdss** [comment]
http://realmplayers.com/ItemUsageInfo.aspx?realm=LB&item=16728&page=7

Close this.
