### ISSUE TITLE
Mobs fighting in middle of alterac shouldnt exist there

### ISSUE THREAD

**Issue by ImperfectCell** [LightsHope/issues#157]
https://www.youtube.com/watch?v=aifkCbAw3wc&t=4m38s

Mobs fighting in middle of alterac shouldnt exist there

http://www.warcraftrealms.com/charsheet/20257204
You can see he exists in Eye for Eye throughout the months and in his video there were no mobs in the middle of AV.

Please remove them its non blizzlike

**Comment by GuybrushGit** [comment]
AV is intentionally kept in its pre nerf state.
