### ISSUE TITLE
Experience from quests compared to 2004-2006 sources

### ISSUE THREAD

**Issue by crackyoo** [LightsHope/issues#159]
A ton of quests on Light's Hope grant too much experience.
The two quests are level 47, the players are 46 and 50 respectively, therefore they both gain full experience.
https://www.youtube.com/watch?v=P3csn5f5pOc&t=646s VarrakWoW, 6000exp per quest
https://www.youtube.com/watch?v=gN3Z2vVNQAE&t=1148s Joana, 4200exp per quest

Old allakhazam links:
https://web.archive.org/web/20050224001347/http://wow.allakhazam.com:80/db/quest.html?wquest=5535
https://web.archive.org/web/20050220000532/http://wow.allakhazam.com:80/db/quest.html?wquest=5536

http://www.wowhead.com/quest=5535/spiritual-unrest
In the comments it says 6050 exp as of patch 2.3, also from my own experience when leveling all quests seem to have 2.3 exp values or close to it, this means practially every quest starting at level 30 is affected by this.

I feel like fixing this issue will be a massive undertaking, but Kronos was able to implement this into their Kronos 3 release and I would love to see this fixed for the upcoming new Light's Hope server.
If possible I would be willing to spend a lot of time helping to fix this issue asap, I need a private server where I can practice leveling with authenticity.

**Comment by Niceguyone** [comment]
I think most of this xp problem is already being addressed with https://github.com/lh-server/core/pull/22

**Comment by crackyoo** [comment]
AWESOME BROS KKTHXBYE

**Comment by thepparker** [comment]
Will be utilized on the new server, Northdale.
