### ISSUE TITLE
Deshift (Druid addon issue)

### ISSUE THREAD

**Issue by pandasd** [LightsHope/issues#16]
Is there something wrong with spell/buff "shapeshift" for druids on anathema? I've got errors constantly when using addon deshift, and it's fine working on LB on my 24 lvl druid.
![wowscrnshot_021918_203022](https://user-images.githubusercontent.com/6220185/36390438-1ae1ba72-15b4-11e8-9cb5-2c82204070af.jpg)

**Comment by Road-block** [comment]
This is 100% an addon error and not a server error.  
There is no `Shapeshift` method in the client API.  
You most likely have a different set of addons enabled and one of them is providing the function.

**Comment by pandasd** [comment]
Alright, gonna check it later without any other addons!

**Comment by GuybrushGit** [comment]
Try downloading a 1.12.1 version of this addon.

**Comment by pandasd** [comment]
Okay!
