### ISSUE TITLE
Dry Times - Quest (Item not at vendor)

### ISSUE THREAD

**Issue by warlockdudes** [LightsHope/issues#162]
In the quest "Dry Times" the player is suppose to buy 4 different items from 4 different vendors. 
However the "Skin of Sweet Rum" cannot be bought in Goldshire from the Bartender. It is not there.

Thank you!

**Comment by ratkosrb** [comment]
It is there...
![wowscrnshot_032618_171815](https://user-images.githubusercontent.com/35845488/37911865-b26e80fc-3100-11e8-90ec-3a9c8621d31a.jpg)
