### ISSUE TITLE
Jadefire Trickster - Curse of Weakness causes 0 damage for duration

### ISSUE THREAD

**Issue by Gutfux** [LightsHope/issues#169]
On realm Lightbringer realm patch 1.10 when using Heatseeking Crossbow as a hunter, if Jadefire Trickster applies the spell Cure of Weakness to my character I would then deal no damage for the duration of the debuff, rather than reduced damage. Tested this on mulitple mobs, relogged, etc and issue still persists.

**Comment by Cabro** [comment]
So the Curse of Weakness causes YOU to do 0 damage.

**Comment by Gutfux** [comment]
Yes, pet does damage but I do none and nothing comes up in the combat log for my attacks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tunesisback** [comment]
this issue should not be closed, people in general chat in felwood are complaining about this, on northdale, patch 1.2

**Comment by brotalnia** [comment]
I have had people report this issue to me too.

**Comment by pentagoth** [comment]
Here is the bug in action
https://www.youtube.com/watch?v=5nAZuRaeK8I

**Comment by brotalnia** [comment]
Should be fixed by https://github.com/lh-server/core/pull/161
