### ISSUE TITLE
Deathknight Understudy Requires Toggle Walk on Initial Mind Control

### ISSUE THREAD

**Issue by towneh** [LightsHope/issues#174]
When mind controlling the first Deathknight Understudy on the Razuvious encounter, the NPC defaults to walk. In order to work around this issue you need to immediately press the toggle walk keybind to get the NPC to run, which helps massively when positioning in the first few seconds of the fight. This issue does not appear to persist beyond the initial pull, and not seen on subsequent mind controls of the other Deathknight Understudy NPCs during the encounter.

**Comment by GuybrushGit** [comment]
Happens with every NPC not just this one.
