### ISSUE TITLE
You don't see buffs of players in your raid/group when they are out of visible range.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#175]
Sometimes you see SOME buffs, but most of the time you don't see ANY. This is superbugged.
Rogues going in stealth bugs all buff checking addons.
Proof: https://www.youtube.com/watch?v=SAaAoyCGdwk

**Comment by GuybrushGit** [comment]
Only bug I found was buffs added to someone before they joined the group.

**Comment by Cabro** [comment]
It's more than the above, as i said, if you join a raid, buff your rogues, and they go stealth, you won't see them anymore (which is good), but also their buffs are not listed either (which is the bug).

**Comment by Aklol** [comment]
Can confirm this is a thing. I often don't see raiders in my guild having their DM tribute buffs until they're in range of me, even though the received the buffs in the same raid as me.

**Comment by Cabro** [comment]
Rogue is stealthed in my visible range. The buffs on him are once he got inside and we started buffing.
![wowscrnshot_032918_195900](https://user-images.githubusercontent.com/1155017/38136013-ce0737be-341b-11e8-834d-d288c18c6101.jpg)
I turn around, and he becomes invisible to me, and i don't see any of his buffs anymore.
![wowscrnshot_032918_195903](https://user-images.githubusercontent.com/1155017/38136015-ce37c802-341b-11e8-88cd-9606466086a9.jpg)

**Comment by GuybrushGit** [comment]
Should stealth rogues be visible to the whole raid?

**Comment by Cabro** [comment]
I remember i could see rogues and buff them in TBC on my priest, I'm not sure how it used to be in vanilla.
But the bug remains, rogues in stealth is only a case of this. A lot of times, players in party when out of range of visible sight don't present any buffs.
