### ISSUE TITLE
Wounded mobs should move slightly slower

### ISSUE THREAD

**Issue by Zarant** [LightsHope/issues#178]
Non-boss npcs are supposed to move slightly slower whenever they are below ~10% hp, this should apply to all npcs including elites and 5 man bosses.

Proof:

https://www.youtube.com/watch?v=3LE4VI5fJwE
At 7:30 you can see both mobs running at the same speed, later at 8:13 you can see both mobs again, one of them wounded running slightly slower

https://www.youtube.com/watch?v=3O_pNDc73MM
at 7:00 the mage is barely able to outrun the dragon, at 9:57 you can see that the player is easily able to outrun the npc

https://www.youtube.com/watch?v=NbHkXttoowE 8:17
https://www.youtube.com/watch?v=dXE_RR5XzE8 15:25

This next video you can observe the same behavior and you can notice that this mechanic kicks in when the npc gets to about 10% hp:
https://www.youtube.com/watch?v=fZTIdqj6B5c
12:22
13:22
15:51
17:43

This next clip is from joana's speed run:
https://www.youtube.com/watch?v=SwLjJH8LXfc 19:22

**Comment by GuybrushGit** [comment]
Some other people tested this on retail over here:
https://vanilla-twinhead.twinstar.cz/?issue=3854
https://vanilla-twinhead.twinstar.cz/?issue=2503

Seems like the reduction and health brackets should be 
>15-10% = 70%
>10-5% = 60%
>5-0% = 50%

And it affects every mob type but some specific NPCs can be immune
>Unlike most NPC's in WoW, these do not slow down when @ low Health.
>http://www.wowhead.com/npc=17132/clefthoof-bull#comments

Unsure how it should work in raids, all mobs immune or only bosses?

**Comment by GuybrushGit** [comment]
Also are pets affected?

**Comment by GuybrushGit** [comment]
Kinda hard to see but I think this mob is being reduced: https://youtu.be/R9bwcQiX6RM?t=223
