### ISSUE TITLE
Ironfoe Proc rate and mechanics

### ISSUE THREAD

**Issue by Swindlerbob** [LightsHope/issues#18]
As you can see in both threads listed below. You can see Ironfoe can chain proc off many things and even gain a double proc.

http://wow.allakhazam.com/forum.html?forum=243&mid=1170604263313154325

http://web.archive.org/web/20050517153603/http://thottbot.com/?i=23837

Both showing also the proc % should sit between 8%-6%. So reverting it back to the natural state our server had it on around 6% was correct. 

Also every vanilla server and even Kronos has it around these %'s and information brought against it last were was info from LATE TBC where it was nerfed(along with thunderfury) as it was being used by guilds in execute phase only late in TBC. 

TBC is not vanilla and that information should be discredited and be reverted back to the original state. 

reference: Warlords of Draenor Patch 6.0.2 (2014-10-14):
Stats squished.
Now only triggers 1 extra attack on proc, down from 2.
No longer allows its wielder to temporarily speak Dwarven. 
Prior to the item squish in Warlords of Draenor, Ironfoe's proc was "Fury of Forgewright", which granted 2 extra attacks on the next swing and caused the wielder to speak Dwarven for 10 seconds. This was effective for Alliance and Horde characters alike, and it allowed a Horde wielder to communicate with nearby Alliance dwarves through /say and /yell.
Cataclysm Patch 4.0.3a (2010-11-23):
Item level reduced from 60 to 56.
Speed reduced from 2.40 to 2.50. 
The Burning Crusade Patch 2.4.2 (2008-05-13): Converted from Main Hand to One-Hand.

**Comment by Pre-Elysium** [comment]
Unfortunately I don't see anything here that credits a 6-8% proc rate. There's one comment in that old thottbot which says "Unless otherwise specified, all proc rates default to 5%" Which would mean it should be 5%, but can that 5% default proc rate be confirmed?

**Comment by Gagarinbest** [comment]
I can confirm that on WoW Classic (Anniversary server) I had 8 melee hits in a row from 1 normal hit. I think, it was like 1 normal hit + 3 Ironfoe procs + 1 HoJ proc. I equipped with Ironfoe and Hand of Justice.

![Image](https://github.com/user-attachments/assets/5f086f9b-6aa3-497a-a7be-fefb04f90feb)
![Image](https://github.com/user-attachments/assets/e01498e1-3d61-4d5c-ab14-4e0bd04a25c1)
