### ISSUE TITLE
AV queueing system broken

### ISSUE THREAD

**Issue by turetafr** [LightsHope/issues#181]
Why there was no game of Alterac Valley allowed in between AV weekends? Prior to the past AV weekend, there was always a game open with level 51-59 people in it, farming and leveling up. Something changed after the last AV weekend ended around March 12.  I know a lot of people who tried getting in after that and could not. Now it is AV weekend and there are people in it, but there should still be people after AV weekend is over. Please check on what is the minimum to enter the BG - it should be 20, not 40. Even 20 is too much for between weekends because of the low amount of honor you allow for the BG, even games that take days.   It is just unblizlike to refuse people to enter Alterac Valley between BG weekends.  The AV queue system also is broken in a way that prevents people from entering the BG unless the teams are even. This is wrong. The reason is because, in a game where people don't rush the boss -- if the game takes longer than 15 minutes some people inevitably leave due to time restraints or due to frustration. The problem with this is that if the BG was not full to begin with, people will not be allowed to enter the BG until the teams even out, which is almost impossible to happen on non-AV weekend if a bunch of people decide to leave at once. This winds up in games that are 1v0 because of the broken queue system.  40v40 queue system should not work identical to 10 or 15 man BGs. It's a completely different type of battleground.  If there is not 40 people on your team, and someone is queued to AV, they should be allowed in no matter what.

**Comment by GuybrushGit** [comment]
Min players is set to 20.

**Comment by turetafr** [comment]
Did you read the second part of this. There is also an issue with people not being able to get into an AV that is not full.

**Comment by turetafr** [comment]
Please answer, why does Alterac Valley not work outside of AV weekend anymore?  AB works on WSG weekend, and WSG works on AB weekend. Why isn't AV working?

**Comment by turetafr** [comment]
It is literally 1 day before AV weekend, and you're telling me there aren't enough people queued to start a game? I call shenanigans. Please investigate this. The end user has no way to determine what is wrong with the server.
