### ISSUE TITLE
Frostwolf is Friendly in AV

### ISSUE THREAD

**Issue by spachib** [LightsHope/issues#188]
The frostwolves on Horde side are friendly in AV, this is a recent change and I believe they should be killable. I noticed they are part of the Frostwolf Clan faction, maybe that's related. This is a serious bug because this also seems to break the quest "Empty the Stables". The frostwolf muzzle item channel is instantly cancelled when used on the Frostwolves and without completing that quest no riders can be summoned. 

Thank you for your time, Spachib

**Comment by turetafr** [comment]
I concur with this report. And it has something to do with the report I made about not being able to heal friendly NPCS.

**Comment by spachib** [comment]
quick fix! thanks Guy
