### ISSUE TITLE
Raw Nightfin Snapper Droprate

### ISSUE THREAD

**Issue by Dualnames1** [LightsHope/issues#190]
To whom it may concern, I tested something yesterday, on Anathema, not sure if it;s the case with LB, probably is. So regarding the [NIGHTFIN SOUP], the droprates are bugged. Explaining. During certain times you're supposed to get either Sunscale Salmon or Raw Nightfin Snapper. From 12:00 pm to 18:00 pm you're supposed to get only Sunscale Salmon, which works fine, the drop rate is always around 18% or 15%, I think it's 18% and that's fine. The closer you get to the night, the 18% divides into two droprates, one for Sunscale Salmon, the other for Raw Nightfin Snapper, till midnight, increasing the drop rate for Raw Nightfin Snapper, so going from 0% to 9% and Sunscale going from 18% to 9%. However after midnight, you're not supposed to get any Sunscale, which works, but in a weird way. Instead of the Percentages going to 18% Raw Nightin Snapper and 0% Sunscale Salmon, they go 9% Raw Nightfin Snapper 0% Sunscale Salmon. Instead of fishing Raw Nightfin Snapper where the Sunscale would drop, instead you get an empty loot. That means that the droprate of Raw Nightfin Snappers varies from 0-9% throughout the course of the day, whilst Sunscale Salmon varies from 0% to 18%. Instead they both should be 0% to 18% depending on time. Can this please get addressed I'm pretty sure it's there for all the servers, Darrowshire included.

Even if the percentages are wrong, they vary in private servers, from 15-25, the issue is still there, Raw Nightfin Snapper gets replaced properly by Sunscale Salmon, Sunscale Salmon is replaced by no drop, thus making the droprate abysmal and definitely not according to blizz-like behavior. Fix?

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/issues/issues/90

**Comment by Dualnames1** [comment]
It's not fixed, you can check it easily.
