### ISSUE TITLE
Tactical Task Briefing issues

### ISSUE THREAD

**Issue by kakkakk** [LightsHope/issues#195]
_The server or game patch that your issue pertains to:_
Lightbringer current patch... 1.12.1?

_Expected Behavior_
This concerns the envelopes received from the repeatable quest "Field Duty" (https://classicdb.ch/?quest=8731) in Silithus. I select the "Tactical Assignment" envelope, and open it. These envelopes are supposed to contain one of "Tactical Task Briefing I" through 10, randomly. 

_What's Actually Happening_
Instead of 1 through 10 randomly, the only envelopes only ever contain one of I, III, VI, VII, or IX. I have completed this quest DOZENS of times trying to get "Tactical Assignment Briefing V" since this is the only one of these quests from which "Mark of Cenarius" (https://classicdb.ch/?item=21508) can be obtained, a requirement for "Champion's Battlegear" (https://classicdb.ch/?quest=8573).

_Additional Information which may or may not be relavent_
The expected behavior was working just fine up until recently. I actually obtained all 20 "Cenarion Tactical Badge" required for "Champion's Battlegear" (https://classicdb.ch/?quest=8573) and each Briefing seemed sufficiently randomized at the time. I even had "Tactical Combat Briefing V" and completed the subsequent "Four Dukes" (http://classicdb.ch/?quest=8538) quest it opened in order to obtain "Mark of Cenarius". Before turning in, however, I accidentally deleted the Briefing which is required for quest completion. It wasn't until I began trying to re-obtain this required "Tactical Task Briefing V" that I began to see the strange pattern of only I, III, VI, VII, and IX being contained in the "Tactical Assignment" envelopes. 

I have spent hours upon hours of repeatedly turning in this quest only to have those 5 options appear over and over again. There is definitely something up with this! I have twice asked GMs to restore the deleted item and was twice refused. So I'm submitting this bug report with hopes for a solution. This is the first bug report I've ever submitted so please ask if I can clarify anything. Thanks for reading!

**Comment by xniko** [comment]
Tactical Combat Briefing V can only be received from the follow up tactical assignments, not the initial field duty one.

**Comment by kakkakk** [comment]
Well, that solves it. Thank you very much.
