### ISSUE TITLE
Free the Gorishi Grub

### ISSUE THREAD

**Issue by Regunes** [LightsHope/issues#199]
Greetings Developper of The LH project.
Lately, I wanted to fill the last pet slot with something ... Exotic. And when I randomly came across this video on youtube  (https://www.youtube.com/watch?v=7RBhciA_S1M), I thought this one would do great.
But then I remimbered that the Gorishi egg (mentionned in the video) isn't working (I noticed this from my 3 1-60 leveling). **It is flaged as a common mob and die almost instantly upon fight, while it is supposed to be a summoned minions from Clutchmother Zavas wich after some delay, summon a Gorishi Grub, a pet that could be tamed** up until MOP(or maybe cataclysm but that's not the point). 
For further sources, here are commentary from the Classic DB website (https://classicdb.ch/?npc=6582#comments)
So here you go, hopefully my demand will be fullfilled.

**Comment by GuybrushGit** [comment]
Only tameable on 5.1

**Comment by Regunes** [comment]
Yeah sorry, after further research it seems that it cannot be tamed on classic. But still, the egg is still bugged
