### ISSUE TITLE
Impersonation of a GM

### ISSUE THREAD

**Issue by habsgab757** [LightsHope/issues#202]
Good evening/morning/day , someone named Dodged in the world chat on Lightbringer messaged me telling me my account has been banned and that I was gonna be disconnected in 30 sec or less for hacking, (speedhacking) it is obviously fake and thought I would report it.  I don't even know how to hack lol as I am pretty much computer dumb. Anyway I have screenshots as well.
![2018-04-05 1](https://user-images.githubusercontent.com/38092836/38346821-e9c18c38-386d-11e8-9130-bfd7f0adae2a.png)
![2018-04-05](https://user-images.githubusercontent.com/38092836/38346822-e9ce59ea-386d-11e8-8183-e767d771dab0.png)
![2018-04-05](https://user-images.githubusercontent.com/38092836/38346828-edcbbf6a-386d-11e8-857e-bfcd9b4ceea0.png)
![2018-04-05 1](https://user-images.githubusercontent.com/38092836/38346829-ee1091bc-386d-11e8-95be-a366c3a17df5.png)

**Comment by Niceguyone** [comment]
Make an in-game GM ticket about this with links to those screenshots. The developers here cannot really help you or ban him.

To make a ticket, check the following guide:
https://forum.lightshope.org/viewtopic.php?f=8&t=491
