### ISSUE TITLE
Suggestion: Add /join world message on login

### ISSUE THREAD

**Issue by spachib** [LightsHope/issues#206]
Hey guys, I got a suggestion to help connect players on lower pop servers like Anathema and Darrow. We could just add a call to /join world in the server greeting message. I think a bunch of lower level players don't know about the channel and might find it useful or entertaining!

Thanks again,
Spa Chib

**Comment by Godmatik** [comment]
This place is for reporting bugs and issues, you should post suggestions like this on the Light's Hope forums.
