### ISSUE TITLE
Felwood Curse of Weakness stopping bow damage

### ISSUE THREAD

**Issue by laseneph** [LightsHope/issues#207]
The Curse of weakness that is cast by multiple mobs in Felwood (Jaednar Cultists, Jadefire Tricksters etc) stops all bow auto attacks from doing damage on my hunter, I continue to use ammo however white damage is no longer displayed nor affects them for the duration of the 2 minute spell.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/issues/issues/169
Still looking for a way to reproduce this in dev.
