### ISSUE TITLE
First aid trainer in theramore bug

### ISSUE THREAD

**Issue by sebsejr** [LightsHope/issues#213]
Hey there,

I think i have noticed a bug, and i reported it in game, and was told to report it here.

The first aid trainer in theramore doesnt offer my character any further training (heavy mageweave bandage for an example), even though i have completed the quest and have first aid at 241. 

Guides and other sources all suggest that heavy mageweave bandages should be learnable at 240 first aid. 

So im not sure whats going on here, thanks

**Comment by Godmatik** [comment]
You need to be a minimum character level to learn this, and that's probably the reason.

**Comment by ratkosrb** [comment]
It currently requires lvl 40 on live servers. It should have been lowered to 35 in patch 1.8 but the change wasn't implemented.

Fixed here https://github.com/lh-server/core/commit/84daaf6dd142a0c41a8cd1ca8ae5f8aebeb69a92
