### ISSUE TITLE
Blizzard + Cone of Cold issue after server maintenance

### ISSUE THREAD

**Issue by Ftyxoxo** [LightsHope/issues#216]
Hey guys! After the server maintenance either cone of cold or blizzard got broken.
If you blizzard and it ticks on mobs and then you do cone of cold, you dont get the slow from CoC. Otherwise if you wait for the blizzard slow to fall off and you do CoC then you will get the slow effect of CoC. Thanks for your attention and hard work!

**Comment by GuybrushGit** [comment]
This was intentionally fixed. You should not be able to stack multiple slow effects, Imp. Blizzard is stronger than CoC so it has priority.
