### ISSUE TITLE
Stranglethorn Fever quest don't work. Only phase one spawns.

### ISSUE THREAD

**Issue by Thaowyr** [LightsHope/issues#223]
Hi, 

Tried to do the Strangethorn Fever quest on Lightbringer today, but it didn't work as it should.
Handed in 10 Gorilla Fang and started the sequence, but only phase one was working. Several other groups had similar issues.

**Comment by GuybrushGit** [comment]
Did you kill all mobs in the first wave? The event is interrupted if some of the mobs despawn.

**Comment by Thaowyr** [comment]
Yes. We killed them all.
