### ISSUE TITLE
[The Den] quest broken

### ISSUE THREAD

**Issue by test1055** [LightsHope/issues#224]
Quest: https://classicdb.ch/?quest=1089

The statue with Claw Key (https://classicdb.ch/?item=5690) not used directly like others. To use it we must right click on Gatekeeper's Key and with "hand" cursor click on statue. Other statues used by simbly right click on them.

Video how it must be: https://youtu.be/ikV1CHshoYU?t=6m24s
Video how it is: https://youtu.be/ikV1CHshoYU?t=1m51s

We tryed to do this quest for 30 minutes and decided its bugged.

=(

**Comment by ratkosrb** [comment]
Fixed here https://github.com/lh-server/core/pull/199
