### ISSUE TITLE
Counterattack! Quest in Barrens is broken.

### ISSUE THREAD

**Issue by hubbazoot** [LightsHope/issues#228]
Hello,

While doing the "Counterattack!" quest, we ran into an issue where only one banner was dropping for an entire group, resulting in having to repeat the quest over and over to get all the pieces for all of our group members. Server version 1.12

Additional notes: Krom'zar's banner places just fine, but even when all the members that killed him were members of the group, only one banner piece would drop per kill. We ended up abandoning the quest due to this behavior.

**Comment by thepparker** [comment]
Working as intended
