### ISSUE TITLE
Onyxia's Fireballs shouldn't trigger confuse (Engulfing Flames).

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#235]
http://wowwiki.wikia.com/wiki/Patch_1.3.0
"Onyxia's fireballs will no longer result in a confuse effect (Engulfing Flames). The impact damage of these fireballs has been slightly increased to compensate for the loss of the damage over time."

**Comment by fgsfdss** [comment]
Boss encounters are all in original pre-nerfed states.

**Comment by Cabro** [comment]
Cthun also?
