### ISSUE TITLE
Unable to enchant Brawler's Boots with Minor Run Speed

### ISSUE THREAD

**Issue by Nighthamster** [LightsHope/issues#239]
Thanks for looking at my ticket. I am trying to enchant item "Brawler's Boots" with Minor Run Speed increase to boots. I'm receiving the error that the item is not a valid target. Obviously, any pair of wearable boots should be a valid target for "Enchant Boots". Please assist. I appreciate your help!
<img width="961" alt="enchant boots1" src="https://user-images.githubusercontent.com/16787588/38932820-4dbe3ee4-42e5-11e8-85b3-93cc5e60e6d1.png">
<img width="934" alt="enchant boots2" src="https://user-images.githubusercontent.com/16787588/38932821-4dd10d62-42e5-11e8-9592-52c2849ace59.png">

**Comment by thepparker** [comment]
The starting items are actually not valid targets for enchants
