### ISSUE TITLE
Hunter Pet: ZG Bloodseeker Bat does not attack on command

### ISSUE THREAD

**Issue by manbat2016** [LightsHope/issues#240]
Light's Hope, Patch 1.10

The Bloodseeker Bat, acquired from Zul 'Gurub, does not respond when prompted to attack. If you press the attack command on the pet toolbar or use the shortcut "ctrl 1", the bat focuses the target but does not move or attack it.
With the pet on follow, if you command it to attack, it will stop and focus the target. It will not attack the target though.

**Comment by Immunelike** [comment]
Hello.

As of the 19th of April I have experienced a bug with one of my Hunter pets; a bloodthirsty bat with claws as fast as lightning. The bat will not attack!

When I command her to attack a target, be that a hostile player or npc, she will target the enemy and use her "Dive" ability, but remain stuck in place. I have tried re-summoning, switching her in and out of the stables, re-logging and deleting WDB folder. None has helped.
My other pets behave normally.

As a side note I have also experienced this bug during the Twins fight in AQ40, although only when targetting certain mobs, namely the enraged scorpids. Pets will attack all other creatures during the fight, but not the enraged scorpids.

Perhaps both of these issues can be fixed.

Thanks for the work you do and a great vanilla experience!

Regards, 
Zilpah

**Comment by A11ister** [comment]
Same problem as above, ZG bat I tamed not moving when it attacks. It can follow you, but not attack.. First time I see a real, huge bug on LH.

**Comment by slawry00** [comment]
I have the same issue with the ZG bat just staring at a target as if it is evading.

**Comment by Sabbec** [comment]
I have been have the exact same problem with the same pet. I abandoned it and went and tamed a new one and still had the same problem. The pet actually will attack mobs that come within melee range of it, but it will not move once you issue an attack command. If on follow, it will follow normally and can use "Dive" "Screech" "Growl" etc. still, just not move once you issue an attack command.
