### ISSUE TITLE
 Overlord Wyrmthalak looting 

### ISSUE THREAD

**Issue by Jinsheng-Peng** [LightsHope/issues#245]
I  get the release  branches!
the world database.

https://classicdb.ch/?npc=9568

Less looting things

fix！
INSERT INTO `item_loot_template` VALUES (9568, 13161, 20, 1, 1, 1, 0);
INSERT INTO `item_loot_template` VALUES (9568, 13162, 20, 1, 1, 1, 0);
INSERT INTO `item_loot_template` VALUES (9568, 13163, 20, 1, 1, 1, 0);
INSERT INTO `item_loot_template` VALUES (9568, 16679, 20, 1, 1, 1, 0);
INSERT INTO `item_loot_template` VALUES (9568, 22321, 20, 1, 1, 1, 0);

my world database is 
https://github.com/brotalnia/database/blob/master/world_full_09_november_2017.7z

and the lh_core release sql  migrations。

**Comment by GuybrushGit** [comment]
What?
