### ISSUE TITLE
Hunter Pet (Lighting Breath Ability)

### ISSUE THREAD

**Issue by Playmode** [LightsHope/issues#251]
--

Hello. Hunter ability Lighting Breath rank 6 (from Son of Hakkar) was working as intended. But last week, when I was farming Earth elementals for Ele Earth item, I noticed significaly change. 

- Ability is 20yd Instant with dealing damage (ideal for taging mobs while your pet is aggresive). It worked perfectly.

BUT

- Now, even after restarts, changing pets in stable master, etc - MY PET USE THIS ABILITY ONLY AT MELEE RANGE OR MAXIMALY 5YD (Yes, im sure he had maximum focus and ability was not with low focus or on CD) 
He never again cast it from 20yd, making it melee dash-less pet. Sometimes I think he do it from bigger range then melee, but its like 1 from 10 attempts, but definitely not more then 10yd.

(Shayathel in-game)

**Comment by Seberats** [comment]
Come on... look at other bugs before posting... check #247

**Comment by Playmode** [comment]
Noticed after. Still, there is some reaction that its fixed, while its not. He made a mistake in logs that its some full healing spell, dem lighting breath.
