### ISSUE TITLE
Warlock Imp doesn't Autoattack and doesn't attack if it's ordered to do so.

### ISSUE THREAD

**Issue by nameless-user-64** [LightsHope/issues#252]
Warlocks Imp doesn't autoattack and doesn't attack if it's ordered to do so. I already googled the issue but didn't find a solution for this bug. I also already deactivated and reactivated the abilities and switched thru the attackmondes (passive/defensive/agressive) of the imp. The voidwalker isn't affected by this bug and works normally. I play the charakter "Elonila", a lvl 10 human warlock on the lightbringer realm.  Please kill this bug. :) Thank You!

**Comment by GuybrushGit** [comment]
Same as https://github.com/LightsHope/issues/issues/247, pet will start attacking once the target it not a full health.
