### ISSUE TITLE
Buccaneer's Strongboxes

### ISSUE THREAD

**Issue by T6nis89** [LightsHope/issues#253]
Hi.

I would like to report a possible bug with Buccaneer's Strongbox. About week ago was the last time I leveled my lockpicking with Buccaneers Strongboxes, I did up to 104. Today when I went to continue leveling I opened up to 100+(took about 20min) strongboxes but got no skills. Since I have read a lot of guides, they all hint that in vanilla patches you must be able to level your lockpicking with Buccaneer's Strongboxes up to 175.

I should add that at the moment the Strongboxes appear as green, which means they should give skills.

I would appreciate if you look into this matter.

Elibar

**Comment by Godmatik** [comment]
Yes they should give skills but keep in mind it will be an extremely low rate.

Also, what level is your rogue? The skill can not go beyond level * 5.

**Comment by thepparker** [comment]
RNG
