### ISSUE TITLE
Messenger to Stormwind etc.

### ISSUE THREAD

**Issue by crackyoo** [LightsHope/issues#258]
Currently on Light's Hope you can accept the following three quests all at once without prerequisite:
https://classicdb.ch/?quest=120
https://classicdb.ch/?quest=143
https://classicdb.ch/?quest=145

From what I can see it's actually a 6-quest chain as follows: quest=120 quest=121 quest=143 quest=144 quest=145 quest=146

Sources:
https://web.archive.org/web/20050209094213/http://wow.allakhazam.com:80/db/qlookup.html?zone=33
https://web.archive.org/web/20050219020117/http://wow.allakhazam.com:80/db/quest.html?wquest=143
https://classicdb.ch/?quest=143 (comment from adashiel, patch 2.4.2)

Additionally the quest text makes more sense with this being a chain.

**Comment by QAkvastskaft** [comment]
Also confirmed by the master guide:
![image](https://user-images.githubusercontent.com/26366996/39399401-272eec7a-4b1d-11e8-8620-cb71dbaa0409.png)
