### ISSUE TITLE
Valentine Event [Horde Gift Collection] turn-in

### ISSUE THREAD

**Issue by Choctaw001** [LightsHope/issues#26]
Server: lightbringer
Faction: Horde
Character: Mikasuki

I have attempted the turn in Valentine event [Horde Gift Collection] item with NPC Kwee Q Peddlefeet next to Thrall in Orgrimmar.  Kwee Q Peddlefeet has the Blue question mark above him but when selected there is no turn in option.  The quest window shows "Here are the Final Standings!" Alliance/Horde.  I have put in two in-game tickets and was directed to open a ticket here.  I have 3 [Horde Gift Collection] items in my inventory for turn in.  Please advise.

**Comment by GuybrushGit** [comment]
The event is over you cannot turn those in anymore. The blue question mark still showing is a bug.

**Comment by Choctaw001** [comment]
When I first tried the turn in the event was not over.  Then Kwee Q Peddlefeet was removed and I put in a ticket, soon after Kwee Q was put back.  Thank you for your response.
