### ISSUE TITLE
Reputation discount for Human players

### ISSUE THREAD

**Issue by crackyoo** [LightsHope/issues#260]
Apparently the reputation discount at honored does not always work for human players. It seems to work at a certain point during the honored rep (not exactly sure when). Also I'm not sure if it only affects Stormwind rep or also the other ones.
https://imgur.com/a/NAs2DJU
This is from Darrowshire. I tested it with a Night Elf and I got the discount immediately after hitting honored.

**Comment by thepparker** [comment]
It was only Woo Ping and the two vendors near him that were not respecting reputation discounts due to a hotfix during the scourge invasion
