### ISSUE TITLE
Fear 1.11

### ISSUE THREAD

**Issue by Remex13** [LightsHope/issues#276]
Hello I think you guys need rewiev the break fear mechenics in 1.11 patch since I got feared, with full dots and he casted an immolate on me plus hes void walker was hittin me, 8 second in fear.. impossible in 1.11 it has been changed by blizzard so dont know whats wrong, its just impossible no?!
warlock was lvl 24 my same level.

**Comment by thepparker** [comment]
RNG, dots have less chance to break it on tick and the total amount of damage it can absorb varies with caster level
