### ISSUE TITLE
Open 1.12 patch, the related NPC did not appear.

### ISSUE THREAD

**Issue by bluehelp1989** [LightsHope/issues#277]
Hello!
After the compilation is completed, the 1.12 patch NAXX is enabled in the configuration file.
There is no associated NPC in the Holy Light Chapel.
Do you need any preconditions?
Thank you

**Comment by GuybrushGit** [comment]
What NPC?

**Comment by bluehelp1989** [comment]
Thank you for your reply. The problem has been solved. Thank you.

**Comment by Jinsheng-Peng** [comment]
@bluehelp1989 I have the same question, Can you tell me how to open naxx Event? thinkyou!

**Comment by Jinsheng-Peng** [comment]
@GuybrushGit  he Open 1.12 patch,but the naxx event not start!  me too~
