### ISSUE TITLE
Stratholme Holy Water should scale at 100% of spell damage

### ISSUE THREAD

**Issue by theloras** [LightsHope/issues#28]
Currently the Holy Water isn't scaling with the correct spell damage coefficient:

**Stratholme Holy Water**
Binds when picked up
Use: Inflicts between **438 and 562 damage** to Undead in a 10 yard radius. (cooldown 1 min)
"Just 1 calorie."
http://classicdb.ch/?item=13180#comments

_By Jaru on 06/14/2007 (Patch 2.1.1)
Some combat log screenshots of this item's effect when combined with spell damage (in this case ~700 as a moonkin):_
http://shrani.si/files/stratholyw11wax.jpg
http://shrani.si/files/stratholyw11way.jpg

_Using against the Constructs in BWL
Score 1.1     Vote: [-] [+] by kjoe, 7.5 months ago
Just so people know, this stuff scales with your +dmg gear.  I was hitting the contructs for around 1100 ea, with 2 crits hitting 2000 dmg.  Yes - this will bring mad aggro, so the trick is to delay for a sec or two while you have your mages and pally's and warlocks do their thing.  We use the throne method, so we can hit 35-40 of the contructs per Holy Water._
https://web.archive.org/web/20070410171354/http://www.thottbot.com:80/i13180

**Stratholme (Priest and Warrior) Dentarg**
_Published on Dec 31, 2006_
https://www.youtube.com/watch?v=oXFjVHqXCi0&feature=youtu.be&t=391

The Holy Priest with minimal spell damage on his gear was able to get the Holy Water to hit for 654 and 657 on the undead skeleton spawn adds during Baron Rivendare boss fight.

**Comment by Dalleren** [comment]
Well, 2 out of 3 sources are from patch 2.0.1 or later.
One source, the mage doing 1100 damage, is from Primo October 2016 (Mid-April 2017 and 7.5 months back in time). This corresponds to Patch 1.12.1.

I suggest that this is not introduced before patch 1.12.1.

**Comment by theloras** [comment]
@Dalleren - there's no way Blizzard would have boosted Holy Water's coefficient AFTER the xpac launched - if anything Blizzard went to town removing legacy items scaling or usability during TBC:

_Six Demon Bag: The damage spells cast by this item no longer benefit from a player’s bonus spell damage effects._
http://wowwiki.wikia.com/wiki/Patch_2.2.0

_Patch 2.4.2 (2008-05-13): Nightfall now has a chance to fail on targets over level 60._
http://wowwiki.wikia.com/wiki/Nightfall_(axe)

Enchant Weapon - Crusader
Reagents:
[Large Brilliant Shard] (4), [Righteous Orb] (2)
Permanently enchant a melee weapon so that often when attacking in melee it heals for 75 to 125 and increases Strength by 100 for 15 sec. _Has a reduced effect for players above level 60._
http://wowwiki.wikia.com/wiki/Enchant_Weapon_-_Crusader

**Comment by GuybrushGit** [comment]
https://youtu.be/Gu4stWs1mwY?t=793
http://www.warcraftmovies.com/movieview.php?id=16248

Patch 1.9. Holy Water hits for 683.

Roughly estimated from his other spell hits he has 170-205 spell damage, so if the Holy Water coefficient has the default 42.8% coefficient the damage can be between 510 and 649, doesnt fit.
With 100% coefficient the damage will be somewhere between 608 and 767, it fits.

**Comment by theloras** [comment]
A+++ :)

**Comment by theloras** [comment]
fix submitted = happy in the pants

**Comment by theloras** [comment]
was there a patch this week - if so, is this fix live yet?

**Comment by goffauxs** [comment]
Almost a month later and this is still not in the game. How come?

**Comment by theloras** [comment]
GOD WILLS IT THAT THIS FIX SHOULD GO LIVE!

**Comment by theloras** [comment]
is this live yet?

**Comment by goffauxs** [comment]
yes it finally is

**Comment by theloras** [comment]
https://cdn.discordapp.com/attachments/401138411286822927/429362644885962752/holy_water_spell_dmg_only.jpg

https://cdn.discordapp.com/attachments/401138411286822927/429362683528216586/holy_water_with_jotc_zhc.jpg

https://www.youtube.com/watch?v=K3dbd2YyeN0

:)

**Comment by theloras** [comment]
FYI absolutely cut and dry evidence here for 100% scaling as I had just come across these videos over the past week:

**Protection Paladin Defender V1**
_Published on Nov 30, 2006_
https://youtu.be/D8EFW-CEK70?t=67

https://cdn.discordapp.com/attachments/484066218911727618/496744305147510785/strat_holy_water_scaling.jpg

**Uber pally DPS**
_Published on Oct 10, 2006_
https://www.youtube.com/watch?v=VpfAsPk6k6g
