### ISSUE TITLE
Buff missing from scourge event?

### ISSUE THREAD

**Issue by Sabre142** [LightsHope/issues#281]
Destroying a necromantic crystal

> When all the Shadows are defeated, all players in the area will see their health and mana refilled, and will receive a half-hour buff called Soul Revival that boosts all damage by 10%

I don't remember getting this buff, is it in correctly?

Sources:
https://wow.gamepedia.com/Talk:Scourge_Invasion#Some_notes
http://web.archive.org/web/20071117054808/http://wow.allakhazam.com:80/db/item.html?witem=22999 5th comment down

**Comment by thepparker** [comment]
The buff exists
