### ISSUE TITLE
Seal of the Dawn not giving attack power against undead

### ISSUE THREAD

**Issue by Sebbex** [LightsHope/issues#284]
Hey! I was trying out this new trinket that i got from Stratholme and i noticed that it does not give 81+ attack power like it should when i attack undead mobs. I thought when i attack the undead mobs it should increase my AP count from 1040 (which what i had unbuffed) to 1121 AP. Is there something to it that i do not know like a hidden AP counter/bonus that i am not aware of or does the item simply not work? The fix would be easy if the case is that it simply does not give the 81+ AP against undead but i am not a coder/bug fixer but you should probably look into it by testing with and without the trinket on undead mobs. IF you want the item as reference you have it here wowwiki.wikia.com/wiki/Seal_of_the_Dawn.

**Comment by thepparker** [comment]
The character sheet does not update with such items
