### ISSUE TITLE
Warlord's Command - Giving quest requirement out when quest started.

### ISSUE THREAD

**Issue by Shotgunsaint** [LightsHope/issues#285]
Please correct so that Warlord Goretooth is not giving Important Blackrock Documents when the is quest started.

If you go and talk to Warlord Goretooth and start this quest, he gives you the quest item "Important blackrock documents"  This item is a requirement of the quest and is supposed to be found in LBRS randomly at one of the bosses.  I believe this was working as intended previously but has somehow changed recently.  Here is a couple links from before patch 1.11 and after patch 1.12 showing that this was never the case.  

https://web.archive.org/web/20060413235728/http://wow.allakhazam.com:80/db/quest.html?wquest=4903
https://web.archive.org/web/20071028174843/http://wow.allakhazam.com:80/db/quest.html?wquest=4903

**Comment by QAkvastskaft** [comment]
Missing 3 alternative spawn positions for the document also

At the feet of Overlord Wyrmthalak
**In an empty corner next to War Master Voone** - Only one available now
Near Highlord Omokk
Next to Urok's Tribute Pile
