### ISSUE TITLE
Un-blizzlike behaviour in spider wing (naxxramas)

### ISSUE THREAD

**Issue by groeterud** [LightsHope/issues#292]
Hello, I believe the models for the Carrion Spinners are about 2x what they are supposed to be, and they don't move like they should (making it impossible to access anub'rekhan's room solo as a rogue). Poisonous Skitters' pathing is also wrong. 

this video from 2006 shows correct size, pathing and behaviour of these mobs: 

https://youtu.be/1QximOcF5T8?t=135

As you can see by the video the skitters clearly portal in a half-circle around the room - rather than into the final room before Anub. 

Currently how it looks like: https://i.imgur.com/O3fAMhZ.png

**Comment by Kittnz** [comment]
Well clearly we don't have the correct model size for these. Thats why you engage them.
