### ISSUE TITLE
"of Holy Wrath" stat not rolling on items at all

### ISSUE THREAD

**Issue by budaletina** [LightsHope/issues#298]
Several sources claim the Holy Wrath stat should be rolled on greens and other items in the same way Frozen, Shadow etc Wrath is.
http://wowwiki.wikia.com/wiki/Master's_Cloak
A chest drops in Maraudon from a rare spawn that has this stat on by default, implying there is a built in function for Holy damage increase, therefore it existed in vanilla.
https://classicdb.ch/?item=17741

**Comment by Cabro** [comment]
That item is not "of Holy Wrath", so your proof is moot. As far as i know, many items with certain suffixes have been removed from drop tables because they never existed in vanilla. This one might be one of them.

**Comment by druidish** [comment]
The holy wrath suffix was removed from the random property rolls in 1.3.

http://web.archive.org/web/20050309031436/http://www.worldofwarcraft.com/patchnotes/patch-05-07-04.html
