### ISSUE TITLE
Event "Love is in the Air" is broken.

### ISSUE THREAD

**Issue by Bug-finder** [LightsHope/issues#3]
If you have buff Perfume (http://classicdb.ch/?spell=26682) or Cologne (http://classicdb.ch/?spell=26681) and have Love Token (http://classicdb.ch/?item=21815) you must see hearts over townspeople of the opposite sex. And if you "talk to one of these people and they will have a dialog where you can give them a love token.

Giving a token will do one of two things. First, you will get a 1 hour "Adored" debuff that gives you a Pledge of Adoration: Ironforge (or whichever city the townperson is associated with). The pledges have a variety of things in them, including temporary Peddlefeet pets, city-related flavor items which can be turned in later, and unbestowed friendship bracelets. If you give any love tokens while you have the "Adored" debuff, you will receive a Pledge of Friendship, which only contains a flavor item.

The other thing that can happen when giving love tokens is that you will get a 1 hour "Heartbroken" debuff and no gift. While you are heartbroken you cannot give love tokens. You can cure this debuff by having another player use an unbestowed friendship token on you.(http://classicdb.ch/?item=21815#comments) " but nothing happen - no dialog, no buff/debuff , no gift...

**Comment by Bug-finder** [comment]
Event now fully working.

**Comment by Bug-finder** [comment]
Now we have next bug - in [Darrowshire]Darnassus we can't see hearts above NPC. This morning all fully working. Many people complain that they can't get Gift...

**Comment by goffauxs** [comment]
Why was this issue closed? This event still does not work in Darnassus on Anathema. Works fine in Ironforge and Stormwind

**Comment by Bloodmoon-Darrowshire** [comment]
I think they fix it but fix dont introduce in live servers.

**Comment by GuybrushGit** [comment]
There are a number of bugs related with this event and the fixes will be applied next maintenance day.

The event dialogs not working in some NPCs is most likely not a bug at all, someone already talked to the NPC and you need to wait for the cooldown.

**Comment by goffauxs** [comment]
Well I hope it gets fixed tomorrow then. 

I know that there is an internal cooldown on each NPC but that is not the issue in Darnassus as the city is almost empty on Anathema yet the guards and vendors do not have the gossip option nor do they have the  [Love is in the Air](https://classicdb.ch/?spell=27741) debuff.

**Comment by GuybrushGit** [comment]
The event lasts 5 days, it will be over by then.

**Comment by Bug-finder** [comment]
After restart event is over and we don't know work event in Darnassus or no .... ((((((
