### ISSUE TITLE
Ratchet boat

### ISSUE THREAD

**Issue by thevipe** [LightsHope/issues#30]
was randomly teleported to razor hill graveyard when taking the ratchet boat from the barrens another guildmate had the same issue!

**Comment by thevipe** [comment]
also theres a druid spell that doesnt have the ratchet npcs attack cause i was just killed by a tauren druid and the npcs did nothing

**Comment by derekvcsr** [comment]
seems like people are glitching out a bit, in fact, I was stuck and had to die to get unstuck. I then was alive standing near my own Corpse.
![ratchet boat](https://user-images.githubusercontent.com/40891841/42424077-83e46d76-82d3-11e8-92cc-5f02fa946a03.jpg)

**Comment by thevipe** [comment]
not sure if this was fixed but imma close for now as this was looong ago
