### ISSUE TITLE
[Darrowshire][Tanaris] Ledger from Tanaris

### ISSUE THREAD

**Issue by Polopollo85** [LightsHope/issues#302]
Hello, I have (finally...) all the items for this quest and I wanted to turn it in but the game refuses.

I tried with addons, and with all addons disabled. Here are some screenshots:
https://imgur.com/a/eI0IFfJ

Let me know what is happening and if you can turn it in for me at worst please :)

Thanks

**Comment by Niceguyone** [comment]
Check https://github.com/LightsHope/issues/issues/153
