### ISSUE TITLE
Stacked Deathguards in Undercity

### ISSUE THREAD

**Issue by Kazzakor** [LightsHope/issues#307]
Hi, I just found that next to mob **'Master Apothecary Faranell'** are stacked much of mob **'Deathguard Elite'**. This is on live 1.11.1 patch on Lightbringer PVP server. They act like normal **'Deathguard Elite'**.

**Comment by brotalnia** [comment]
This can happen because guard posts are not implemented, thus civilian npcs can spawn infinite guards. Spawning a gameobject of type 21 (guard post) crashes the vanilla client for some reason.
