### ISSUE TITLE
[horde][Darrowshire][Melding of Influences] - Oozes don't merge

### ISSUE THREAD

**Issue by Polopollo85** [LightsHope/issues#309]
I did read here: http://classicdb.ch/?quest=4642

> Be sure to engage the Primal Ooze before you release the Encased Corrupt Ooze. Otherwise the quest won't work.
> 
> If all goes well, the two will merge and become a Gargantuan Ooze. Kill that (watch out, it makes a clone), loot your quest item, and head back to UC for your just rewards.

Which I did to be sure. (just a moonfire to pull).
But as you can see here they don't merge at all:
https://imgur.com/dXYFXMJ

I waited till all my mana was exhausted by healing me with low cost healing touch, but then I had to innervate and kill them. Nothing happened.

I just searched and saw that it was an issue several time in the past:

https://github.com/LightsHope/issues/issues/21
https://github.com/LightsHope/issues/issues/124

Please let me know when it will be fixed I really like this quest chain :) But it is tedious to travel all over the world for nothing :(

**Comment by Polopollo85** [comment]
Try again for science. Dropped the quest, took it again, went straight to ungoro. Still didn't merge.

**Comment by GuybrushGit** [comment]
https://github.com/LightsHope/issues/issues/21
