### ISSUE TITLE
Donova Snowden quest NPC Winterspring

### ISSUE THREAD

**Issue by Xengard** [LightsHope/issues#324]
Can't complete these quests, "Trouble in Winterspring!" and "Winterfall Firewater". When I get to Winterspring, she stands there, you can talk to her, but no quests show up to complete.

**Comment by Jack-Miller3** [comment]
Also experiencing the same problem. This isn't limited to the above quests, it is every quest associated with the NPC.

**Comment by Juicyone** [comment]
Yep .....

**Comment by Teffeltop** [comment]
Stuck with 4 quests I can't hand in to Donova Snowden also...

**Comment by oldamon** [comment]
Facing the same issue with several quests for Donova Snowden. She can be clicked on, but the pointer does not turn into a chat bulb, rather just the standard mouse pointer remains. As a result it is impossible to talk to the NPC, hence no quest can be accepted or completed at this NPC.

**Comment by ratkosrb** [comment]
Should be fixed here -> https://github.com/lh-server/core/commit/c6c33bc156aa3632341aac6c00c4ac4a4ce1f64a
