### ISSUE TITLE
Raleigh The Devout "In The Name of The Light" quest 

### ISSUE THREAD

**Issue by Halcyon702** [LightsHope/issues#328]
I completed this quest (In The Name of The Light) over a few days, half one night, and half the next.  I completed the quest (but did not hand it in) prior to the server restart on May15th and when the servers came back online I could not turn in the quest or even interact with the NPC.  

I tried the usual relog, disable mods, delete WDB folder, abandoned the quest and still cannot obtain the quest again, or even interact with the NPC.

**Comment by tomcroypa** [comment]
I'm having same question, can't interact with this npc at all, although I am on the prequest right before it.
