### ISSUE TITLE
Buff effects contain misleading tooltips.

### ISSUE THREAD

**Issue by sinerp** [LightsHope/issues#336]
This issue happen with different classes buff abilities. If player improves buff with talents, spell tooltip shows improved stats/armor/e.t.c. but when player buffs another game character, buff effect tooltip doesn't show improved stats/armor/e.t.c. This includes mage, priest, druid buffs and maybe others.

**Comment by Cabro** [comment]
That's not how it was in vanilla, they updated tooltips to reflect talents only in ... wotlk.

**Comment by sinerp** [comment]
Guess this can be considered blizzlike bug. But if bug is blizzlike it doesn't make it intended or valid game mechanic. Especially considering that tooltip doesn't affect game mechanics at all as far as I know. So what's rational reason not to fix tooltip except "not blizzlike"? I don't see any.

**Comment by ratkosrb** [comment]
Tooltips are in the client. They cannot be changed by the server.

**Comment by sinerp** [comment]
Ok, I see. It sucks then.
