### ISSUE TITLE
Barov Peasant Caller not supposed to remove stealth.

### ISSUE THREAD

**Issue by groeterud** [LightsHope/issues#350]
I'm not certain how other trinkets are supposed to work, but Barov Peasant caller (ItemID 14022) is not supposed to break stealth as shown in my source below from nov '06 - Well into patch 1.12.2 

https://youtu.be/1QximOcF5T8?t=21

You can see he clearly activates the trinket in stealth, so that the mobs aggro the adds while he is in stealth. He then breaks stealth by using a LIP.

**Comment by Cabro** [comment]
I'm sorry but that is bullshit. In the video you linked as proof he is EQUIPPING it, not using it.

**Comment by groeterud** [comment]
@Cabro You are indeed correct upon viewing it again!
