### ISSUE TITLE
NPC "Fishing Supplies" at Stormwind Canaal

### ISSUE THREAD

**Issue by IroTzu** [LightsHope/issues#379]
Respect, Light`sHope

I hope your day is unfolding well.

NPC "Fishing Supplies" is not interactive. It does not open its goods so you could buy "fishing supplies" like fishing pole, bait etc.

I appreciate all the effort that went into creating and maintaining the server, and I wish you success on your journey.

Regards, 
IroTzu

**Comment by ExodusINT** [comment]
Npc is "Catherine Leland" still not working after supposed fix

**Comment by QAkvastskaft** [comment]
https://github.com/LightsHope/issues/issues/355
