### ISSUE TITLE
Quest: C'Thun's Legacy (8801) - Text error

### ISSUE THREAD

**Issue by EinBaum** [LightsHope/issues#396]
The NPC will call male characters "Lady" in all quest-related texts
![image](https://user-images.githubusercontent.com/1443650/41257289-956ee376-6dcc-11e8-8da5-9e4e4a06cbdf.png)
![image](https://user-images.githubusercontent.com/1443650/41257299-9b9fda7a-6dcc-11e8-8953-3ac3079034d8.png)

**Comment by QAkvastskaft** [comment]
Correct should be Lord or Lady
from follow up:
http://web.archive.org/web/20060629121429/http://wow.allakhazam.com:80/db/quest.html?wquest=8802
