### ISSUE TITLE
Defias Trappers in Westfall cast backstab from far out of melee range

### ISSUE THREAD

**Issue by jfkusin** [LightsHope/issues#403]
Patch: Lightbringer 1.12

Issue: Defias Trappers (and probably Defias Smugglers too but they default to throwing when out of melee range) in Westfall can cast backstab from way too far out of melee range, possibly up to 25 YD's.

Expected Behavior: These mobs should only backstab in the proper melee range

**Comment by ratkosrb** [comment]
Same issue as https://github.com/LightsHope/issues/issues/402
