### ISSUE TITLE
Defias Smuggler backstabbing from 30+ yards away

### ISSUE THREAD

**Issue by gotmilk0112** [LightsHope/issues#405]
http://classicdb.ch/?npc=95#abilities

Some of the Defias mobs in Westfall have a Backstab ability, and for some reason, it seems to have no range restriction. I was running away from one of these mobs, and despite being about 25 yards away, I noticed that my health kept going down. Then I actually died, and looked in my combat log to see multiple instances of Backstab damaging me.

https://i.imgur.com/5N0YNYy.jpg

I can make a video of it, if you'd like.

**Comment by ratkosrb** [comment]
Same issue as https://github.com/LightsHope/issues/issues/402
