### ISSUE TITLE
Bug Quest Job Opening : Captain of Revantusk Village

### ISSUE THREAD

**Issue by Elvious** [LightsHope/issues#411]
Hi !

I've got an issue with the Quest Job Opening : Captain of Revantusk Village in Hinterlands. I can't complete it, as you can see on the screenshot. Moreover the quest progress is increasing even if the goal has been reached.

In the expected behaviour I am able to complete the quest and the progress is stop on 10/10 and not 14/10 for the kills.

![bugquest](https://user-images.githubusercontent.com/18071622/41511944-f92bab84-7280-11e8-8ea8-353be9d78d31.png)

Thanks for you job.

**Comment by QAkvastskaft** [comment]
This quest has been reverted to its vanilla state: https://vanillawowdb.com/?quest=7862
Please delete your WDB folder and you will be able to see the current state
