### ISSUE TITLE
Strigid Screecher, Nightsaber Stalker in Teldrassil

### ISSUE THREAD

**Issue by crackyoo** [LightsHope/issues#42]
There are 2 Strigid Screechers and 1 Nightsaber Stalker in Teldrassil near Dolanaar which are usually only found farther away from town. 
Also these 3 mobs have a respawn time of roughly 20-30 seconds with no other players than me near them.
https://imgur.com/a/y88jL
https://imgur.com/a/Z8SuR

old thottbot and current classicdb links:
https://web.archive.org/web/20070519073401/http://thottbot.com:80/c1996
https://classicdb.ch/?npc=1996
https://web.archive.org/web/20071024184512/http://thottbot.com:80/c2043
https://classicdb.ch/?npc=2043

Those 3 spawns should just not exist.

As a side note, I noticed that the Beast mob spawns in Blasted Lands are completely messed up with almost no Basilisks to be found anywhere, but tons of Vultures instead and Scorpid/Hyena spawns may have been off too. I'm not sure if this was an intentional change, possibly to combat the shortage of Vulture Gizzards. I don't remember this being the case on the old nost. Nonetheless I'm not a fan of the current Blasted Lands spawns, I can make a more detailed report on that matter if desired.

**Comment by brotalnia** [comment]
Blasted Lands spawns are based on Joana's videos, i even did the correct waypoints for the mobs. Old spawns in the db were from TBC. Blizzard had changed a lot of the spawns then. Compare with Joana's videos and only report differences compared to that, or other 2004-2006 videos if you can find any.

**Comment by crackyoo** [comment]
Hey, thanks for the clarification!
