### ISSUE TITLE
Wrong mob's location.

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [LightsHope/issues#43]
Winterspring Owl (vanillawowdb.com/?npc=7455)
It's very strange that one of these owls forgot something in silithus ?
![wowscrnshot_010418_233813](https://user-images.githubusercontent.com/30354821/36643850-cc8f6084-1a83-11e8-8a7d-5d38a52114ab.jpg)
Here is the link of old allakhzam.com http://web.archive.org/web/20060614010757/http://wow.allakhazam.com:80/db/mob.html?wmob=7455#map
Аs you see these owls live only in Winterspring.

**Comment by GuybrushGit** [comment]
That's intentional, it was there on retail as well.
