### ISSUE TITLE
Young Goretusk crit damage very high

### ISSUE THREAD

**Issue by aheinzm** [LightsHope/issues#435]
Normal hits my level 12 mage between 15-20. Crits were 100+

https://imgur.com/a/Ch9yCSL

**Comment by Cabro** [comment]
The first attack does more damage because it has some charge in it. If it crits, it's obviously more.

**Comment by QAkvastskaft** [comment]
Rushing Charge:
https://vanillawowdb.com/?npc=454#abilities
