### ISSUE TITLE
[Missing Quest] Journey to Astranaar

### ISSUE THREAD

**Issue by ghost** [LightsHope/issues#445]
_Patch 1.2_ was released in _December 18th, 2004_. This quest was added to _Allakhazam_ on _May 28th, 2004_.

**[Realm]**
- Name: Northdale

**[Quest]**
- Name: Journey to Astranaar
- Attain: 20
- Level: 20
- Faction: Alliance

**[NPC]**
- Name: Fiora Longears
- Location: Theramore Isle - Dustwallow Marsh

**[Sources]**
Quest: http://web.archive.org/web/20041120150309/http://wow.allakhazam.com:80/db/quest.html?wquest=1133
NPC: http://web.archive.org/web/20041115100623/http://wow.allakhazam.com:80/db/mob.html?wmob=4456

**Comment by QAkvastskaft** [comment]
Current behavior:
Quest currently need https://vanillawowdb.com/?quest=1132 to be completed to unlock

Correct behavior:
https://vanillawowdb.com/?quest=1132 should be a breadcrumb quest only

Source:
Masterguide: under Thousand Needles
![image](https://user-images.githubusercontent.com/26366996/42055640-0487fe0c-7b18-11e8-9159-716d94ced39e.png)
