### ISSUE TITLE
Battleshout.

### ISSUE THREAD

**Issue by Yuzzlebug** [LightsHope/issues#446]
Battle shout does not grant ANY threat.
just tried this:
had 100 rage before fight with mob.
did 1 autoattack with a partymember in group.
then he did 1 autoattack and pulled aggro.
i then spammed 7 battle shout.. > nothing

(people told me that rebuffing could grant threat - it did not.)

so a pack of 10 elites. you need to change stance to battle stance. thunderclap spam dmo shout (and by doing that take 10% more dmg due to battlestance.) AND aswell tab+sunderspam to keep threat on all mobs. aswell as having other partymembers spamming AE-spells. seems very unreliable.
i can say, tried now with 4 other partymembers. everyone tried removing buff so we reapplied the buff everytime. still no threat.
vanilla wow > battle shout grants threat per how many partymembers there is, then it's divided by how many mobs there is.
as it should be.

on everysingle private server i've played on, it grants nothing.

Please do write a response if you know anything about this

**Comment by GuybrushGit** [comment]
This is working correctly. BS is adding threat per party member.

**Comment by Yuzzlebug** [comment]
Did you try it yourself?
If so, fine.

But i decided to wait till retail instead. Cba

Skickat från min iPhone

**Comment by Zarant** [comment]
Battle shout on this server is handled the same way healing spells are, it divides the threat generated evenly among all npcs in combat with you.
