### ISSUE TITLE
Bugged Wolfrunner Shoes

### ISSUE THREAD

**Issue by nekrohren118554** [LightsHope/issues#45]
-

**Comment by nekrohren118554** [comment]
This item - https://classicdb.ch/?item=13101
Wolfrunner Shoes adding stats incorrectly.
It should add +11 int/stam/spirit and + 13 SPD 
But in fact this shoes dnont adds int - only +11 stam/spirit.
Plz fix it

**Comment by GuybrushGit** [comment]
Classicdb is not a valid source, those shoes don't have int on this patch.
They're actually missing 11 agility: https://web.archive.org/web/20050225005941/http://www.thottbot.com:80/?i=16052
