### ISSUE TITLE
[Missing Quest] The Algaz Gauntlet

### ISSUE THREAD

**Issue by ghost** [LightsHope/issues#459]
_Patch 1.2_ was released in _December 18th, 2004_. This quest was added to _Allakhazam_ on _March 25th, 2004_.

**[Realm]**
- Name: Northdale

**[Quest]**
- Name: The Algaz Gauntlet
- Attain: 15
- Level: 21
- Faction: Alliance

**[NPC]**
- Name: Mountaineer Rockgar
- Location: Dun Algaz/North Gate Pass - Loch Modan

**[Sources]**
Quest: http://web.archive.org/web/20040917224212/http://wow.allakhazam.com:80/db/quest.html?wquest=455
NPC: http://web.archive.org/web/20041114044211/http://wow.allakhazam.com:80/db/mob.html?wmob=1342

**Comment by QAkvastskaft** [comment]
Current behavior:
Quest currently need https://vanillawowdb.com/?quest=468 to be completed to unlock

Correct behavior:
https://vanillawowdb.com/?quest=468 should be a breadcrumb quest only

Source:
Masterguide:
![image](https://user-images.githubusercontent.com/26366996/42054640-3aa30926-7b15-11e8-995a-5a0e66db6e7b.png)

**Comment by ratkosrb** [comment]
Fixed here -> https://github.com/lh-server/core/commit/955cc28460189b105aeb193f35e8b05ed099efc2
