### ISSUE TITLE
Fine Light Crossbow having different stats from normal

### ISSUE THREAD

**Issue by CrimsonHollow** [LightsHope/issues#462]
The item stated above with the id of 15808 is supposed to have 29 static dmg and 10.7 dps as shown in here: http://classicdb.ch/?item=15808 , https://vanilla-twinhead.twinstar.cz/index.php?item=15808 and also in my own local version of the Lights Hope core (i use it for testing around). While ingame it currently has 20 static dmg and 7.4 dps.
![fine light crossbow northdale](https://user-images.githubusercontent.com/22963563/42027425-5b7fa764-7ad2-11e8-98a2-5710b9a4e9b1.png)
![fine light crossbow light s hope core local](https://user-images.githubusercontent.com/22963563/42027426-5ba7447c-7ad2-11e8-8081-0deff55ed84b.png)

**Comment by QAkvastskaft** [comment]
Invalid:
https://web.archive.org/web/20060526233139/http://wow.allakhazam.com:80/db/item.html?witem=15808
