### ISSUE TITLE
Minor Recombobulator (northdale)

### ISSUE THREAD

**Issue by Javelja** [LightsHope/issues#465]
The trinket [Minor Recombobulator](https://classicdb.ch/?item=4381) is currently just a white trinket with no on use spell attached to it.  If it's not ingame yet, the whole trinket should be removed. If it is correctly ingame then this obviously needs a fix. 
[Ingame screenshot after deleted wdb](https://i.imgur.com/piEFT2F.png)

**Comment by ratkosrb** [comment]
Fixed here -> https://github.com/lh-server/core/commit/955cc28460189b105aeb193f35e8b05ed099efc2
