### ISSUE TITLE
Fiora Longears

### ISSUE THREAD

**Issue by Daydamage** [LightsHope/issues#468]
The quest "Fiora Longears" from Menethil Harbor states that I should meet her in the lovely port of Auberdine, though she is located in Theramore Isle (this is correctly stated in the short version of the quest description on the other hand). 
No need for a link/source I believe, since it's a minor detail.

**Comment by QAkvastskaft** [comment]
Correct text:
https://web.archive.org/web/20050102160153/http://wow.allakhazam.com:80/db/quest.html?wquest=1132
