### ISSUE TITLE
about ban

### ISSUE THREAD

**Issue by Yolincc** [LightsHope/issues#476]
i dont know solve my problem at here.
I play lh with my wife at home.We didn't use plug-ins and scripts, or even macro commands.
We are very anxious to upgrade. We haven't slept well for a few days.
Is it because the plug-in I used has a problem? I'm so wrong, I just like its interface.This is its address:http://www.luacn.net/thread-14707-1-1.html.
Or because I used the accelerator?Because of network latency, I must use it to reduce latency.This is its address:https://www.lonlife.cn/

We were very hard to get to the 26 level.
We follow the rules of the game very much.I don't know why I'm going to ban me.Please tell me why :(
i am very inquietude now.

**Comment by QAkvastskaft** [comment]
This is not the correct location for this, ban appeals should be submitted on the project site.

Please read the following before proceeding:
[Ban appeal info](https://forum.lightshope.org/viewtopic.php?f=8&t=488)

Thank you

**Comment by Yolincc** [comment]
Well, if you are an administrator, I think you should try to help me. Because I didn't do anything that violated the rules of the game, which affected my upgrade arrangement.:(

**Comment by Yolincc** [comment]
Has affected my sleep, this long wait.I just want to know the reason.Why my efforts will be banned?It's too unfair for me.

**Comment by ratkosrb** [comment]
There are no administrators on github, nobody here can unban you.
