### ISSUE TITLE
[Warlock] Pyroclasm Talent Broken

### ISSUE THREAD

**Issue by Tunesisback** [LightsHope/issues#478]
Warlock destruction talent "Pyroclasm" does not properly stun npcs.  Tested with ranks 1 and 2 of hellfire, and ranks 1 and 2 of rain of fire.

**Comment by Tunesisback** [comment]
this is northdale on patch 1.2

**Comment by Tunesisback** [comment]
pyroclasm does proc for soulfires

**Comment by QAkvastskaft** [comment]
It works on dev branch:
![image](https://user-images.githubusercontent.com/26366996/42412631-24890e36-8210-11e8-9088-15ac4d83cfa4.png)

Note: It will probably only proc on the first tick

**Comment by Tunesisback** [comment]
ya since wednesday i have noticed it stun once, so it appears to have started working (since the "patch"?).  shouldn't it be every pulse and not just the first tick?
