### ISSUE TITLE
[Quest] Redridge Mountains Questname MISSING IN ACTION

### ISSUE THREAD

**Issue by Edgewood411** [LightsHope/issues#491]
The quest has the NPC walking the entire length back to lakeshire. In the past, according to multiple leveling guide, it states that the NPC will get outside the cave and then rest (to let the player eat/drink) once that happens he runs, not walks, to lakeshire.

**Comment by gotmilk0112** [comment]
He has always walked.

Video from retail vanilla (or maybe TBC, given the date) https://www.youtube.com/watch?v=nRyMHR0SlAs
