### ISSUE TITLE
A letter to The light's hope GM

### ISSUE THREAD

**Issue by dongli5656** [LightsHope/issues#510]
Honorific GM
Thank you very much for reading this letter.Maybe it will take you a long time to finish reading this letter, but I still hope you can read it as far as possible.
Im a player with the your game for 2 years almost,
In this morning my game Id was frozen by RMT,i never meet this situation,i don't know how to do.Im sure i didn't  do anything with breake the rules ,I just wanna continue play the game with my friends.So next is the source of my gold, maybe they can speed up my complaint process
I borrowed 68 gold from my four friends
25 gold from Boa he is my LH's president of the guild and he is my old friend,the second one is my guild member
when I was lv40,i ask him who can borrow me some gold so i can learn riding and buy a horse and Cupidxiao borrowed me 20 gold and i promise i will give her 30 gold back,cause im very grateful  for he can borrowed me.
The third one is a mage his name i cant remembered,u know as a chinese usually just  remember his name with the firt letter when i was lv 30 maybe,we do the quest together and we add friends each other,when i was lv 40 i ask can he borrowed some gold for the horse,he borrowed 15 gold.
The fourth is a mage he play with me when i lv 12 and he borrowed me 8 gold.
This is my gold coin for all the places to get, I really didn't breake the rules and i also know maybe this letter won't change what,but i really hope the GM can read the end,as a chinese player i try to do a good player and keep the rules as much i do,I also hate the gold seller and i won't buy any gold with them dirty gold never ever.Cause they breake the game's balance and admission.
I didn't know the seriousness of the matter at first untill i find my game ID permanent freezing,I'm very scared , so i think So I think it's necessary for me to explain it clearly.
I swear to God that all I said above is true and there is no place for deception.I just wanna play this game to remember my teammmates 10 years ago.
Hope the Light's hope can help me.
Thank you very much for reading this letter and thank you for your do anything with the light's hope.

                                                                                                                 From the love WOW player

**Comment by dongli5656** [comment]
I really have no way to ask for help. I can only find a letter to GM here.

**Comment by Sabre142** [comment]
Message a GM on Discord.

**Comment by ratkosrb** [comment]
The github is for developers, game masters don't read it.
