### ISSUE TITLE
Quest "A Strange Red Key" not working.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#512]
The NPC that is supposed to finish this quest, Captured Arko'narin is not doing it.
quest=5202

**Comment by QAkvastskaft** [comment]
Been an open issue for a long while. Can't figure out how/when it breaks

**Comment by Cabro** [comment]
Once i start the quest, this NPC doesn't have the yellow question mark on its head. Could it be that there is another NPC assigned to finish the quest in the db?

**Comment by peterschriever** [comment]
Just farmed out the Blood Red Key to find out the quest still seems to be bugged. On Northdale i cannot complete the quest. Cage opens, even without the key but the npc doesn't react.

![image](https://user-images.githubusercontent.com/6523141/55573393-23988b80-570a-11e9-8307-e13523c69c62.png)

**Comment by gazebosx3** [comment]
Same
