### ISSUE TITLE
Bug - through the walls

### ISSUE THREAD

**Issue by kondziu5** [LightsHope/issues#52]
Hi. Server Lightbringer.

You can target enemies and target objects through the walls - by the mouse click as same as TAB targetting.

**Comment by GuybrushGit** [comment]
How is this a server bug?

**Comment by Cabro** [comment]
Oh, if you didn't play on retail, you wouldn't see this as a bug. On retail in Kara for example, you couldn't target Netherspite like this. :)

**Comment by GuybrushGit** [comment]
Don't think this is something the server can control.
