### ISSUE TITLE
Improved Drain Soul not working correctly

### ISSUE THREAD

**Issue by SilverSaw** [LightsHope/issues#527]
Hello,

Description:
Improved Drain Soul talent description says the following:
> Gives you a 100% chance to get a 100% increase to your Mana regeneration for 10 sec if the target is killed by you **while you drain its soul**. In addition your Mana may continue to regenerate while casting at 50% of normal.

I bold "while you drain its soul" because this part is working partially.

How to Reproduce:
If you attack your enemy with your pet and cast Drain Soul simultaneously and if your last hit is made by your pet while you still draining its soul, you should get buff from Improved Drain Soul talent. Now its not working like that, you get nothing and talent is not working in this cases. Right now buff only appears if you kill your enemy with damage from Drain Soul, if last damage hit before enemy health pool hit 0 is from Drain Soul spell.

Best Regards.

**Comment by Haiwuu** [comment]
**if the target is killed by you**
