### ISSUE TITLE
Long Forgotten Memories - Unable to Complete

### ISSUE THREAD

**Issue by Eldwinn** [LightsHope/issues#53]
Referencing  https://github.com/LightsHope/issues/issues/34 . 

I am encountering this exact same issue. However the fix did not resolve the issue for myself. Anachronos did not allow me to complete Long Forgotten Memories. If further investigation could be completed? 

In game name is Eldwinn. Lightbringer 1.9

**Comment by GuybrushGit** [comment]
The fix was not applied yet.
