### ISSUE TITLE
People cant see my messages/whispers, i cant mail to my alt. I guess its some gold-sellers spam block.

### ISSUE THREAD

**Issue by Saido4563** [LightsHope/issues#535]
When i create some party for dungeons i spam some stuff in whispers like (Looking for healer/tank for BFD) for every healer/tank in /who with levels that i need for dungeons.

-So i guess i get blocked by spam-system
-Can you fix it? or make that i cant get that block in future

I create ticket but no answer for 10 hours
Its really makes bad game-experience for me, because i cant play without communicating.

**Comment by Saido4563** [comment]
Still in mute with my 30 lvl. srsly?

**Comment by Saido4563** [comment]
1 month, problem still exist

**Comment by brotalnia** [comment]
Only a GM can help you. Developers are not game masters.
