### ISSUE TITLE
Engineering: Mechanical Dragonling, Ornate Spyglass - Not Working

### ISSUE THREAD

**Issue by Mordrux** [LightsHope/issues#536]
Hi, this items does not work ... 

This spell its not Available to you .. and cooldown reset ...

Please fix this .. Thank you

**Comment by ratkosrb** [comment]
Not a bug. Disabled temporarily on LH live servers. Go test on development branch and you'll see they are working.

**Comment by justwowthings** [comment]
bump - mechanical dragonling still not working
