### ISSUE TITLE
 the horse is not called

### ISSUE THREAD

**Issue by madevp** [LightsHope/issues#545]
Server Northdale.
Good day, spent 15.99g for riding training, after which I bought a mount for 63.99.99g and can not climb on it. Everything was recorded on the stream, stream time 11:39:29
Please solve the problem! link to the stream:   https://www.twitch.tv/videos/281426772

**Comment by Gamemechanicwow** [comment]
Have you tried clearing your WDB folder?

**Comment by madevp** [comment]
Yes, tried.
