### ISSUE TITLE
Rogue Beginner Quests (Possibly Beyond) Reference Wrong Name

### ISSUE THREAD

**Issue by Dobrounoc** [LightsHope/issues#548]
I've started a Rogue and have noticed in the first few quests the Rogue Trainer in Northshire calls me Cailel in the quest text.

**Comment by Gamemechanicwow** [comment]
ye.. needs a minor fix.

https://classicdb.ch/?quest=3102
Completion:
"You're gonna find that there a number of outfits that'll covet our skills, **Cailel**."

https://www.getmangos.eu/bug-tracker/mangos-zero/0-archived-reports/encrypted-letter-quest-3102-r1318/
