### ISSUE TITLE
You are unable to zone into raids when trash fights are ongoing.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#55]
This should only happen for boss fights...
http://wowwiki.wikia.com/wiki/Patch_1.11.0 - it refers to boss and boss's adds if there are any, (when it says "almost entirely raid bosses").
This shouldn't even be implemented before 1.11 :)))

**Comment by theloras** [comment]
There's also a bug that if say someone agros a mob OUTSIDE the instance but zones in anyway, the entire raid gets put into combat INSIDE the instance - not sure if that is linked to this or not - but it's annoying AF in Naxx.

**Comment by Cabro** [comment]
That's another bug, open your own :P

**Comment by Cabro** [comment]
What more info, you should be prevented to enter the raid only when there is a BOSS fight ongoing. It says so very clearly in the patch notes.
The current behaviour is unblizzlike.
