### ISSUE TITLE
Rogue "Vanish" bugged? (Northdale)

### ISSUE THREAD

**Issue by G4DStudio** [LightsHope/issues#551]
Why rogue "Vanish" removes all magical/curse Effects?
It's bugged or a patch 1.2?

**Comment by thepparker** [comment]
It does not remove all effects, only slow and roots.

**Comment by G4DStudio** [comment]
thepparker - its not true.
hunter mark. curse, dots - removes...
watch the video https://www.youtube.com/watch?v=TVmEtkZ1bjY
hunter mark was remove by Vanish

**Comment by Cabro** [comment]
Yes, it removes everything. Something like Cloak of Shadows was in TBC... but in vanilla. Rogues are op in this state.
