### ISSUE TITLE
I can't send mails please, help me!

### ISSUE THREAD

**Issue by nathanyon** [LightsHope/issues#555]
I tried to send mail to my another character and my friend it says "mail sent" but nothing happens the item stay on bag. I've disable all addons but still with same problem. Can someone help me ? 
My chars are: "Leam" and "Mandyl"

**Comment by Shaanan123** [comment]
I got the same issue with all charac of my account, chararc : Shaanan

**Comment by thepparker** [comment]
open a ticket

**Comment by Shaanan123** [comment]
in game?
