### ISSUE TITLE
the horse is not called

### ISSUE THREAD

**Issue by madevp** [LightsHope/issues#558]
Server Northdale.
Good day, spent 15.99g for riding training, after which I bought a mount for 63.99.99g and can not climb on it. Everything was recorded on the stream, stream time 11:39:29
Please solve the problem! link to the stream: https://www.twitch.tv/videos/281426772
what could be the problem?

**Comment by VendettaMoarte** [comment]
i have the same Problem...

**Comment by Sabre142** [comment]
Delete WDB folder.

**Comment by VendettaMoarte** [comment]
With much Thanks Bro!
