### ISSUE TITLE
Wolfmounts got all races (even alliance races) but no tauren!

### ISSUE THREAD

**Issue by Premixx** [LightsHope/issues#564]
hey me and a friend (both tauren) gave a orcfriend 65g for a wolf mount, we are not lvl 40 yet but we see in inventory that the wolf got all 7 wow races, even alliance races but no tauren? seems like you made the mounts by your own and forgot the tauren race, i mean in classic tauren can 100% ride a wolf, just no raptor and no hourse but they can ride wolfs, i know that, can you please change this so we can ride our wolfs at lvl 40? (we already deleted wdb folder and talked to a gm he said this seems to be a bug)
thanks

**Comment by Seberats** [comment]
are you exalted with orgrimmar?

**Comment by Premixx** [comment]
im not but i dont need, its about the races on the mount it dont say tauren

**Comment by Seberats** [comment]
Are you 40 now?

**Comment by ratkosrb** [comment]
Blizzlike.

```
World of Warcraft Client Patch 1.3.0 (2005-03-22)
 - Mounts now are Horde or Alliance restricted in the tooltip. We do 
   not intend to allow Horde players to ride Alliance vendor-purchased 
   mounts and vice versa.
```
Prior to 1.3, mounts showed as being usable by races of the opposing faction, but they were not really, since its impossible to train the required skill.

```
World of Warcraft Client Patch 1.7.0 (2005-09-13)
 - Tauren can now ride wolves if they learn the wolfriding ability.
```

Tauren were only allowed to ride wolves after 1.7. Currently Northdale is at 1.2.

**Comment by Seberats** [comment]
Can they use AV wolf?

**Comment by Premixx** [comment]
oh my gooooood well thanks ^^

**Comment by ratkosrb** [comment]
![wolf](https://user-images.githubusercontent.com/35845488/42522771-89a5f66a-845b-11e8-9813-818651ec0dcd.jpg)

Horn of the Frostwolf Howler does not have any racial restrictions, and does not require a riding skill until 1.12. You can ride it as a Tauren.

![wolf2](https://user-images.githubusercontent.com/35845488/42522988-0b545968-845c-11e8-8203-79f628d314ee.jpg)
Allakhazam comments confirm it.
