### ISSUE TITLE
Slashclaw Bracers giving wrong stats once equipped

### ISSUE THREAD

**Issue by Jumbawumba** [LightsHope/issues#570]
Instead of +7 Agility +7 Stamina and +6 Spirit they give +6 Strenght and +7 Spirit

**Comment by Gamemechanicwow** [comment]
They are changed later on. This is a progressive server and items may change on each patch according to how they did on retail vanilla.

Logout and delete your wdb folder, so you can see the actual stats on item, instead of the values you have in your cache.
