### ISSUE TITLE
Elwynn forest always raining

### ISSUE THREAD

**Issue by vashin1** [LightsHope/issues#578]
This zone should be more flooded then the wetlands with the amount its raining on northdale, can definitely use some toning down, its very odd always going from a sunny stormwind to monsoon like weather in Elwynn forest 80% of the time.

**Comment by Cabro** [comment]
Should there even be weather in 1.2? :D

**Comment by vashin1** [comment]
Apparently so!  This is as far as I know the only zone that has this issue!

**Comment by Cabro** [comment]
Sorry, that's [patch 1.10](http://wowwiki.wikia.com/wiki/Patch_1.10.0#toc).
It's bonus, enjoy it!
