### ISSUE TITLE
Account name change

### ISSUE THREAD

**Issue by sweapzen** [LightsHope/issues#588]
Hey guys
Thanks for the opportunity to play the awesome era of Wow again! Absolutely fantastic. One question though, can you or I change my account name in any way? I might have done the stupid thing and named my account the same as a character...

Thanks in advance

**Comment by toinetoine** [comment]
Why's this an issue? Just pick a good password and you'll be fine.

**Comment by Gamemechanicwow** [comment]
and enable 2fa

**Comment by thepparker** [comment]
2fa + secure pw
