### ISSUE TITLE
The "more powerful spell is present" mechanics is not taking into consideration talents or bonuses that improve the spells.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#59]
For example:
- you can cast battleshout rank 6 with 0/5 improved battle shout over a battle shout rank 6 with 5/5 improved battle shout.
- you can overwrite battle shout rank 6 with t2 bonus by casting shout without the set bonus

Same for hots and dots.

They should take into consideration base rank and bonuses.

**Comment by Cabro** [comment]
Na it's ok, leave it like this, classic inc.

**Comment by thepparker** [comment]
Was changed later to take spellpower bonuses into consideration. In Vanilla it is entirely based on the rank of the spell.
