### ISSUE TITLE
Items Magequest

### ISSUE THREAD

**Issue by Shahryan** [LightsHope/issues#590]
At lvl30 and lvl40 there are two longer questchains for mages. At lvl30 you get a wand and at lvl40 there is a staff.

Sadly, both items dont give the right stats here. Both items should give Intellect to the player, they dont grant it. Both items should give spellpower (the wand i take frost) and both dont give that spellpower to the player.

I hope and think that are not big issues and can both get fixed soon.

Lg Shahryar

**Comment by Gamemechanicwow** [comment]
This is a progressive server. Items may change over patches according to how they did on vanilla retail.

example:
Celestial stave at patch 1.2: https://vanillawowdb.com/?item=9517
Celestial stave at patch 1.12: https://classicdb.ch/?item=9517

Don't forget to clear your wdb folder, you may have some items cached from other servers.

**Comment by Shahryan** [comment]
But the tooltip of the staff is at the later patch, so there is a) a tooltip-bug or b) the staff himself bugged.

While both versions have int and the staff grants zero int to the player, its anyway not correct

**Comment by Gamemechanicwow** [comment]
Did you clear your wdb folder?

**Comment by thepparker** [comment]
Clear wdb
