### ISSUE TITLE
I do not see (ride 75) in the skills

### ISSUE THREAD

**Issue by MaxFlyMan** [LightsHope/issues#591]
Hello
I do not see (ride 75) in the skills.
You wrote to delete the WDB folder, but I did not have it. And the problem did not dare even when I went to another client of the game. You have already sent two letters with an explanation of one hundred this is a bug, but I can not fix it please fix it. The trainer shows that I bought him a skill. But the character does not have it.
Regards Max

Realm: NORTHDALE
character: Aeldar (warrior) alliance

**Comment by fromtexas** [comment]
same issue

**Comment by fromtexas** [comment]
ok, I've solved it.
For some reasons wow stors user settings in virtual srore.
Go to
C:\Users\USERNAME\AppData\Local\VirtualStore\Program Files (x86)\World of Warcraft
then delete or rename WTF and WDB folders

**Comment by MaxFlyMan** [comment]
Hi
Thank you
Tiger turned out to saddle, but in the bookmark skills there is no display. I removed everything I could, even re-installed the game. Apparently this is already a bug in the game.

**Comment by thepparker** [comment]
There is no 75 or 150 riding skill on Northdale. You only have the riding associated with a specific mount type until 1.12, and it is working as intended.

You must clear your WDB for your client to be aware that you do actually have the required skill.
