### ISSUE TITLE
Friend list is empty when I log in, after adding a friend, it comes back to normal

### ISSUE THREAD

**Issue by hussa91** [LightsHope/issues#61]
Few days ago I got this issue that my friend list is empty even though I got some friends added there.
After I add any friend (old or new) it turns back normal and shows full list as it was.
This happens every time I log in with this particular character.
I have tried to disable all add ons, but didnt help.
Also I removed folder WTF and WDB and started client again but that didn't help either.
Any suggestions?

**Comment by berillis** [comment]
Known issue, you have a character in your friendlist which has been deleted. Just remove the "Unknown" from there and it will work fine again.

**Comment by hussa91** [comment]
You were right. Thank you.
