### ISSUE TITLE
Gnomish Mind Control Cap not current to 1.2

### ISSUE THREAD

**Issue by L33tspeek** [LightsHope/issues#614]
The mind control cap can only be used on targets that aren't in combat, which wasn't implemented until patch 1.11

This severely limits the use of this item and as far as PVP goes makes it near unusable unless initiating a fight.

https://wow.gamepedia.com/Patch_1.11.0#Items

> The Gnomish Mind Control Cap may now only be used on targets that are not in combat.

**Comment by Gamemechanicwow** [comment]
Also referenced in: https://github.com/LightsHope/issues/issues/553

The base rule is that spells use the 1.12 version of the spell, since that is the client we are using.
