### ISSUE TITLE
The Annals of Darrowshire not working

### ISSUE THREAD

**Issue by Wiseguy420** [LightsHope/issues#620]
Quest in Western Plaguelands ''The Annals of Darrowshire'' isn't working. supposed to loot books in the andorhal town hall but its not working, ive tried to loot about 20 times over 2 days and submitted 2 tickets , the latter one asked me to go here and report it. thanks (Northdale)

**Comment by Cabro** [comment]
It works on LB. Curious it doesn't on ND.

**Comment by Wiseguy420** [comment]
nevermind, i fucked up.

**Comment by thepparker** [comment]
There's only 1 book that actually has the item ;)
