### ISSUE TITLE
Ram Riding Vendor Offering "Ram Riding (1)", Mounts Need "Riding (75)"

### ISSUE THREAD

**Issue by axbat** [LightsHope/issues#633]
The riding trainer at Amberstill Ranch offers "Ram Riding" for 20g. This grants the player the skill "Ram Riding (1)". The ram vendor has the normal five colored rams, but only one 60% can be used with "Ram Riding (1)". The other two 60% require "Riding (75)". There's a similar disparity with the 100% mounts. Attaching screenshots.

![screenshot_071518_195507](https://user-images.githubusercontent.com/2262019/42741844-a928bdac-886a-11e8-85cd-30f66770d002.jpeg)
![screenshot_071518_195509](https://user-images.githubusercontent.com/2262019/42741845-a93fe266-886a-11e8-86e5-a4431b465778.jpeg)
![screenshot_071518_195513](https://user-images.githubusercontent.com/2262019/42741846-a9572480-886a-11e8-9a66-937f9da7e686.jpeg)
![screenshot_071518_195515](https://user-images.githubusercontent.com/2262019/42741847-a96e42be-886a-11e8-84b8-d6c3fece60ec.jpeg)

**Comment by ratkosrb** [comment]
Delete your WDB folder.
