### ISSUE TITLE
Cannot see cross race mounts in the vendor inventory after hitting exalted with that race/faction.

### ISSUE THREAD

**Issue by UncleSluagh** [LightsHope/issues#640]
--

I recently hit exalted with Orgrimmar as a **Tauren**.
However, I cannot see any of the mounts the Orgrimmar Mount vendor has to offer, the NPC's inventory window opens up, but its completely empty as if he's out of stock!

This is obviously not working as intended, I have tried deleting my WDB, Restarting the game etc, nothing works.
I can see the mounts just fine on a level 1 Orc alt.

I cannot currently continue leveling.

Any feedback would be appreciated.

**Comment by ratkosrb** [comment]
Taurens could not ride Wolves until patch 1.7.

**Comment by UncleSluagh** [comment]
But I should still be able to see them in the vendor, why is this labeled invalid?

**Comment by ratkosrb** [comment]
No you shouldn't, just like how you can't see sets for other classes on the PvP vendors.
