### ISSUE TITLE
Reputation discount

### ISSUE THREAD

**Issue by Kikomaster** [LightsHope/issues#642]
After reach an eaxlted reputation with Stormwind, i was surprised to find my discount in this faction is still 10%. Not even 15%!
I opened a ticket, cleared WDB folder on the advice of GM.
I even reinstalled game client (twice!). Nothing changed, it is still 10%.

**Comment by Gamemechanicwow** [comment]
You get 10% at honored and another 10% for Rank3.

Gaining rep levels higher than honored have no effect on discounts.

**Comment by Kikomaster** [comment]
Wow, knew nothing about it. Thank you. And when did the system start with 5-10-15-20%?

**Comment by QAkvastskaft** [comment]
TBC patch 2.3

Vendor Discounts: All vendors with an associate faction now give discounts at all levels above neutral.
Friendly: 5% discount
Honored: 10% discount
Revered: 15% discount
Exalted: 20% discount


From http://wowwiki.wikia.com/wiki/Patch_2.3

**Comment by Kikomaster** [comment]
Thanks again! That's all I needed to know.
