### ISSUE TITLE
Paladin Seal of the Crusader Is Broken

### ISSUE THREAD

**Issue by 7revorj** [LightsHope/issues#647]
Please see this post https://www.reddit.com/r/lightshope/comments/8xarnt/is_seal_of_the_crusader_ever_going_to_get_fixed/

Seal of the crusader needs to be updated with the next patch, as would be "blizzlike" is this confirmed to be taking place?

**Comment by Gamemechanicwow** [comment]
https://github.com/lh-server/core/pull/166

**Comment by QAkvastskaft** [comment]
https://github.com/LightsHope/issues/issues/132
