### ISSUE TITLE
Rogue kick doesnt work correctly

### ISSUE THREAD

**Issue by Plusader** [LightsHope/issues#648]
Since I haven't found a related post, here's mine.
I'm just leveling through the legendary Barrens when I see my so far unused skill "Kick".

I started to use it and to my suprise it doesn't work like it should. 
The castbar of Quilboards and the StormECHSEN(area south-west of caverns of mists, lvl-range around 19) is being interrupted indeed, though their cast comes through anyway without the castbar active at this point and doing the normal damage.

Haven't tested it on other NPCs/in PvP yet.

**Comment by Cabro** [comment]
It's not from the Kick itself, it;s just that for some reason the spells themselves have the attribute to not be interruptible, because... level 19 NPCs should be really OP.

**Comment by QAkvastskaft** [comment]
See #434
