### ISSUE TITLE
Inventor's Focal Sword wrong stats pre 1.10

### ISSUE THREAD

**Issue by mooblia** [LightsHope/issues#649]
Inventor's Focal Sword (id 17719) seems to be missing +6 int it had up to patch 1.10.

Here is an archived link of the item before 1.10
http://web.archive.org/web/20050206201843/http://wow.allakhazam.com:80/db/item.html?witem=17719

Going by the assumption that it only changed once then it should've changed to the current state of the db in 1.10 where it says in patch notes
- The following items were found to be more powerful than intended and
  have been tuned to be more in line with their level: Satyr's Bow,
  Inventor's Focal Sword, and Scepter of the Unholy.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/lh-server/core/commit/d294701fe693bcab74b9519311bb4cf7e0f201a5
