### ISSUE TITLE
Attack and movement speed debuff stacking

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#65]
http://wowwiki.wikia.com/wiki/Patch_1.7.0
Spells and effects that reduce attack speed will no longer stack with each other. Some spells this change effects include Thunderclap, Frost Armor, the Doomguard's Cripple spell, the Icy Chill enchantment, and Hurricane.

**Comment by GuybrushGit** [comment]
Related mechanic thats also missing:  
>Do snares stack?
>No, only one snare can be active on a target at a time, the snare that slows the target the most is the priority, which can create problems when a short powerful snare like the one attached to improved blizzard hits a target. It removes the snare you have on them and then it vanishes shortly afterwards. Attempting to apply a less powerful snare on target already more powerfully snared fails. However Ice/frost armor snares don't operate on the same scale as they also slow attack speed. So you can have the ice armor snare on a target and any other frost snare, its just the movement reduction doesn't stack.
>http://web.archive.org/web/20060811120918/http://www.blizzardguides.com:80/frost_mage_guide.html

Some video evidence from vanilla:  
https://youtu.be/VkYGGefB5C8?t=235 CoC removes Frostbolt
https://youtu.be/VkYGGefB5C8?t=282 Blast Wave doesnt remove CoC
https://youtu.be/unusjpGt8bY?t=91 CoC doesn't remove Imp Blizzard
