### ISSUE TITLE
Account : Sec035 -- All characters deleted

### ISSUE THREAD

**Issue by sec035** [LightsHope/issues#653]
I was inactive for a decent amount of time due to life's demands and upon returning my entire account of characters had been erased. I'm not sure how to address this issue or if there even is a solution but I would love to have my warlock back at least so I can continue to play on this server. Please contact me @ Stevenclark962@gmail.com or on here !

**Comment by Gamemechanicwow** [comment]
No ingame support here. This bugtracker is only for server development.

You should make a ticket ingame or contact a gm on discord.
