### ISSUE TITLE
Hunter lost pet Humar The Pridelord 

### ISSUE THREAD

**Issue by purrk1tty** [LightsHope/issues#66]
--

Write your report here
Today Mar 1st I have been off and on checking on my other charatures and the last time on was on my hunter my cat Humar The Pridelord that i named BlackSpirit was happy and when i logged off and came back on after a couple hrs he was gone. I tried calling and nothing , i tried ressing and nothing, says i dont have pet, what should i do?

**Comment by GuybrushGit** [comment]
Sounds like its gone for good or maybe you stabled it.

**Comment by purrk1tty** [comment]
nope not stabled it, one time i had a problem feeding my pet . still do, i have to drag food to his portrat. i want him back.

**Comment by purrk1tty** [comment]
can anyone help me

**Comment by brotalnia** [comment]
Developers are not GMs and cannot restore your missing pet. The github is for bug reports only, not in-game support.

**Comment by purrk1tty** [comment]
ok, they told me to come here. i'lll try them again
