### ISSUE TITLE
E-mail

### ISSUE THREAD

**Issue by Veloris** [LightsHope/issues#660]
Hello! Can i change my email? I lost my mail dont remember login and password. Please help.

**Comment by Haiwuu** [comment]
Unable to change email, github isn't for account issues.

**Comment by Veloris** [comment]
Yes? And then why? Here everything is to share game problems.

**Comment by ratkosrb** [comment]
Github is for reporting bugs to developers. This is not a bug report. Developers are not game masters. We cannot help you with any account issues related to the LH live realms. Try the support section in the discord.
