### ISSUE TITLE
BRD Lyceum extra pats

### ISSUE THREAD

**Issue by Minnona** [LightsHope/issues#665]
What are these extra patrols in BRD Lyceum? They don't look blizzlike. They look like you guys added them manually. Never seen it on Anathema/LB.
Someone in discord said "added based on wotlk sniffs", is it wotlk project already?

**Comment by ratkosrb** [comment]
Do you have vanilla sniffs that contradict the wotlk sniffs? Seems unlikely that Blizzard would add extra spawns to a vanilla dungeon in wotlk, most of the content from vanilla is the same. If it was a nerf - removing spawns, then that would seem more plausible, but i don't see why they would buff the difficulty in wotlk. They usually did the opposite.

**Comment by Tobschinski** [comment]
They weren't even added, they patrols existed but were static spawns. You never noticed them because they were in a place you'd usually not go.
