### ISSUE TITLE
Error with quest in Human noob area.

### ISSUE THREAD

**Issue by corrupteddrake** [LightsHope/issues#67]
The quest "Milly Osworth" is the prequest required to do the quest "Milly's Harvest".
"Milly's Harvest" was designed to be done at the same time as "Brother of Thieves" (usually anyway)
However, the current behavior of this quest is that the prequest of "Milly Osworth" is "Brother of Thieves".

The real prequest of "Milly Osworth" is the quest "Wolves Across the Border" not "Brother of Thieves".

I do not any proof for this, but if you have ever played a human character you most likely have done these quests at the same time.  Worse there are some websites that say that the prequest for "Milly Osworth" is "Brother of Thieves" not "Wolves Across the Border" like it actually is.  However, there are a many places that have it listed correctly as well.  However, of all the places that have it listed incorrectly I find that they have "Milly Osworth" as the only quest that occurs after "Brother of Thieves" which is not true, since the next quest in the "Brother of Thieves" line is "Bounty on Garrick Padfoot"

**Comment by brotalnia** [comment]
This was intentionally changed by @kampeador back on the elysium repository, as he believed that this was the way it was in vanilla.

https://github.com/ratkosrb/server/commit/df0518ced560c5595498713f95970bfb7dc5deb9#diff-5b0b70a9d12e78288b7184f6e62e0d3d

> Before patch 2.4, quest Milly Osworth(id:3903) was available after Brotherhood of Thieves(id:18).

**Comment by GuybrushGit** [comment]
https://web.archive.org/web/20070101111538/http://wow.allakhazam.com:80/db/quest.html?wquest=3903

**Comment by placoto99** [comment]
https://web.archive.org/web/20070101111538/http://wow.allakhazam.com:80/db/quest.html?wquest=3903
If you read comments on that link " Turicus Scholar" with a decent rating score said that:  [Brotherhood of thieves] and [Wolves Across the Border] are both required to get [Milly Osworth].
