### ISSUE TITLE
Siegel von Wrynn

### ISSUE THREAD

**Issue by Leegis** [LightsHope/issues#674]
https://datenbank.classic-wow.org/?item=2933
The Item "Siegel von Wrynn" is a ring obtained due to a Quest from the Stockades.

Siegel von Wrynn
Finger
Soulbound by pickup
+3 Str
+3 Agi
+4 Stamina
+4 Int
+3 Spirit

at the moment the stats are shown as above, but the ring actually do grant 
+2 Stamina
+6 Spirit

it would be awesome, if the Item could be fixed.

Greetings

**Comment by Cabro** [comment]
That's how it was in the patch you play atm.

**Comment by QAkvastskaft** [comment]
This item will have it’s stats updated at a later patch. If you delete your WDB folder you will be able to see the current stats. 

This item is part of the progressive item mechanic here at Light’s Hope.
