### ISSUE TITLE
Murloc Scale Belt

### ISSUE THREAD

**Issue by Godmatik** [LightsHope/issues#686]
Equipping this item does not soulbound it to you.

**Comment by Gamemechanicwow** [comment]
Murloc Scale Belt is a common quality item in patch 1.2. In a later patch it will be upgraded to uncommon.

If you see this item ingame as a green item, you should exit wow and empty your WDB folder. That folder contains cached items.

DB that currently shows data from patch 1.2:
https://vanillawowdb.com/?item=5780

DB that shows data from patch 1.12:
https://classicdb.ch/?item=5780

**Comment by Godmatik** [comment]
Thanks for the info.

I already cleared out the WDB folder, so the client is incorrectly showing this as an uncommon item when it should be common.

Also, whenever you unequip and re-equip it, it gives you the soulbound prompt message.
