### ISSUE TITLE
Jingling Bell, not working

### ISSUE THREAD

**Issue by Danyy123** [LightsHope/issues#69]
Jingling Bell is meant to summon a reindeer companion... it used to work, it should still work. but now it doesn't. i have snowballs so that's not the problem. and all my friends who have the item is having the same problem too. this is not how it is meant to be, its meant to still work all year round, but you need snowballs to use it. just like the Winter Veil Disguise Kit, which still works.

If you can fix this problem then please do so. :<

I'll be testing the item everyday like i have been for the past few weeks waiting for it to work again.

:< please fix, i miss my reindeer :c

**Comment by GuybrushGit** [comment]
Fixed in https://github.com/ratkosrb/server/pull/8
