### ISSUE TITLE
Item Stat bug

### ISSUE THREAD

**Issue by DGProphet** [LightsHope/issues#694]
Northdale currenlty on 1.02

Finished Thandol Span quest where you blow up the cache. I selected cloth pants "Swampland Trousers" 
http://classicdb.ch/?item=4505   -     +11 Stamina + 4 Intel ... when equipped my stamina doesn't change.. change I seem to notice is +8 agility +5 spirit.

link to quest

http://classicdb.ch/?quest=633

**Comment by Shahryan** [comment]
You should use the Server-db for this patch.

Clear ur wdb-folder and relog.

**Comment by DGProphet** [comment]
Makes sense, I am sort of new to "this" , I will do that and remember for future reference/troubleshooting. 
Before I open another ticket.

Thanks

**Comment by QAkvastskaft** [comment]
This item gets updated stats in patch 1.10
