### ISSUE TITLE
Tauren cant buy raptor mounts

### ISSUE THREAD

**Issue by panglaozhang** [LightsHope/issues#698]
Dear GM,

This is my SECOND ticket regarding to my mount purchasing issue. My account ID is XXX and I have a lvl 60 Tauren druid named “mumuniu” on Lightbringer. My druid's reputation is already exalted with Darkspear tribe which means the vendor should sell a raptor to me. However, when I clicked to that NPC, he sold nothing. So I followed the instruction from the first ticket to delete WDB folder and also disabled all addons and blah blah blah. Unfortunately the issue persists. Please help!

**Comment by Cabro** [comment]
Taurens never could use raptor mounts in vanilla. The faction ones.

**Comment by panglaozhang** [comment]
I ,m sure seen some Tauren players have raptor mounts and they are not ZG loots...

**Comment by Godmatik** [comment]
Cabro is correct, Taurens were not allowed to use the normal raptor mounts. I remember back in Vanilla this caused quite annoyance on the forums among people who wanted to have it.

Regardless, it is blizzlike for that time-frame.

**Comment by panglaozhang** [comment]
but I,ve given GM a report in game, he think thats bug let me to report here for fix it...

**Comment by Godmatik** [comment]
It's likely the GM just wasn't fully informed. Keep in mind, they are not developers.

Anyway, I'm not an expert either on these things, I was just corroborating with what Cabro said above. A developer looks over these bug reports and determines if they are valid or not.

**Comment by panglaozhang** [comment]
k,got it

**Comment by DarkmoonRabbit** [comment]
看你角色名，国人么？-。-
加个QQ聊聊天，哈哈
2302520536

**Comment by Godmatik** [comment]
They ask that you use English in the issues tracker.

**Comment by brotalnia** [comment]
It is not a bug. Taurens could NEVER use normal raptors in Vanilla WoW. The only raptor they can ride is the epic ZG mount.

The race restrictions were removed all the way in the Wrath of the Lich King expansion patch 3.0.8.
http://web.archive.org/web/20160629214506/http://eu.battle.net/wow/en/game/patch-notes/3-0-8

> Racial restrictions on mounts have now been lifted. Night Elves on mechanostriders? Tauren on raptors? You’re not seeing things.
