### ISSUE TITLE
2FA removal

### ISSUE THREAD

**Issue by Hectelion** [LightsHope/issues#707]
Cant login, my account was Hectelion, registered with email antonio.mezzetti@gmail.com,
when try to use 2fa remove there's something to compile that I cant:
cant remember when I created my account, neither the login if I even have logged in, and probably I have no characters, so please remove my 2fa, or send me again a new valid qr code

**Comment by Godmatik** [comment]
The Github is for reporting bugs, not 2fa removal.

Try opening an in-game ticket (on a different account) or contact a GM on discord.
