### ISSUE TITLE
hello, l whisper to ot others l cant see it

### ISSUE THREAD

**Issue by ye47331714** [LightsHope/issues#709]
hello, l whisper to ot others l cant see it

**Comment by ye47331714** [comment]
ACCOUNT number jsl47331714  name guazi

**Comment by Godmatik** [comment]
You are muted, you need to open a GM ticket in-game, only they can help you. 

This Github is for reporting bugs, and GMs are not here.

**Comment by ye47331714** [comment]
I contacted GM but did not reply to me for two days

**Comment by Godmatik** [comment]
You'll just have to be patient and wait for your ticket to be answered mate.
You can also try contacting a GM on Discord.
