### ISSUE TITLE
Iron Deposit - chance of getting Heavy Stone too low

### ISSUE THREAD

**Issue by bugbringer** [LightsHope/issues#713]
Even if you don't accept vanillawowdb.com sources, I'll still link from there because the current state is also not correct. 

Vanillawowdb.com says 25% chance of getting 1-3 Heavy Stone per strike (https://vanillawowdb.com/?object=1735).

You can mine Iron Deposit 2-4 times - the average is 3 times. 

The chance of getting 2 Heavy Stone (average) is 100% after 4 Iron Deposit-strikes. 

Now, I striked 97 times Iron Deposit and it got me only 30 Heavy Stones - and I'm pretty sure that 2 Stones were from other sources (Chest, Mobs). 

https://imgur.com/a/XoP9HY2 - I shoud have 44 Heavy Stones + the 2 I got from other sources. 

Not even 2 stacks gg lightbringer bugbringer chinese teleport hack

**Comment by Gamemechanicwow** [comment]
Fyi Vanillawowdb uses the same DB as lh. Its maintained by a staffmember. 

Your samplesize is to low to give a clear indication, that the droprate is wrong. Imo.

**Comment by derekvcsr** [comment]
I have mined more than 300 iron ore but still have to buy heavy stone. My last total was below 50 heavy stone mined.
I have had to buy heavy stone because the drop rate is so low.

**Comment by QAkvastskaft** [comment]
#807
