### ISSUE TITLE
[24609] Furious Howl (Northdale)

### ISSUE THREAD

**Issue by Keftenk** [LightsHope/issues#715]
Furious Howl should not be available until Patch 1.7.
http://wowwiki.wikia.com/wiki/Furious_Howl

See Patch 1.7 Patch Notes:
"Hunter pets can now learn a maximum of four active abilities. Active abilities include Claw, Bite, Dash, Dive, Cower, Prowl, Screech, Scorpid Poison, Growl, and Furious How"

"Wolves can now learn Furious Howl. The howl adds a flat amount of damage to all nearby party member's next attack (within 15 yards)."

**Comment by Slicy** [comment]
Spells and mechanics are 1.12. 
Only raids/dungeons/events content and items are following a progressive pattern.

If that gets pushed and FW is removed until 1.7, then Shadowmeld's stealth should not cancel on cast starts but on casts ends.
