### ISSUE TITLE
Puissant Cape should not be added in 1.3.0

### ISSUE THREAD

**Issue by Cephel** [LightsHope/issues#729]
While scanning Azuregos loot with Atlas Loot on the server after 1.3 was patched in, we noticed the Puissant cape was able to be scanned. Talking to some other players we agreed that this most likely is not correct and set out to find evidence.

https://web.archive.org/web/20050913183446/http://wow.allakhazam.com:80/item.html?witem=18541 This shows the earliest scan of the item, dating to patch 1.7.0 - August 13th, 2005

http://wowwiki.wikia.com/wiki/Puissant_Cape <-- While not a credible source, lists "Patch 1.4.0 (2005-05-05): Added" under the item.

This corresponding line of the patch notes from 1.4.0 reads: "Onyxia, **Azuregos**, Lord Kazzak, and all Molten Core boss creatures have all **received some new items on their loot tables**." (http://wowwiki.wikia.com/wiki/Patch_1.4.0)

**Comment by Gamemechanicwow** [comment]
>https://web.archive.org/web/20050913183446/http://wow.allakhazam.com:80/item.html?witem=18541 This shows the earliest scan of the item, dating to patch 1.7.0 - August 13th, 2005

Look at the user comments. The oldest comments are from Mar 25 2005. Thats 18 days after the release of patch 1.3

Mar 27 - Talking about what just dropped.
Mar 28 - A player ninjalooted the cape.

**Comment by Cephel** [comment]
Good eye, can be closed
