### ISSUE TITLE
Stutter step animation bug after tauren lands from a jump.

### ISSUE THREAD

**Issue by dragons1** [LightsHope/issues#73]
The issue is tested with female tauren but several other taurens reported the same bug. It is visible to everyone in the game and 100% reproducible.

When a tauren performs jump animation with the default key Space, after the land there is a stutter step in the animation for the landing steps after the jump.
Simply jump with a tauren and watch his/her legs after it lands on the ground.

**Comment by Kittnz** [comment]
Thats more of a client issue which can't be fixed.
