### ISSUE TITLE
Lash of Pain being used from front

### ISSUE THREAD

**Issue by gotmilk0112** [LightsHope/issues#732]
http://classicdb.ch/?spell=21987

This ability is used by the lashers in DM East, and even though the description says that you must be behind the target, the lashers are still using it when they are in front of me.

**Comment by ratkosrb** [comment]
Fixed here https://github.com/lh-server/core/pull/199

**Comment by gotmilk0112** [comment]
Ah, nice.

**Comment by gotmilk0112** [comment]
Did this get implemented yet? Lashers are still using that ability from the front, even after maintenance.

**Comment by ratkosrb** [comment]
This has not been applied to LH live servers on today's update.

**Comment by gotmilk0112** [comment]
When will it be applied?

**Comment by Tobschinski** [comment]
With the juicy DME revamp I hope....

**Comment by Godmatik** [comment]
Still not applied =(

**Comment by gotmilk0112** [comment]
When is this going to be applied to live servers? It's been six weeks now.

**Comment by nxsofsys** [comment]
Hmm, its possible that this fix applies to warlock's succubus spell lash of pain? Now it says that succubus must be behind the target, but [https://wow.gamepedia.com/Lash_of_Pain](https://wow.gamepedia.com/Lash_of_Pain) says this requirement was removed in 1.1.0.
