### ISSUE TITLE
No one can see my Private chat

### ISSUE THREAD

**Issue by huanran2201** [LightsHope/issues#733]
So I can't team up    I'm troubled.
The server：Northdale
ID：Heguan

**Comment by Godmatik** [comment]
The GMs are the only ones who can help you, and they do not visit this Github, only developers come here to deal with bugs.

You'll need to open a GM ticket in-game and wait for one to contact you, in order to get your mute removed.

**Comment by huanran2201** [comment]
BUT they say
NOTE: Game Masters DO NOT handle bug reports!Please use our bugtracker and provide sources if possiblehttps://github.com/lightshope/server
For quicker casual support, visit our forumshttps://forum.lightshope.org/viewforum.php?f=9

**Comment by Godmatik** [comment]
It's not a bug though, the spamfilter the server uses automatically muted you, and it could be for a number of reasons.

Only a GM can remove that mute.

**Comment by huanran2201** [comment]
But I'm not in touch with GM now

**Comment by Godmatik** [comment]
Sorry I don't understand your last comment. 

You need to open a GM ticket in-game (red question mark button on your menu bar) and have to wait until it is responded.

**Comment by huanran2201** [comment]
![tim 20180801231712](https://user-images.githubusercontent.com/42002508/43530854-21f0411e-95e1-11e8-8550-7d027425ff5a.png)

**Comment by Godmatik** [comment]
You can ignore that, you still need to open a GM ticket. 

Only they can remove it 100%. It is not a bug, as I have stated. The same thing happened to me mate. I am just telling you, it is the only way you will be able for people to see your messages. A GM within the game has to remove it.

**Comment by huanran2201** [comment]
All right

**Comment by ratkosrb** [comment]
This is not a bug. Your character has been muted. Only a GM can help you.
