### ISSUE TITLE
Melding of Influence available too early

### ISSUE THREAD

**Issue by lazermon** [LightsHope/issues#736]
(Northdale)

The quest melding of influence (https://classicdb.ch/?quest=4642)
has the following quest text: "Here is some encased ooze created from the Felwood samples you recovered. Take the case to Un'Goro Crater and find a pure ooze... the primal variety will do nicely. When you get close enough, release the ooze in the case, and let us see what the two think of one another."

Despite this, the quest is currently possible to accept without completing "A Sample of Slime..." (https://classicdb.ch/?quest=4293), which is the quest where you collect ooze samples from felwood: https://i.imgur.com/pTxFsK2.png

It seems that at this moment, all that is required at the moment is to complete "... and a Batch of Ooze" (https://classicdb.ch/?quest=4294), which should obviously not be enough.

**Comment by ratkosrb** [comment]
Fixed here https://github.com/lh-server/core/pull/199
