### ISSUE TITLE
SM Npc Doesn't Attack when aggro-ed

### ISSUE THREAD

**Issue by thevipe** [LightsHope/issues#74]
Scarlet beastmasters in the dungeon scarlet monastery: Library bug out and do not attack you!
they just follow you and do nothing!

**Comment by thevipe** [comment]
ill run it again with this patch and see if it is still happening if so i will record a video to show it

**Comment by thevipe** [comment]
can you view the video  https://youtu.be/DoqgNlX37uU i set it as private

**Comment by GuybrushGit** [comment]
Weird, tested on dev and they worked fine.

**Comment by Kittnz** [comment]
Can you try release @GuybrushGit ?

**Comment by brotalnia** [comment]
All of the issues with ranged mobs standing around doing nothing will be solved once i am done migrating them to creature spells system.

**Comment by sipertruk** [comment]
Shouldn't scripts use the distance used for checking spell casts (Unit::GetCombatDistance) instead ?
It's happening here https://github.com/lh-server/core/blob/f2acf1a594a0400db6720f1ceffaee056a224b0c/src/game/AI/CreatureEventAI.cpp#L770
If a spell has a minimum distance which is logically used in the script there could be a gap where the mob won't move nor cast.

**Comment by brotalnia** [comment]
Timed, repeatable, in combat casts should not be part of the script. The spell should simply be part of the creature_spells template used by the mob. As i said in my previous comment on this issue, i am currently working on moving all caster mobs to this system, and they will all work perfectly when i am done.
