### ISSUE TITLE
DM Tank Itemization Error

### ISSUE THREAD

**Issue by zmandude24** [LightsHope/issues#742]
Force Imbued Gauntlets and Bulky Iron Spaulders give 3 less defense than they should in this patch.
http://classicdb.ch/?item=18383
http://classicdb.ch/?item=18493
These are both links to a 1.12 itemization database or after the blanket 33% nerf to the def on blues.
http://wowwiki.wikia.com/wiki/Patch_1.7.0

**Comment by ratkosrb** [comment]
Fixed here https://github.com/lh-server/core/pull/199

**Comment by zmandude24** [comment]
It's still wrong btw

**Comment by ratkosrb** [comment]
Did you build the branch from my pull request, and cleared your WDB folder before testing?
