### ISSUE TITLE
Paladin 35% dps nerf

### ISSUE THREAD

**Issue by AkOneVanilla** [LightsHope/issues#743]
After restart i try do lveling and i see less damage per hit , like from 198 dps ( Blessing of might  rank 5 and seal of the crusader rank 5) to 128 dps, that is to much and now if you are paladin on retribution . My game name Akone . Whats happened? Nerf or bug fix for Seal or the crusader?

**Comment by Gamemechanicwow** [comment]
Sounds like the SotC fix went live.

**Comment by Godmatik** [comment]
Seal of the Crusader was bugged and giving you more damage than intended. It increased your melee attack power and swing speed, but it wasn't reducing the power of each attacks as intended (like the tooltip says it should).

Looks like they finally fixed it.

**Comment by AkOneVanilla** [comment]
But from 160 dps only with blessing of might now i have 112 dps ....

**Comment by Cabro** [comment]
It never was meant as a dps seal. More like a weapon skill leveling skill. Google it.

**Comment by zmandude24** [comment]
I'd say it should have been kept in there to make ret pallys somewhat decent.

**Comment by Godmatik** [comment]
Project aims to be as Blizzlike as possible in vanilla :)

Sorry mate.

**Comment by zmandude24** [comment]
It would be a problem if they were on par or better than the standard dps classes as that would undermine the meta of vanilla, but making it so they do about 20-30% less than that without being broken in PvP is fine. Making a spec worthless because of incompetence at the time is bad game design.

**Comment by Godmatik** [comment]
Blizzard made a lot of poor game design decisions early on, and Ret pallies were not competitive in DPS. 

That's Vanilla for ya mate. Project still aims to be as close to it as possible.
