### ISSUE TITLE
Crimson Felt Hat should be available

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/issues#748]
https://web.archive.org/web/20060212073735/http://wow.allakhazam.com/db/item.html?witem=18727

Comments from before May 5th 2005 suggest that the item was implemented before patch 1.4.

**Comment by ratkosrb** [comment]
Release date for the patch on wowwiki is wrong.

https://github.com/brotalnia/ely-database/blob/master/new_progression/Patchnotes%20(ALPHA%20to%201.12.1).txt#L5904
> World of Warcraft Client Patch 1.4.0 (2005-04-19)

Allakhazam shows the item first being added on the day 1.4 was released.
https://web.archive.org/web/20060327085942/http://wow.allakhazam.com:80/db/itemhistory.html?witem=18727
> 2005-04-19 23:23:17 | Initial Entry

Also this item uses display id 31177 which does not exist in the game client prior to patch 1.4. Install WoW from the original disks, patch it to 1.3, extract the dbc files, and check for ID 31177 in ItemDisplayInfo.dbc and you'll see this model does not exist. Now patch your client to 1.4 and extract the file again and check that the model this item uses is among the newly added ones in the patch.

And if you read the 1.4.0 patch notes you will see this:
```
 - Stratholme Itemization 
 * 26 new Rare items have been added to Stratholme. 
```
This item is of Rare (Blue) quality and drops from Magistrate Barthilas in Stratholme.

Invalid issue.

**Comment by fgsfdss** [comment]
Interesting, good sources. Thanks for the elaborate response.
