### ISSUE TITLE
Oran's Gratitude is not working

### ISSUE THREAD

**Issue by pilarwow** [LightsHope/issues#752]
After you complete the escort quest Rin'Ji is Trapped! you get the quest Rin'Ji's Secret. You basically take the tablet you get and give to the npc Oran Snakewrithe in Undercity. After giving the tablet she was supposed to reward you with the quest Oran's Gratitude, but in this server i couldn't get it. You just finish the quest giving the tablet to Oran and then nothing, not a single quest prize.

**Comment by lazermon** [comment]
It's intentional, the quest is not in the game at this patch.

**Comment by pilarwow** [comment]
Oh,i see! Thank you
