### ISSUE TITLE
Betina Bigglezink is not giving you a new Dawn's Gambit when requested.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/issues#76]
You can select the dialogue option just fine, but you never obtain it in your bags. It used to work until a couple of weeks ago.

**Comment by GuybrushGit** [comment]
Condition 50407 has wrong type.

**Comment by brotalnia** [comment]
The script has wrong data_flags, that's why clicking the option does not give you the item.

`UPDATE `gossip_scripts` SET `data_flags`=0 WHERE `id`=50407;`

The condition is Quest Rewarded which seems to be correct based on Allakhazam comments.
https://web.archive.org/web/20071101052923/http://wow.allakhazam.com:80/db/quest.html?wquest=4771

> Does anyone know of a way to continuesly pick up more Dawn's Gambits. The reason I ask is because im interested in farming Vectus until he drops Skullsmoke Leggings. I have one but I am hestitant to use it especially in a pick up raid to scholo.

> Reply: After you complete the quest just talk to Dawn and she'll give you another.

**Comment by brotalnia** [comment]
Fix https://github.com/ratkosrb/server/commit/01f3272fcb32891e4a726a8a137c5e4c8cdb671d

**Comment by Bloodmoon-Darrowshire** [comment]
Betina Bigglezink still not giving you a new Dawn's Gambit when requested. (WDB folder was deleted 2 time) 
![gambit](https://user-images.githubusercontent.com/30354821/38293527-0b88d10c-3812-11e8-9230-e24e55b4bd86.jpg)

**Comment by brotalnia** [comment]
Unable to reproduce, works without issues after my commit. Please make sure you are running the latest development branch when testing bugs.
![wowscrnshot_040418_195501](https://user-images.githubusercontent.com/6519171/38322188-6266cbfc-3842-11e8-8c99-cdd3ebe8b865.jpg)

**Comment by Cabro** [comment]
It might work on dev branch, but on live server it hasnt worked for the last month or more.

**Comment by Bloodmoon-Darrowshire** [comment]
No. It not been fixed on today's maintenance... On live server still not working...

**Comment by brotalnia** [comment]
There's nothing left to do except wait for the commit to be pushed to live servers by thepparker.
