### ISSUE TITLE
[NOT a BUG] Loosing combo points after switching target

### ISSUE THREAD

**Issue by kaldown** [LightsHope/issues#766]
1) find target to attack
2) use sinister (get combo)
3) switch target (don't do anything, just switch)
4) switch target back (when combo were applied)
5) profit (there is no combo at all, even after you try to get "another" one)

clear wow client from kronos
no plugins

**Comment by Godmatik** [comment]
That is Blizzlike and intended. 

Combo points are per mob, and will clear if you switch to another target.

**Comment by kaldown** [comment]
CP are ONLY drops when you switch targets and do cp-apply actions on another target.
They MUST NOT drop on just switch.

**Comment by Tobschinski** [comment]
No, Sir!

2.0.3 (09-Jan-2007): Combo points added to a target should not be reset until you add a combo point to a different target.

1.4.0 (2005-05-05): Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected.

**Comment by kaldown** [comment]
Yeap. I'm sorry

Just now noticed this behave too.
https://youtu.be/40xcyujsfzM?t=298

Thanks.
