### ISSUE TITLE
4 people, who using botting program. + bonus

### ISSUE THREAD

**Issue by Payorbye** [LightsHope/issues#775]
Hello. I am fighting bots, which dishonestly sway until lvl 60.
Please look at the logs of these characters and make sure that they fraudulently allow to do such things.
Everything happens in the morning server time.
**Stabbybois** 5.08.2018 ruins of alterac 
**Unserjoerg** 5.08.2018 ruins of alterac
**Ratjones** 5.08.2018 arathi. hammerfall 
**Celerypeepee**  5.08.2018 arathi. hamerfall 
BONUS:
Play in a double window, or using someone's help WITHOUT A GROUP, to obtain a standard amount of experience. Also, a big request to remove this defect, which even on Kronos removed, and all who used it - went to the ban. This is very much prevents other players who are honestly trying to gain experience.
**Kiven** and **Eswind** 5.08.2018 ruins of alterac

**Comment by Godmatik** [comment]
The GMs don't visit this Github, it's only for reporting bugs.

You need to open a ticket in-game to report them.

To your "bonus", multiboxing outside of cities is not allowed. However, there is nothing against the rules by getting boosted by a friend/guildie/etc.
