### ISSUE TITLE
The Scepter of Celebras Quest

### ISSUE THREAD

**Issue by bteinert** [LightsHope/issues#779]
I am in Maraudon and accepted the quest "The Scepter of Celebras" at Celebras the redeemed and he has done nothing for 20minutes. We have waited here and he is supposed to create the scepter or allow us to speak with him but we are unable to interact with him and he is still standing in the same location that we killed him at. Please fix, our group is unable to obtain the scepter because of this issue.

**Comment by bteinert** [comment]
Character name is Zeedorf

**Comment by dumbstufftoreport** [comment]
that happened to me he sometimes bugs if you go back in with someone that has the staff and climb up the ramp on your right you can kill him again and it should work the next time you do it bro sorry to tell you fastest way to get it done

**Comment by Godmatik** [comment]
Confirmed, also happened to us.

Only way to fix is to reset the instance.
