### ISSUE TITLE
need a help 

### ISSUE THREAD

**Issue by ngs1989819** [LightsHope/issues#781]
Dear GM,
Hello, I am a player from Northdale. When I was sleeping, my account was maliciously stolen on August 7th and a lvl60 Tauren warrior named miyami was deleted from the account. A new troll warrior named miyami was created. But I was still asleep at the time. When I reacted, it has been 5 hours. I feel very sad and helpless.Can I get help from you? If you can, you can find another character miyala in the game or leave a message for me. Thank you so much

**Comment by brotalnia** [comment]
There are no GMs here. Github is for reporting bugs to developers. Try posting in the #support section on discord.
