### ISSUE TITLE
Cant log into server + 0 online shown on lighbringer and northdale

### ISSUE THREAD

**Issue by kaharas** [LightsHope/issues#785]
Is this a tecnical problem or it's just me?
is a mantainance thing?
if anyone has some info pls share
![whatsapp image 2018-08-08 at 12 08 30](https://user-images.githubusercontent.com/42205563/43831520-b4996fc2-9b04-11e8-9f4e-294ef56bb03f.jpeg)

**Comment by cbspcb** [comment]
in now

**Comment by Godmatik** [comment]
Servers were down for maintenance.

This happens every Wednesday morning.
