### ISSUE TITLE
Is this a joke? Piercing howl has been broken for over 1 month now

### ISSUE THREAD

**Issue by nacsdale** [LightsHope/issues#792]
Piercing howl is only applying to one target and it should aoe slow. Has been reported already and no progress ofc.

**Comment by Sabre142** [comment]
Fix it yourself.

**Comment by simonmathay** [comment]
Can confirm. Really annoying!

**Comment by ratkosrb** [comment]
Duplicate of https://github.com/LightsHope/issues/issues/604
