### ISSUE TITLE
Shadow Word: Pain not triggering Aspect of the Cheetah dazed effect

### ISSUE THREAD

**Issue by Solu9** [LightsHope/issues#793]
I've noticed that when applying Shadow Word: Pain on a hunter with Aspect of the Cheetah on, the daze effect does not trigger.
Furthermore when Shadow Word: Pain ticks damage the daze effect of Aspect of the Cheetah is not triggered either.

Both the cases above worked on Lightbringer, so unless evidence has emerged that it should not work, which seem unlikely, then Shadow Word: Pain (or Aspect of the Cheetah) is currently not working correctly.

**Comment by Godmatik** [comment]
Same with other Warlock DOTs. Also, initiating combat with DOTs against a target that eating/drinking won't break them out of it. Unsure if intended or not.

**Comment by uhdx** [comment]
It's not supposed to, only direct damage is supposed to daze the hunter.
as far as dots not stopping eating/drinking targets, thats a bug

**Comment by Solu9** [comment]
I find that hard to believe when the description of Aspect of the Cheetah is: "The hunter takes on the aspects of a cheetah, increasing movement speed by 30%. **If the hunter takes damage**, he will be dazed for 4 sec. Only one Aspect can be active at a time."

**Comment by Cabro** [comment]
Just like dots don't interrupt flag capping, but wand attacks do. Doesn't look like a bug to me.

**Comment by Solu9** [comment]
After having looked for any clues you seem to be correct. I can't find any official documentation on the matter, but other servers have "fixed" issues where hunters got dazed by dots. So if that is any indication then Aspect of the Cheetah works as intended (as if hunters are not op to begin with, amarite)

**Comment by Solu9** [comment]
Actually. I dunno if this has any value, but it appears as if hunters actually are supposed to get dazed until AQ patch.
http://wowwiki.wikia.com/wiki/Patch_1.9.0 -> "Aspect of the Pack and Aspect of the Cheetah - Periodic damage will no longer trigger the Dazed effect."

**Comment by Godmatik** [comment]
Then it's working as intended.

This server's spell and talent database are based on patch 1.12.1, they aren't progressive and changing with each patch similar to quests and items.

**Comment by bladezLH** [comment]
Working as intended
