### ISSUE TITLE
Event "Love is in the Air" is broken #2

### ISSUE THREAD

**Issue by Bloodmoon-Darrowshire** [LightsHope/issues#8]
NPC [Morgan Pestle](http://web.archive.org/web/20071106121715/http://wow.allakhazam.com:80/db/mob.html?wmob=279) must give this quest: Morgan's Discovery (http://vanillawowdb.com/?quest=9025) after this quest: Aristan's Hunch (http://vanillawowdb.com/?quest=9024). [Aristan Mottar](http://web.archive.org/web/20071117132647/http://wow.allakhazam.com:80/db/mob.html?wmob=16105) must start players to next quest chain:
 - Tracing the Source (http://vanillawowdb.com/?quest=9026)
 - Tracing the Source (http://vanillawowdb.com/?quest=9027)
 - The Source Revealed (http://vanillawowdb.com/?quest=9028)
And in the end you need to click on cauldron:
 - A Bubbling Cauldron (http://vanillawowdb.com/?quest=9029)

Prof:
 - http://classicdb.ch/?quest=9029
 - http://vanillawowdb.com/?quest=9025
 - http://web.archive.org/web/20071117132647/http://wow.allakhazam.com:80/db/mob.html?wmob=16105 (see date of comment)
 - https://wow.gamepedia.com/index.php?title=Quest:Morgan's_Discovery&direction=next&oldid=501587

**Comment by GuybrushGit** [comment]
This is working I just did it.

**Comment by Bloodmoon-Darrowshire** [comment]
My bad.Need to delete  WDB folder after fix.
