### ISSUE TITLE
Quest items not registering properly

### ISSUE THREAD

**Issue by strahinjamilic** [LightsHope/issues#802]
Hi,i have a problem with the quest The ledger from Tanaris.I have all the items needed to complete the quest but the quest giver doesnt register it(quest log does).As far as i could find out this is not isolated just to this quest cause some people had similar problems with Armorsmithing quests etc...(multiple quest items and not all registering server side).If i wasnt clear,or if a picture is needed feel free to write to me in-game(Sellexi@Northdale)Thanks for your time,and keep up the good work :D

**Comment by Godmatik** [comment]
It's an old bug and affects all quests, it occurs if you delete excess quest items from your bag.

Only solution is to abandon and retake the quest.

**Comment by strahinjamilic** [comment]
Damn,what a quest to learn about the bug.Thanks for the info though :D
