### ISSUE TITLE
Cadaverous Worm

### ISSUE THREAD

**Issue by lazermon** [LightsHope/issues#808]
Cadaverous worm (https://vanillawowdb.com/?npc=14370) is an npc which spawns when a Rotting Highborne (https://vanillawowdb.com/?npc=11477) is killed.

Some incorrect database entries were submitted during vanilla, which translated into stock mangos giving certain mobs a loot table which they definitely shouldn't have. This is one of these examples.
Depending on which time you go back to, Allakhazam shows up to 24 (incorrect) loot entries from this mob. This can be compared with Rotting Highborne (which will always spawn the Cadaverous Worm on death), which has 28159 entries in the database. Had the worm actually dropped loot, the amount of entries for each of these ought to be roughly the same, this is evidently not the case.

To add to the suspicion, the worm has an abnormal drop rate of Star Ruby (18% on lights hope), an item that ought to have a world drop rate of roughly 0.09%.
http://web.archive.org/web/20070115111834/http://wow.allakhazam.com:80/db/item.html?witem=7910
(Take a look at the amount of submitted entries for each mob, an amount lower than 100 is extremely rare)

Rotting Highborne: http://web.archive.org/web/20060720203712/http://wow.allakhazam.com:80/db/mob.html?wmob=11477
Cadaverous Worm: 
http://web.archive.org/web/20060415085240/http://wow.allakhazam.com:80/db/mob.html?wmob=14370

**Comment by ratkosrb** [comment]
Fixed here -> https://github.com/lh-server/core/commit/688b696d780b2e1ad5287c7262497709486d6380
