### ISSUE TITLE
Why does Eviscerate miss 50% of the time?!?!

### ISSUE THREAD

**Issue by jmin213** [LightsHope/issues#812]
Dear LightsHope,

I'm currently leveling an undead rogue on Northdale PVP server. This server is excellent for me, except for one key issue. Eviscerate misses about 50% of the time. What the heck?! Please take a look into this and fix it. Thank you.

**Comment by Godmatik** [comment]
Working as intended and anecdotal nonsense unless you provide a lot more details, along with data backup.

I could come on here and say "WTF MY FROSTBOLT JUST RESIST 3 TIMES IN A ROW, FIX IT!", but that doesn't mean there is a bug. High miss rates are very common for melee in Vanilla, especially during leveling.
