### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by HotFrog2** [LightsHope/issues#816]
Good afternoon!!!
I have a problem: why all the sets of m1 and m2 look quite different in the game
For example, the paladin set of the Judge's Armor looks like an ordinary brown set
Seth Felcloth robes looks like normal starting rags
All sets starting from t1 and ending with sets of Naxxramas look wretched
Is there a problem with the game files?
Help me please. I can not see

**Comment by Godmatik** [comment]
This is intentional, the sets were not updated until a later patch, and we're only on 1.3.

**Comment by ratkosrb** [comment]
https://imgur.com/a/HcFjZ
