### ISSUE TITLE
Character crashes WoW client every time. 

### ISSUE THREAD

**Issue by sgjrealtor** [LightsHope/issues#821]
Character crashes WoW client every time. I can log on to every other character, but one. Lvl 5 Gnome rogue Focuss on Northdale server. I have changed clients 3 times and it still crashes it. Something about that character and that location. How can I fix it?

**Comment by ratkosrb** [comment]
You need to open a ticket from another character, and ask a GM to teleport the bugged character to a safe location.

**Comment by sgjrealtor** [comment]
The problem I have with that is that it shows that GM tickets are unavailable?

**Comment by ratkosrb** [comment]
Wait until they are available.

**Comment by Godmatik** [comment]
Also, the problem will keep happening, you probably need to install a fresh client, the one you have is corrupt.

**Comment by sgjrealtor** [comment]
3 rd client and it doesn’t happen on any other character


> Stephen James
> 
> Affiliate Broker | Keller Williams Realty
> 3860 Forest Hill Irene Rd | Suite 105 | Germantown | TN | 38125
> c:662-689-1299 | o: 901-221-5100 | sgjrealtor@gmail.com

**Comment by Gamemechanicwow** [comment]
Are you using a Mac and is it happening south of kharanos?

https://github.com/LightsHope/issues/issues/579

If thats the case, the only solution is getting a gm to port you. If you cant open a ticket, you could also try to login right after a reset. Some ppl say that works too.

**Comment by sgjrealtor** [comment]
That is exactly where it is! And yes I am on a Mac! I have had no luck contacting a GM so I guess a reset is what I look forward to. Thank you! 

> Stephen James
> 
> Affiliate Broker | Keller Williams Realty
> 3860 Forest Hill Irene Rd | Suite 105 | Germantown | TN | 38125
> c:662-689-1299 | o: 901-221-5100 | sgjrealtor@gmail.com

**Comment by smlax** [comment]
Have you tried disabling all addons and logging in?  That solved the issue when it happened to me once or twice.  I may have also deleted the data for the account/character in the WTF folder, can't remember.

**Comment by Godmatik** [comment]
That will not help him.

The MAC client has a corrupt file for a specific area in Kharanos. The issue is client-side and nothing can be done unless someone fixes it and release a new client.
