### ISSUE TITLE
Bug with Journeyman Riding Skill?

### ISSUE THREAD

**Issue by deathkil27** [LightsHope/issues#822]
I've purchased Journeyman riding on my rogue along with a Pinto Horse. I cannot use the horse however. Even though I've purchased the riding skill? It still say's in red text, I require Riding (75)

In game name is Duncanjax

**Comment by Falstring** [comment]
I suggest you clear your cache and restart the game.

Pretty sure this is a clientside bug.

**Comment by Godmatik** [comment]
Close out your game and delete the WDB folder.

**Comment by deathkil27** [comment]
The WDB solution worked, thanks mates!
