### ISSUE TITLE
Savage Gladiator Chain should have defense reduced in 1.7

### ISSUE THREAD

**Issue by zelazrgn** [LightsHope/issues#84]
https://web.archive.org/web/20060508233655/http://wow.allakhazam.com:80/db/item.html?witem=11726

> Posted @ Wed, Mar 29th 12:11 PM 2006
> new stats after patch 1.10=+13 stam,+14 agi,+13 strength
> still 2% to crit but lose the+13 defense

The item stayed at 20 defense.

Considering 1.10 is almost out, seems like a good time to finally make this issue.

**Comment by QAkvastskaft** [comment]
Should be reduced from 20 Def -> 13 with patch 1.7 due to the Def nerf
http://wowwiki.wikia.com/wiki/Patch_1.7.0
