### ISSUE TITLE
Single target CC abilities can be applied to several targets

### ISSUE THREAD

**Issue by Slicy** [LightsHope/issues#843]
Single target CC abilities like Polymorph, Fear are now able to be cast on several targets. These aren't meant to be applied to more than 1 target at the same time.

Example : Mage A cast Poly on target B then on target C. Both B & C will be polied. B should get out of poly as soon as C is polied.

**Comment by ratkosrb** [comment]
Cannot reproduce.
https://streamable.com/7gzat
https://streamable.com/qxk1o

**Comment by Stunlocked** [comment]
can confirm https://www.youtube.com/watch?v=M7IeaPEA1Co 
Shows me as a rogue sapping 2 targets then 3 targets after.

**Comment by Kolmarwow** [comment]
i can confirm this is how it works at the moment on the live servers. i just went into the searing gorge and starting polymorphing the spiders there and got 5 polymorphs at once. so it looks like i can roleplay as a sheep herder now.

**Comment by Godmatik** [comment]
Confirmed as well, appears to be a recent new bug.

**Comment by Cabro** [comment]
Maybe it is only bugged on players, but works on NPCs?

**Comment by ratkosrb** [comment]
Should be solved on LH live servers now.
