### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by Bloodcrusade** [LightsHope/issues#844]
I am unable to log in. For about the last week, every time I attempt to log in, it says connecting for a minute and then says disconnected from server. I have made sure I can log onto lights hope and all of that and made sure my account wasn't hacked to cause a ban but no luck. I am not sure what is wrong but I can no longer get in game.

**Comment by Godmatik** [comment]
Either your realmlist isn't setup properly, or you have a corrupted client and need to start over with a fresh one.

**Comment by Bloodcrusade** [comment]
I have been playing for a while now, it only started doing this a week or so ago.

**Comment by Godmatik** [comment]
Then your client got corrupted somehow, you'll need to start over with a fresh one.
