### ISSUE TITLE
Improved Power Word: Fortitude rank 2/2 Not working

### ISSUE THREAD

**Issue by angrypriest** [LightsHope/issues#849]
Power Word: Fortitude rank 3 Tooltip displays: "Power infuses the target, increasing their Stamina by 26 for 30 min" but once applied the buff reads "Increases Stamina by 20"

**Comment by Godmatik** [comment]
The tooltip will not reflect the talent change, but it still gives you the increased stamina when used. Same goes for any other talents that improve your buffs.

This is how it was in Vanilla.
