### ISSUE TITLE
Seal of the Crusader- bugged?

### ISSUE THREAD

**Issue by Shibester** [LightsHope/issues#850]
Seal of the Crusader seems to be wrong. It does in fact increase attack speed and power, but 
the tool tip reads that overtime it will do less and less damage; but right now currently it lowers 
immediate damage, and it gets worse from then on. 

Normally on other servers including Nost, etc. you would get an immediate damage boost which would
lower over the course of the consecutive melee hits- can this be addressed?

**Comment by Godmatik** [comment]
You misread the tooltip, it doesn't mean it gets progressively work with each attack, it means that each attack deals less damage than normal without the seal being used. It was bugged on previous Nost projects and was fixed a few weeks ago. Working as intended.
