### ISSUE TITLE
Gnomish Cloaking Device not working

### ISSUE THREAD

**Issue by bugbringer** [LightsHope/issues#858]
https://youtu.be/g8Nr3RpUE0w?t=1m21s

as you can see in the vurtne 3 movie, gnomish cloaking device provides you invisibility and the option to stay invisible while setting up a cast.

its not like this on northdale

**Comment by Sylvatir** [comment]
I believe it was nerfed in a later patch before 1.12.1, as a gameplay feature it required fixing, as you can see from the video.

**Comment by bladezLH** [comment]
It is in fact already working like this
