### ISSUE TITLE
Rescue From Jaedenar

### ISSUE THREAD

**Issue by slaskeren** [LightsHope/issues#860]
After accepting quest from Captured Arko'narin, she wont move, she just sit`s in her cage.
I have tried abondon / retake the quest alot of times, and nothing new happens.

this is a video of retail ( i assume ) but i believe this is how the quest/escort should be like
https://www.youtube.com/watch?v=V3dId_-OLwU

**Comment by Godmatik** [comment]
Confirmed, she constantly bugs out.

**Comment by QAkvastskaft** [comment]
#512
