### ISSUE TITLE
druid not getting mana/hp from levelup stats

### ISSUE THREAD

**Issue by Gyronell** [LightsHope/issues#861]
Hello just started a night elf druid and turns out I'm not getting health/mana from the stats I get from leveling.

what I started with at lvl 1: 52hp/67mana
level 2 granted 9 hp and 55 mana as well as 1 str 1 stam 1 int and 1 spirit
what I ended up with at lvl 2: 61hp/122 mana 
level 3 granted 17 hp and 23 mana as well as 1 agi 1 int and 1 spirit
what I ended up with at lvl 3: 78hp/145 mana
level 4 granted 17 hp and 24 mana as well as 1 str 1 stam 1 int and 1 spirit
what I ended up with at lvl 4: 95hp/169 mana
level 5 granted 17 hp and 25 mana as well as 1 agi 1 int and 1 spirit
what I ended up with at lvl 5: 112hp/194 mana

As you can see I'm only getting the health and mana bonus from the increase stated but not from the stamina and intelligence I get and I assume this goes on all the way to 60.
I did notice an increase in mana regen though so spirit seems to work correctly, however I did not check if agility and strength was doing what it's supposed to.
hope this helps and gets fixed sooner rather than later :)

**Comment by bladezLH** [comment]
See https://www.reddit.com/r/lightshope/comments/8ttmfp/stamina_not_increasing_hp/e1b9z1z/
