### ISSUE TITLE
Missing Character Frame 

### ISSUE THREAD

**Issue by Aernasun** [LightsHope/issues#865]
Dear the Development Team!

First big thank you, your hard work! I have a little problem, whit my game. This problem is, my Character, and target frame is missing. Plus, i have a second chat bar, and i can't delete, ore move it! Can you help me?

![wowscrnshot_082718_150431](https://user-images.githubusercontent.com/42741003/44661482-15afb900-aa0b-11e8-9a0a-caac67d9ffda.jpg)

Thank You!

**Comment by Godmatik** [comment]
One of your addons is causing the issue.

**Comment by Aernasun** [comment]
Thank You, my Icehud is the problem!

**Comment by Aernasun** [comment]
But the second Chat bar it's still there.

**Comment by Godmatik** [comment]
That looks like your Combat log, you can drag it so that it's a part of the first one, just on a separate tab

**Comment by Aernasun** [comment]
I tried but can not move.

**Comment by Godmatik** [comment]
Right click the tab and make sure it is unlocked so you can move it.

**Comment by Aernasun** [comment]
I deleted my all addons, then reloaded the game, finally its working! Thank you for the help! 
It looks like old addons hide big errors.
