### ISSUE TITLE
Character BUG

### ISSUE THREAD

**Issue by Nonnazor** [LightsHope/issues#867]
my client wow crashed with my second chart in server Northdale in alliance his name is Nonnazor mage human lvl 33 is bug in a place of Forjal. Dun Morogh
I am here for talk with a GM plz teleport a save place.
 
mi cliente de wow se cierra con mi segundo PJ en el server Northdale alianza nombre Nonnazor mago humano lvl 33 esta bug en un lugar de Dun Morogh.
escribo por aqui para hablar con un GM y lo teletransporte a un lugar seguro

**Comment by Godmatik** [comment]
GMs are not on this Github, you need to open a ticket in-game on another character.
