### ISSUE TITLE
Starshards - 1.4.0 Patch Changes

### ISSUE THREAD

**Issue by tommyb233** [LightsHope/issues#869]
First of all, thank you for taking the time to report this issue.

Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster. They may redirect you to this
bug tracker if they believe there's a server issue that they cannot help you
with.

Before writing your report, please do read and consider the following points to
increase the quality of your report.

Search the issue tracker for open and closed issues before opening a new
issue. You may be able to contribute additional facts by commenting on
existing issues instead of adding extra noise in a separate issue.
http://www.wowhead.com/ and http://db.vanillagaming.org/ are not valid sources
for quests, items etc., instead, please use archived versions of
http://wow.allakhazam.com or http://www.thottbot.com through
https://archive.org/.
Validate the date and time of the archived sources to a certain patch. The
patch release dates can be found on the corresponding WoWWiki article, as
found at http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_patches.
Videos are valid if and only if the footage contains a timestamp or
information that confirms the time it was recorded. Date of upload is NOT
valid and does not confirm when it was shot.

Once you've read this message, delete it and write your report below.

--

Hi, I've been experimenting with the lack luster NE priest spell "Starshards" on Northdale.  After researching why this spell was ever created, it looks like it went through some changes and eventually removed in later expansions.  However, I noticed in the 1.4.0 patch notes that "Force of Will" talent (and others) now impacts the spell, but presently I've never seen the spell crit.

I believe the issue is that it is considered both a dot and channeled spell - DOTs do not crit in classic wow.   This make sense with instant cast warlock DOTs, and certainly isn't a drain spell.  It looks like this was resolved in TBC as they changed it to a true DOT.  However, since this is classic, does it make sense to change it to a true channeled spell thus able to crit and affected by the appropriate talents and gear?  Removing the DOT component also prevent taking up one of the 8 debuff spots as well, which is important given how low dps a skill it is.

As it stands now, it is essentially a useless skill assuming you even finish casting.  With the ramped up damage, getting hit causes you to lose later larger damage ticks thus making it even less DPS and DPM.  I believe another classic server fixed this by making it even over the coarse of casting, but this is a bit past the point of this post/fix (able to crit and be affected by associated talents).  Appreciate any review or thoughts.  As the spell stands now, I don't see any reason to ever purchase later versions - might need to reroll to a dwarf priest given how OP that racial is :)

Thanks!

**Comment by Gyronell** [comment]
Force of Will: Increases your spell damage by 1% and the critical strike chance of your offensive spells by 1%.
I'm afraid that just means it now benefits from the spell damage increase part, not the crit.

**Comment by Godmatik** [comment]
Starshards not critting is intended in Vanilla.

It's a lackluster skill, very much agreed, but that's how it was...

**Comment by tommyb233** [comment]
Ah, I'm dumb - just focused on the crit part and got confused and stuck on that.  Thanks!
