### ISSUE TITLE
The mission 'Ivar the Foul'

### ISSUE THREAD

**Issue by Super-Mouse** [LightsHope/issues#870]
HI，
I'am doing the mission 'Ivar the Foul' which happened in the north of the Silverpine Forest . It makes me get the head of Ivar. 
But, when i kill the Ivar, there is no quest item i need. Even if i get the misson again, it is still like this.
Please help me. Thanks!

**Comment by Godmatik** [comment]
Are you in a raid?

**Comment by Super-Mouse** [comment]
of course not

**Comment by Super-Mouse** [comment]
thanks, i did in a raid.....
