### ISSUE TITLE
Mark of the Wild Rank 5 only increasing armor 195 instead of 263, attributes and resistances also buffing lower than supposed to be.

### ISSUE THREAD

**Issue by Dinkerbell** [LightsHope/issues#876]
Mark of the Wild is only increasing armor by 195 instead of 263, attributes by 8 instead of 10 and resistances 10 instead of 13.   I was told to delete my WDB folder after closing my client and it seems to have worked but the icon in the corner is still telling me the increase is 195, which is also bizarre because no rank has those same numbers .

**Comment by Godmatik** [comment]
This is blizzlike, the buff icons do not reflect the increases you get from talent points spent, in this case, improved mark of the wild from the resto tree. But the increased stats are there on your character.
