### ISSUE TITLE
Greater Intellect pots are bugged

### ISSUE THREAD

**Issue by Tabletopcheese** [LightsHope/issues#888]
Greater intellect pots are providing no stat increases.

Should give 25 int. 

Gives nothing.

**Comment by Tabletopcheese** [comment]
correction, is not stacking with INT buff

**Comment by dinsfireyo** [comment]
they are not supposed to stack did u even ask around before saying its a bug

**Comment by Tabletopcheese** [comment]
oi ya not a friendly cunt
