### ISSUE TITLE
Elune Stone erroneously creates an attackable light source object which also attacks you back.

### ISSUE THREAD

**Issue by Neejrow** [LightsHope/issues#89]
Elune Stone is spawning an attackable level 1 object called 'Spotlight' (which also attacks back when attacked)

Screenshots attached of the Spotlight attacking me and being attackable when I place it. This is not like vanilla retail. You were never able to see an attackable 'Spotlight' and kill it. This makes Elune stones completely useless, they were considered a special item because it takes 1 day to make 1. And anyone can instantly kill it as soon as you place it.

![spotlight_spawn](https://user-images.githubusercontent.com/30435596/37100857-29dd4e44-2278-11e8-8156-e1a0fba474a2.jpg)
![spotlight_attack](https://user-images.githubusercontent.com/30435596/37100858-2a1938f0-2278-11e8-8a34-82ea110d6d2c.jpg)
![spotlight_kill](https://user-images.githubusercontent.com/30435596/37100859-2a4cf546-2278-11e8-96bf-70506a453553.jpg)

**Comment by Cabro** [comment]
Yea it shouldn't be targettable as NPC and should not be affected by aoe.
