### ISSUE TITLE
Beasts are able to parry

### ISSUE THREAD

**Issue by Sylvatir** [LightsHope/issues#897]
Wasn't a thing.

**Comment by Kittnz** [comment]
any proof?

**Comment by dinsfireyo** [comment]
Yeah lets gimp a massive amount of mobs of the mobs in the game because "omg how does a bear parry?". I think u are comparing the game to real life and thats ur only reason for claiming this

**Comment by femdead** [comment]
stock mangos scripting, everything can parry even totems

**Comment by Kittnz** [comment]
it's not called stock mangos scripting. It's just a creature like anything else with default combat.

**Comment by Cabro** [comment]
Beasts should be able to parry. Check Joana's videos for leveling, the scorpids in Durotar can parry.
LE: not sure about totems.

**Comment by Gamemechanicwow** [comment]
Why do ppl still make bugreports like this....

https://vanilla-twinhead.twinstar.cz/?issue=4987 <- tons of vanilla footage of beasts parrying (or just google “beasts parry vanilla”... there is actually ppl out there that did some research)

Totems shouldnt parry on lh servers.
https://github.com/lh-server/core/commit/3eb5db1b7973201d12b14b4d2e197e90f591bb0d
