### ISSUE TITLE
Thunderclap only works in Battle Stance

### ISSUE THREAD

**Issue by jgsaulsbury** [LightsHope/issues#898]
Hi devs, 
In vanilla Wow, warriors' Thunderclap worked in both Battle Stance and Defensive Stance, and was central to a typical tanking rotation. Currently (at least in my game) Thunderclap only works in Battle Stance. Allakhazam doesn't list the stances in which spells work, so I can't cite that as a source, but [wow.wikia.com lists it as being castable in Defensive Stance](http://classic-wow.wikia.com/wiki/Thunder_Clap). Not having Thunderclap is a big handicap as a tank, so I greatly appreciate your efforts to resolve this. 
Thanks!

**Comment by Godmatik** [comment]
Thunderclap always was only usable in Battle Stance during vanilla, was not changed until Burning Crusade. This is working as intended.

EDIT - Source:

http://wowwiki.wikia.com/wiki/Thunder_Clap

Patch 2.0.10 (2007-03-06): "Thunder Clap" is now useable in Defensive Stance. In addition, the tooltip has been adjusted to indicate it causes additional threat.
