### ISSUE TITLE
Incorrect directions from guards in Ironforge

### ISSUE THREAD

**Issue by Offroads** [LightsHope/issues#9]
If you ask a guard for directions in Ironforge he will give you incorrect directions. Sub-sections appears to be pointing to the options on the first menu with the corresponding index.
As an example I went through the options in the profession trainer menu.
The class trainer menu also seems to be selecting from the first menu as well the same way that the profession trainer menu does. 

1. Alchemy -> AH
2. Blacksmith -> Bank
3. Cooking ->Tram
4. Enchanting -> Flightpath
5. Engineering -> Guild
6. First Aid -> Inn
7. Fishing ->Mailbox
8. Herbalism -> Stable master
9. LW -> Weapon master
10. Mining -> Battlemaster
11. Skinning -> Opens options for class trainers in IF.
12. Tailoring -> Opens options for profession trainers.

**Comment by sipertruk** [comment]
The same happens in all cities.

**Comment by sipertruk** [comment]
Fixed now, as well as #10
