### ISSUE TITLE
Overlord Wyrmthalak

### ISSUE THREAD

**Issue by Machika123** [LightsHope/issues#907]
Hey, i killed Overlord Wyrmthalak yesterday. And he did not drop the General Drakkisath's Command wich starts a quest for a valuable trinket. please help
Link is a screen picture that shows ive killed him for a quest called "Warlord's Command"
https://imgur.com/W3oTCb5

**Comment by Godmatik** [comment]
Were you in a raid group? 

It only drops if you are not, you need to run it as a 5 man.

**Comment by Godmatik** [comment]
That item only drops for Alliance.

https://vanillawowdb.com/?item=12780#starts

As Horde, you only need to continue the chain after finishing "Warlord's Command", which has you defeat Rend, then you get your trinket.

https://vanillawowdb.com/?quest=4974

**Comment by Machika123** [comment]
i did it as 5man

**Comment by Machika123** [comment]
Thanks tho, i asked some ppl and they said it dropped from him. first time playing horde thats why
