### ISSUE TITLE
Hunter Talent "Pathfinding" not working

### ISSUE THREAD

**Issue by Vents** [LightsHope/issues#909]
The hunter talent "Pathfinding" on the Beast Mastery tree doesn't seem to be working.
It is supposed to increase the walking speed percentage of your Aspect of Cheetah and Aspect of the Pack by 3% or 6%, depending on the number of points that you had spent on it.
I have put 2 points on that talent but it still says "movement speed increased by 30%" when it should say "movement speed increased by 36%".
![img01](https://user-images.githubusercontent.com/35167703/45177642-e444a380-b1e9-11e8-9a02-c9b4e5d0269f.jpg)

**Comment by Gyronell** [comment]
doesn't mean it's bugged, you're still getting 36%. It's the same when you get improved mark of the wild or improved power word fortitude, the buff will still say the original value.

**Comment by Godmatik** [comment]
This is blizzlike. The buff icon does not reflect any talent changes you have made, however you are still getting the 6% extra speed increase. This is how it was in vanilla.
