### ISSUE TITLE
Windfury Totem proc: combat log issue

### ISSUE THREAD

**Issue by hedgefund** [LightsHope/issues#91]
In retail vanilla when you would get a Windfury Totem proc as a result of say, Hamstring, your combat log would read like this:

```
You gain 1 extra attack through Windfury Totem.
You hit PoorGuy for 574.
You gain Windfury Totem.
Your Hamstring crits PoorGuy for 93.
Windfury Totem fades from you.
```

But in LH the first line that notifies you of the extra attack is missing. As a results several addons don't detect extra attacks properly.

The combat log message that notifies you of extra attacks can be seen in this video at the linked time: https://www.youtube.com/watch?v=ISx6eni6I1k&feature=youtu.be&t=15m21s

**Comment by GuybrushGit** [comment]
He does the cast animation in that video. Checked another video and the same thing happens: https://youtu.be/NAqnho4LOnM?t=518

**Comment by hedgefund** [comment]
You're correct, I completely missed it since it's drowned by other animations but I watched it again (the George video) and I can clearly see him doing it now :flushed:. I must have mixed it up with the TBC version of Windfury Totem or somesuch. I will edit it to only contain the combat log issue.
