### ISSUE TITLE
Elemental Fire drop rates bugged on certain mobs?

### ISSUE THREAD

**Issue by birdyy2** [LightsHope/issues#911]
I've been farming blazing elementals and magma elementals in Searing gorge for the last hour.. killed well over a hundred at this point... I'm trying to farm elemental fires which according to multiple sites including vanillawowdb (says its set to patch 1.3 and is maintained by lightshope community) states it should have an 8% drop rate on these two mobs.... I've killed well over a hundred in the last hour and have yet to recieve a single drop... not sure if bugged or just bad luck? or the db lying to us?
https://vanillawowdb.com/?npc=5855
https://vanillawowdb.com/?npc=5850

**Comment by Godmatik** [comment]
Just RNG mate, you got unlucky. I've also been farming them an hour or so before our raid start time, and have a decent drop rate. Once I got 3 dropped in a row.
