### ISSUE TITLE
Lost item.

### ISSUE THREAD

**Issue by Machika123** [LightsHope/issues#912]
While mixing with my gear with the outfitter addon i had vendor tab open and it accidently sold my trinket Carrot on a stick. i noticed this a few hrs later when it was to late to retrive the item from the vendor. pls help

**Comment by Godmatik** [comment]
Open a GM ticket in-game. They may be able to recover it, but no guarantees.

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue there and a GM will assist you as soon as possible.

Thank you
