### ISSUE TITLE
Commander Gor'shak Quest

### ISSUE THREAD

**Issue by bugges234** [LightsHope/issues#916]
Can't get Commander Gor'shak from Galamav the Marksman.

 I finished 

-Disharmony of Flame

I am able to accept 

-Disharmony of Fire and The Last Element    both need Disharmony of Flame to be completed just like Commander Gor'shak.

**Comment by Godmatik** [comment]
You need to complete the 2nd "Disharmony of Flame" before Commander Gor'Shak quest opens up.
