### ISSUE TITLE
I never get Warchief's Blessing

### ISSUE THREAD

**Issue by Scorpiore** [LightsHope/issues#924]
Hey
I never get the buff. I has happened like 7 times now where everyone around me get the buff, but I don't. I tried talking to GM's and they led me here! My toon's name is Galing. Lvl 20 priest.
Keep up the good work!

Regards

**Comment by Godmatik** [comment]
You need to have at least Friendly reputation with Orgrimmar to receive the buff.

EDIT: It might be Honored. Regardless, it's one of the two. I'm guessing you're an undead priest.
