### ISSUE TITLE
hunter pet bugged

### ISSUE THREAD

**Issue by zygosa151** [LightsHope/issues#928]
hey, so the issues is about the defensive stance

when i'm playing solo it's working fine, when i pull a mob my pet goes for it.
but when im in dungeon or simply in a group and i'm not the one pulling and taking aggro first, my pet stay's next to me like in passive mod.

**Comment by Godmatik** [comment]
Working as intended. It only attacks if you personally have aggro on a mob while in defense stance, not when someone else has aggro.
