### ISSUE TITLE
Archivist Cape Values not updated with patch?

### ISSUE THREAD

**Issue by harrydotter** [LightsHope/issues#930]
So the Archivist Cape's generated a fixed value of 14 when a spell damage type comes up and that was improved to 21 with the patch however the cape in my inventory did not update
I am aware that the green boe's didn't have their values updated because these values were random but the random part of the Archivist Cape was the type of damage and not the stat value itself
I believe it is an error that the item does not update automatically to 21 with the patch and was directed to post this here by a GM

Can this be corrected?

Thanks for your time!

**Comment by Godmatik** [comment]
All random spell damage afflixes stayed at their same values, both greens and blues, only higher ones drop going forward. Fairly sure this is intended.

**Comment by QAkvastskaft** [comment]
This is intended
