### ISSUE TITLE
Help Wild Leather Vest Quest Bug

### ISSUE THREAD

**Issue by Orisio** [LightsHope/issues#933]
Hello, for some reason I can't finish my Wild Leather Vest Quest I have material and armors to finish the quest but continue button stays gray without vest I can't continue other leatherworking quests such tribal leatherworking

![can t continue](https://user-images.githubusercontent.com/43246942/45501940-550c3280-b78b-11e8-8c42-00654820e256.PNG)

**Comment by Godmatik** [comment]
Try exiting the game and deleting the WDB folder to clear out the cache.

Or try and abandon/retake the quest.

**Comment by Orisio** [comment]
> 
> 
> Try exiting the game and deleting the WDB folder to clear out the cache.
> 
> Or try and abandon/retake the quest.

Thanks a lot! Deleting WDB folder didin't help but abandoning and retaking quest helped

**Comment by QAkvastskaft** [comment]
Some causes of this issue has been resolved but some continue...
Where did the items come from? The mailbox?

**Comment by QAkvastskaft** [comment]
#153

**Comment by jasonbourne109** [comment]
This happened to me. Dropping quests and then re-taking them fixed it.
