### ISSUE TITLE
Bonespike Shoulders not dropping

### ISSUE THREAD

**Issue by roadsterruss** [LightsHope/issues#935]
hello, on my item databank addon and the website it is showing that bonespike shoulders drop off rend. nobody has seen them equipped or dropped, even after 100's of runs. i dont want to waste my time if they arent dropping. thanks!

**Comment by Godmatik** [comment]
They are not in the game yet, they drop in a later patch.

**Comment by roadsterruss** [comment]
which patch and date on the server? ive heard so much i want resolution on the issue.

**Comment by bladezLH** [comment]
Most likely 1.10
