### ISSUE TITLE
The Defias Brotherhood

### ISSUE THREAD

**Issue by corcilius** [LightsHope/issues#936]
Cant get the final quest to kill VanCleef. Finished the escort then nothing.

**Comment by tvturnhout** [comment]
Still not working, getting the same bug.

The Defias Brotherhood quest, it is a chain that leads to the Tunic of Westfall. After killing the defias messenger you are referred back to the questgiver and it should give you the final quest, which requires to hand in the head of vancleef. 

However the last quest is not given and the chain stops too early.
