### ISSUE TITLE
HUNTER PET DISAPPEAR ALL THE TIME

### ISSUE THREAD

**Issue by EALLAH** [LightsHope/issues#939]
Hunter pet keeps disappearing when logoff or go afk.

Whenever i tame pet and go afk or log off it disappears for good.
Revive/call pet/check stables not working.

GAME SAYS I DO NOT HAVE A PET. I Dont dismiss it but it keeps disappearing for good.

Any ideas?

**Comment by Shivsproket** [comment]
You have to continually feed your pet and level it for it to gain your trust, you simply can't just tame it.

**Comment by Godmatik** [comment]
Not a bug, the pet will abandon you if you don't feed it.
