### ISSUE TITLE
Sapphiron is buged in anathema

### ISSUE THREAD

**Issue by kinjazwarlock** [LightsHope/issues#94]
we try Sapphiron after Wednesday reset. the iceblock in Sapphirons fight is buged. it cant protect us and didt work. we try one more time and it still buged.
hope u can fix that bug soon. we will try Sapphiron tomorrow!
thx a lot!

**Comment by gergunsha** [comment]
https://github.com/LightsHope/issues/issues

**Comment by gergunsha** [comment]
http://sendvid.com/ne9pjzxm

**Comment by Tartar1986** [comment]
sorry to bother
just want to confirm whether this BUG has been fixed or not?

**Comment by gergunsha** [comment]
we check yday before 19st but i think is still bugged since no res on server

**Comment by gergunsha** [comment]
ill ask other guilds

**Comment by gergunsha** [comment]
still bugged
