### ISSUE TITLE
Super Reaper 6000 - Stone Talon.

### ISSUE THREAD

**Issue by Finessexo** [LightsHope/issues#947]
The Super Reaper 6000 Blueprints don't seem to drop off of Venture Co. Operators in the Stonetalon Mountains.

**Comment by Klannoc** [comment]
Keep trying. It's a 15% drop rate.

![superreaper](https://user-images.githubusercontent.com/42480939/45604612-9881cd80-ba25-11e8-9664-f778b84fb090.png)

**Comment by Finessexo** [comment]
Thank you! Just unlucky I guess
