### ISSUE TITLE
wrong wand damage

### ISSUE THREAD

**Issue by sweetbubaleh** [LightsHope/issues#951]
Hello, i have 7 lvl Priest, and my wand shooting have wrong scale, on my wand 12-22 damage, but when i wear it i have 6-12 damage even with max wand skill. Please check it, comfort game are in danger for many peoples!(((

**Comment by Godmatik** [comment]
You have wrong cache loaded, close out the game and delete the WDB folder.

The lesser magic wand is a lot weaker in earlier patches.

**Comment by sweetbubaleh** [comment]
delete wdb folder don't help

**Comment by sweetbubaleh** [comment]
"The lesser magic wand is a lot weaker in earlier patches."- not very convincing argument mate

**Comment by Godmatik** [comment]
Was your game closed out completely when you did it? Please make sure it is so.

The lesser magic wand wasn't buffed up and made into a green item until patch 1.10, I don't need to be convincing, it just is what it is, we are on patch 1.5 and this is not a bug:

https://vanillawowdb.com/?item=11287

**Comment by sweetbubaleh** [comment]
15 silver thrown into the wind) other wands weaker too?

**Comment by sweetbubaleh** [comment]
yep, thanks for the help

**Comment by Godmatik** [comment]
Yes, greater magic wand (one you get at level 13) is also weaker.
