### ISSUE TITLE
Druid quest 'A Better Ingredient'

### ISSUE THREAD

**Issue by dyoxia** [LightsHope/issues#952]
Close to hitting 60, saw a pre-bis chest drop from an ST related quest. Item name: 'Forest's Embrace'.
Druid trainer doesn't give this quest atm. Don't know if it's not on patch 1.5 or previous but yeah I can't get the quest.

**Comment by Godmatik** [comment]
The level 50 class quests aren't available until patch 1.11, so it's a long ways off.

**Comment by QAkvastskaft** [comment]
This quest gets added in patch 1.10: http://wowwiki.wikia.com/wiki/Patch_1.10.0
"A new level 52 druid quest that takes place in Un'Goro crater has been added."
