### ISSUE TITLE
Orc hardiness 

### ISSUE THREAD

**Issue by hmellin97** [LightsHope/issues#954]
Orcs are practically immune to stuns on this server, they resist almost every stun. It's suppose to be only 15% increase but it's more like 80% resist.

Hardiness - passive
Duration of Stun effects reduced by an additional 15%

**Comment by Godmatik** [comment]
You need to provide empirical proof and a set of data for a bug report to be taken seriously here, not just conjecture and anecdotal stuff. I could say that my frostbolt resisted 5 times against a mob, and thus it's broken and needs to be fixed, but that means nothing.

P.S. It's 25% increase, not 15%.

**Comment by Gyronell** [comment]
reducing stun duration is not even what the racial does.. it gives you 25% increased chance to resist the stun entirely.

**Comment by bladezLH** [comment]
It adds a flat 25% chance to resist, which is correct. This is further increased by many class racials that affect stuns and fears.
