### ISSUE TITLE
Alzzin the Wildshaper

### ISSUE THREAD

**Issue by Muldeberg** [LightsHope/issues#958]
Hello Lightshope.

I've been farming DME jump runs with a friend for a while now. After last server maintenance the last boss in dme "Alzzin the Wildshaper" has been doing some weird stuff like resetting agro. Is this a bug or did you do this to him? If its a bug i would like a fix and if you did this i would like an explanation please.

Kind regards MUldeberg

**Comment by zelazrgn** [comment]
https://github.com/lh-server/core/pull/201

Intended
