### ISSUE TITLE
Thorium Brotherhood Reputation

### ISSUE THREAD

**Issue by bindulanija** [LightsHope/issues#962]
TB rep quests in Searing Gorge are giving 20 rep each. Other sources show different numbers, and Tanaris (BS quests) and rep turn ins are giving correct numbers. 

<img width="268" alt="screen shot 2018-09-24 at 11 56 06 am" src="https://user-images.githubusercontent.com/31020134/45946968-da48e000-bff2-11e8-9db4-5cf3e11b36c2.png">
Earliest Thottbot Archive Screenshot

**Comment by budaletina** [comment]
Keep in mind that TB quests are lower level (50 or so) quests, and doing them at lv60 will reward significantly less reputation, same as any other outleveled quest in the game.

**Comment by bladezLH** [comment]
Other databases are not to be trusted either, as many have the TBC reputation reward values.
