### ISSUE TITLE
Scourge Warder (EPL) broken loot table

### ISSUE THREAD

**Issue by budaletina** [LightsHope/issues#964]
Essence of Undeath, which should and has dropped like 90% of the time from these mobs, seems to be completely gone from their loot now.

https://vanillawowdb.com/?npc=8525

**Comment by Shivsproket** [comment]
This was recently changed due to the drop rate being too high, if you can find evidence that the drop rate should be this high please provide it.

**Comment by budaletina** [comment]
It is hard to provide any evidence on minor issues like these, Essence of Undeath never held any real value due to not being used often therefore it was never farmed and rarely mentioned. What i can say from personal experience is that veteran vanilla players always recommended farming these mobs, and several  private servers including Nost, Elysium, Kronos and LH had decent drop rates, going from 50% and up. But i do suppose it may be an internal issue if all servers used the same databases and had wrong values from start. Thank You for the confirmation on the change.
