### ISSUE TITLE
Why don't our administrators start WeChat payment?

### ISSUE THREAD

**Issue by Gruer502** [LightsHope/issues#968]
According to what we know, servers often face many difficulties, such as a shortage of funds.But there will be players who donate money to the server to help the administrator run.There are many Chinese players in this server, and they know that this situation also wants to donate to the server.
But there is no way to donate, because the way the donation is opened by the administrator is not a tool used by the Chinese. Many people want to donate and are troubled by no way.
If the administrator can register a WeChat account and open WeChat payment, bind a savings card or credit card and publicly collect the QR code. Then Chinese players can contribute their strength to the server. This server has many Chinese players who want to help the server while accepting the game service for free.
I hope that administrators can pay attention to my suggestion, because in the game forums in China, many players who wish to donate to the server cannot help the server because there is no donation method.

**Comment by DarkmoonRabbit** [comment]
一看你就应该是一个真魔兽粉！感谢你对这个服务器的支持。。。但是最近我发觉LH服真的有点不对劲了……
源码没人管了-。-开发人员出走了很多

**Comment by Gruer502** [comment]
To register a WeChat account, you only need one mobile number, and then bind a bank card with real name information, credit card. The donation can be accepted, and the donated money will be transferred to the WeChat account, which can be directly extracted into the bank card.

Most Chinese people have poor English and will not use the payment tools provided by the server. However, they are proficient in using WeChat, Alipay and other Chinese payment software, which are used almost every day. If the server has both payment methods enabled, Chinese players can donate to the server every day.
They also want to see the donation display page and the Chinese flag.

**Comment by DarkmoonRabbit** [comment]
我不是玩家，也不是LH服的管理-。-
在研究学习他们的源代码，不过我也没开服
有机会加个QQ: 2302520536 一起怀念一下魔兽世界把，哈哈
