### ISSUE TITLE
There is a problem with my account!

### ISSUE THREAD

**Issue by mylichao84** [LightsHope/issues#971]
Hello!
I am a player from China, a management of a trade union. On September 23, I mailed Mid-Autumn Festival gifts to union members in the game, because September 24 is a traditional Chinese festival: Mid-Autumn Festival! During this process, I mailed a lot of letters and finally found that I could not continue to mail the items to anyone, but I can still receive letters from others. Then there was a problem in the game that I couldn't talk privately with other players. So far, the two problems of not being able to mail items and not being able to chat privately with other players still cannot be solved. This has caused a lot of trouble for my game, I hope to help me solve it!
my character is "coperr" at LH.

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue there and a GM will assist you as soon as possible.

Thank you
