### ISSUE TITLE
Other players can't read any of my messages

### ISSUE THREAD

**Issue by Lucesacra** [LightsHope/issues#974]
I can /say /whisper and write in the general chat but other players can't read my messages.
Tested with friends.
I can't party and do dungeons like this, please help.
Best regards.

Account name: -

**Comment by Gamemechanicwow** [comment]
Make a ingame ticket.

... And remove your accountname from your post here.

**Comment by Steeldre** [comment]
Hello. My name is Steeldre on Northdale server and im lvl 11. I can't whsipering or use world chat its says in middle of screen "error". What should i to do?
Thanks for helping!

**Comment by QAkvastskaft** [comment]
Contact a GM ingame for help with solving this issue.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue there and a GM will assist you as soon as possible.

Thank you

**Comment by Steeldre** [comment]
Thank you! I maked a thicket!

QAkvastskaft <notifications@github.com> ezt írta (időpont: 2018. okt. 2.,
K, 18:58):

**Comment by Steeldre** [comment]
Can you write here GM name please?

Dávid Rózinger <steeldrey7@gmail.com> ezt írta (időpont: 2018. okt. 2., K,
20:36):

**Comment by Steeldre** [comment]
Soon i will receive whispering from a GM?
