### ISSUE TITLE
Sylvanas, repop time

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [LightsHope/issues#975]
Hi,

sylvanas died the 30/09/2018 in late afternoon (no screen shot but she would have died between 5pm and 8pm).

I use to find on internet the repop time should be around 2hours.

Around 12 am the 01/10/2018 , she is still not  repoped.

On the server database there is no information about it : https://vanillawowdb.com/?npc=10181#starts

Thank's for making her repoped , or sharing any information concerning her repop time.
Best regards

**Comment by QAkvastskaft** [comment]
Current respawn time is 24h. (Hover over the small icon on the map in the link above)
