### ISSUE TITLE
banned without breaking any rules 

### ISSUE THREAD

**Issue by Importantrespect** [LightsHope/issues#977]
Greetings I have a question and a very alerting issue which requiers your help for i do not know what to do from here   regarding my partner's account being banned for false "GM impersonation" 30.09.2018
My girlfriend (21st level Night elf druid "Jojoto ") was runing deadmines with a group  she could not heal propperly so she got kicked and i assume got  reported by those same kids group so she
left the dungeon and logged off. A few hours later about 17:00h she tried to log back in and turns out she got banned for "GM impersonation" which is in and of it self an absurd reason,however she did no such thing nor is it possible since she cannot speak english more than a few basic sentances and did not try to imeprsonate in any way a GM  please help she loves the game and vanilla and this is abusrd  ,my question is how can you have such an approach towards such important alligations and procedures and how do you allow banns to be executed from your staff without any propper trail, any kind of reasonable evidence and just bann accounts without real evidence  and simply draw conclusion on basis of the reports of a few  kids ? Needless to say i am speechless and this speaks very poorly about the process  of staff regarding such important issues and tasks .Im sorry for  being impolite but  i am shocked and disgusted  and i have no idea who to turn to about this ridiculous bann  please this issue needs your attention

**Comment by Gamemechanicwow** [comment]
>needs your attention

Nope. You are talking to the wrong ppl.

> Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. 

She should logon to the website and file a banappeal.

**Comment by QAkvastskaft** [comment]
This is not the correct location for this, ban appeals should be submitted on the project site.

Please read the following before proceeding:
[Ban appeal info](https://lightshope.org/faqs/faq-account-suspended-closed)

Thank you
