### ISSUE TITLE
Banned for no reason , still waiting for an answer to my appeal 

### ISSUE THREAD

**Issue by Zdik23** [LightsHope/issues#983]
i was wandering in Scarlet Monastery and i was having some lag issues. At a certain moment i got a huge lag spike, i was kicked from the game. I can't login anymore beacause it says that i was cheating wich is certainly a false positiv. Thank you for your consideration, hopefully i can get back my account soon

**Comment by QAkvastskaft** [comment]
This is not the correct location for this, ban appeals should be submitted on the project site.

Please read the following before proceeding:
[Ban appeal info](https://lightshope.org/faqs/faq-account-suspended-closed)

Thank you
