### ISSUE TITLE
Quest problem in wetlands

### ISSUE THREAD

**Issue by bhajeb** [LightsHope/issues#987]
Hello. I was questing in wetlands and got the quest from the npc in front the inn named First mate fitzsimmons. It is a chain quest. After geting all the chains. The last quest was to get an cursed eye from dead sailors and get it cleansed. I got the eye but i acidentally destroyed the item from my bag cuz i didnt pay attention. After that i panicked and abandoned the quest in hopes i can retry it again. Unfortunantely the npc no longer gives the quest or talks for that matter. So im stuck. I would be willing to go through the entire chain once again but only if its possible to reset or unbug this. Is there a solution to this problem of mine or should i just forget about it?

Thank you for any feedback.

**Comment by Gamemechanicwow** [comment]
I suppose it is this part: https://vanillawowdb.com/?quest=292 ?

You pick up the quest from the lockbox.

**Comment by bhajeb** [comment]
In order to open the lockbox i need the key, the key I do not have, cuz the NPC is supposed to give me that. I wrote that NPC does not talk to me anymore.

**Comment by Gamemechanicwow** [comment]
Have you tried? 

Part 3 requires the key.
Part 4 requires part 3 completed. Not that you have the key.

**Comment by bhajeb** [comment]
So youre telling me to go to the boat. And dive to the bottom and reopen the black chest thats down  there? The boat that has the goblin captain on it?

**Comment by bhajeb** [comment]
> Have you tried?
> 
> Part 3 requires the key.
> Part 4 requires part 3 completed. Not that you have the key.

Hey man. I tried what you said and it worked. THe chest that was in the second boat at the bottom gave me the quest anyway and I was abble to finish it. Thanks a bunch!!
