### ISSUE TITLE
Northdale: Arathi basin lost even though we had more resources

### ISSUE THREAD

**Issue by sind0u** [LightsHope/issues#990]
Hello,

today was the 2nd time we (the alliance) lost an Arathi Basin except we had more resources. The game has been closed due to the fact there weren't enough players. At the closing time the alliance had about 3xx resources and the horde only 1xx.

Afaik only resources are the factor of winning or not winning, right? If yes, looks like there's a bug.

Greetings,
Jan

**Comment by bladezLH** [comment]
Games that close early do not give winner rewards based on the current score.
