### ISSUE TITLE
Furious Howl buffs but doesn't consume on melee white attacks

### ISSUE THREAD

**Issue by Azizxoxo** [LightsHope/issues#993]
**Current behavior:** Furious Howl increases damage dealt by ranged physical attacks and consumes the buff after it's been used for ranged white and yellow hits. Furious Howl increases damage dealt by melee physical attacks and consumes the buff for yellow hits **_but doesn't consume it for white melee hits._**

**Expected behavior:** Furious Howl increases damage dealt by ranged physical attacks and consumes the buff after it's been used for ranged white and yellow hits. Furious Howl increases damage dealt by melee physical attacks and consumes the buff after it's been used for melee white and yellow hits. 

**Evidence:** 
https://streamable.com/9vxqa
White attacks hits the spider for 145 damage, furious howl is used and buffs the damage to 183 and the buff is consumed afterwards. Tested with https://classicdb.ch/?item=15808 a static damage ranged weapon.

https://streamable.com/rmakm
White attacks hits the cat for 92-93 damage, furious howl is used and buffs the damage to 128-129 and the buff isn't consumed afterwards. Tested with https://classicdb.ch/?item=35 .

**Comment by vindruvor** [comment]
still bugged

**Comment by bladezLH** [comment]
Is not currently affecting melee attacks, hence not consumed.
