### ISSUE TITLE
Nemesis Raiment 3-set bonus

### ISSUE THREAD

**Issue by fgsfdss** [LightsHope/issues#994]
**Currently:** (3) Set: Increases damage and healing done by magical spells and effects by up to 23.

**Should be:** 3: Reduces the casting time of your Enslave Demon spell by 1.5 sec.

https://web.archive.org/web/20051223181149/http://www.thottbot.com:80/?i=37836

Changed with 1.9, as the rest of the T2 updates. (Might be good to check other sets' bonuses as well.)

**Comment by bladezLH** [comment]
See https://github.com/LightsHope/issues/issues/995
