### ISSUE TITLE
Set Bonus for Magister's Regalia, Arcanist Regalia and Netherwind Regalia are incorrect for patch 1.5

### ISSUE THREAD

**Issue by Shivsproket** [LightsHope/issues#995]
According to the archived version of Thottbot.

**Magister's Regalia**
**Currently:**
(2) Set: +200 Armor.
(4) Set: Increases damage and healing done by magical spells and effects by up to 23.
(6) Set: When struck in combat has a chance of freezing the attacker in place for 3 sec.
(8) Set: +8 All Resistances.

**Should be:**
(3) Set: Increases damage done by Frost spells and effects by up to 7.
(5) Set: +5 Frost Resistance.
(5) Set: +5 Fire Resistance.
(5) Set: +5 Arcane Resistance.
(6) Set: Increases damage done by Arcane spells and effects by up to 21.
(7) Set: Increases damage done by Fire spells and effects by up to 27.
(8) Set: Restores 8 mana every 5 sec.
(8) Set: +10 Intellect.
https://web.archive.org/web/20051129202913/http://www.thottbot.com:80/?set=181#

**Arcanist Regalia** seems to have 3 different Set bonuses over the course of the game. I am unsure of the timeline.

**Currently:**
(3) Set: Increases damage and healing done by magical spells and effects by up to 18.
(5) Set: Decreases the magical resistances of your spell targets by 10.
(8) Set: Decreases the threat generated by your spells by 15%.

**Initially should be:**
(3) Set: You have a 1% chance to regain 1 mana any time you take damage.
(5) Set: Increases the duration of your Polymorph by 5 sec.
(8) Set: Increases the added fire damage of your Fireballs by 24 per period.
(8) Set: Increases the duration of your Arcane Missiles by 1 sec.
(8) Set: Your Frostbolts do 45 extra damage.
https://web.archive.org/web/20050525083125/http://thottbot.com/?i=26877

**Should then become:**
(3) Set: Damage absorbed by Fire Ward and Frost Ward is increased by 10%.
(5) Set: Increases the duration of your Polymorph by 15 sec.
(8) Set: Decreases the threat generated by your spells by 15%.
https://web.archive.org/web/20051112111508/http://thottbot.com:80/?set=201#

**Netherwind Regalia**
**Currently:**
(3) Set: Reduces the threat generated by your Scorch, Arcane Missiles, Fireball, and Frostbolt spells.
(5) Set: Increases the radius of Arcane Explosion, Flamestrike, and Blizzard by 25%.
(8) Set: 10% chance after casting Arcane Missiles, Fireball, or Frostbolt that your next spell with a casting time under 10 seconds cast instantly.

**Should be:**
(3) Set: Reduces the threat generated by your Arcane Missiles, Fireball, and Frostbolt spells.
(5) Set: When struck in melee, 2% chance you are protected from all physical attacks and spells for 2 sec
(8) Set: 10% chance after casting Arcane Missiles, Fireball, or Frostbolt that your next spell with a casting time under 10 seconds cast instantly.
https://web.archive.org/web/20050530060054/http://www.thottbot.com/?set=210

Most of these seem to be changed in Patch 1.9.

**Comment by Bloodmoon-Darrowshire** [comment]
Set bonus is in client side not server.

**Comment by Shivsproket** [comment]
> 
> 
> Set bonus is in client side not server.

I'm not sure exactly what you mean, but if you are talking about clearing my WDB folder then I do that every time I launch the game so it isn't because my WDB folder being out of date. The set bonuses are itemized for patch 1.9 while the gear itself is appropriately itemized for the current patch.

**Comment by Bloodmoon-Darrowshire** [comment]
Stats of set bonus is in .dbc file whitch packed in one of .mpq file - its client side. If you want to chenge stats of setbonus you need change client. Server side support only 1.12.1 and have final stats of setbonus.

**Comment by bladezLH** [comment]
While we could theoretically implement alternate set bonuses, they would not be rendered correctly for the client since as mentioned, the display is defined client-side.
